### ISSUE TITLE
关于vue <script setup>的使用问题

### ISSUE THREAD

**Issue by SnowingFox** [vexip-ui/vexip-ui#133]
我看了几个组件的代码，几乎都没有使用`<script setup>`是有什么顾虑吗

**Comment by qmhc** [comment]
有几个原因：

1. 可配置的 props 默认值的特性，需要在原 props 上做一层包装，在 `<script setup>` 时会对模版暴露两个 props
2. 使用 `<script setup>` 在打包后的类型推断上具有局限性，需要人为的定义 props 的类型，以及对外暴露 api 方法或变量时需要单独定义（这点在用 tsx 时也有这个问题）
3. 在定义组件名、`inheritAttrs` 等属性时需要借助一些外部插件来支持 `defineOptions` 或者需要一个独立的 `<script>`

目前来说 `<script setup>` 对组件库的改善上利处没有足够大，而且重构代码也需要不小的成本
