### ISSUE TITLE
Layout支持router属性

### ISSUE THREAD

**Issue by zhang19980518** [vexip-ui/vexip-ui#140]
Layout组件支持Menu组件的router属性吗,如果支持，用法上有什么区别

**Comment by qmhc** [comment]
你可以看看这个文档的用例 https://www.vexipui.com/zh-CN/components/menu#%E4%BD%BF%E7%94%A8%E8%B7%AF%E7%94%B1 是否满足你的需求

**Comment by zhang19980518** [comment]
<Layout v-else logo="https://www.vexipui.com/logo.png" sign-name="Joert UI" :router="router"
    @user-action="handleUserAction">
    这是我的layout
    const router = createRouter({
    history: createWebHistory(import.meta.env.BASE_URL),
    routes: [
        {
            path: '/',
            name: 'login',
            component: Login,
            meta: {
                layout: 'login',
                name: "登录",
                menu: false,
            }
        },
        {
            path: '/manager',
            component: Demo,
            meta: {
                label: '1',
                name: '首页',
                icon: EnvelopesBulk
            },
            children: [
                {
                    path: 'manager/list',
                    component: About,
                    meta: {
                        label: '1-1',
                        name: '子菜单 1'
                    }
                }
            ]
        },
    ]
})

export default router
这是我vue router
<img width="1296" alt="image" src="https://user-images.githubusercontent.com/35387407/189295066-fa97f6f3-ff71-4506-8fbf-99b006569bd5.png">
此时页面是空白的

**Comment by zhang19980518** [comment]
<img width="1304" alt="image" src="https://user-images.githubusercontent.com/35387407/189295352-a678d4cb-b1c0-48a5-a42d-cd5b35531137.png">
我的router在另一个文件里面

**Comment by qmhc** [comment]
在 Layout 组件中传递 Menu 的其他 props 需要通过 `menu-props` 属性进行传递：

```vue
<template>
  <Layout :menu-props="{ router }"></Layout>
</template>
```

**Comment by zhang19980518** [comment]
好的  已经解决 谢谢大佬  提前祝大佬中秋节快乐
