### ISSUE TITLE
表格组件添加自定义单元格

### ISSUE THREAD

**Issue by jamespatriot** [vexip-ui/vexip-ui#154]
能自定义的单元格的内容，样式，事件等等。

**Comment by qmhc** [comment]
是否能举例更具体一些的应用场景？这样在设计 API 时能更具有针对性。

目前行和列都可以自定义类名，单元格内容也提供了插槽，我大概能想到的可能是单元格的移入移出事件之类的？

**Comment by jamespatriot** [comment]
如：在单元格上添加鼠标事件，目前可否实现？
用renderer实现时报错：Maximum call stack size exceeded

`const columns = ref(
  defineColumns([
    {
      name: 'First Name',
      key: 'firstName',
      renderer: (d)=>h('div',{
        onClick: 'alert(111)'
      },d.row['firstName'])
    },
   
  ])
)`

**Comment by qmhc** [comment]
初步构想是添加几个针对单元格的属性：`cell-class`、`cell-style`、`cell-props`

以及添加上针对单元格的事件：`cell-enter`、`cell-leave`、`cell-click`、`cell-dbclick`、`cell-contextmenu`

也补充两个针对行的事件：`row-dbclick`、`row-contextmenu`

看看这样子能否满足你的需求？

**Comment by jamespatriot** [comment]
> 初步构想是添加几个针对单元格的属性：`cell-class`、`cell-style`、`cell-props`
> 
> 以及添加上针对单元格的事件：`cell-enter`、`cell-leave`、`cell-click`、`cell-dbclick`、`cell-contextmenu`
> 
> 也补充两个针对行的事件：`row-dbclick`、`row-contextmenu`
> 
> 看看这样子能否满足你的需求？

太好了，最好还可用使用h()函数创建vnode。

**Comment by qmhc** [comment]
使用 Column 选项的 `renderer` 属性可以用过 `h` 来渲染内容的。

同时现在新增了 `cell-attrs` 之后可以通过 `onXxx` 绑定一些事件。
