### ISSUE TITLE
Layout使用MenuExposed

### ISSUE THREAD

**Issue by zhang19980518** [vexip-ui/vexip-ui#156]
因为我的layout 布局已经指定 :menu-props={router}  还能用Menu的MenuExposed方法吗

<img width="946" alt="image" src="https://user-images.githubusercontent.com/35387407/190967609-d0489550-ffda-4449-9ae4-8675c3ce8c05.png">

<img width="424" alt="image" src="https://user-images.githubusercontent.com/35387407/190967664-592bb954-dba3-407f-9a08-bf691e6c6495.png">

**Comment by qmhc** [comment]
```ts
import { ref, onMounted } from 'vue'

import type { MenuOptions } from 'vexip-ui'

const layout = ref(null)

onMounted(() => {
  layout.value.expandMenuByLabel('label')
})
```

将在下一个 patch 版本发布。
