### ISSUE TITLE
Layout使用LayoutExposed

### ISSUE THREAD

**Issue by zhang19980518** [vexip-ui/vexip-ui#161]
<img width="516" alt="image" src="https://user-images.githubusercontent.com/35387407/191448460-1a74f323-51f1-4b6e-b3a1-5325e01607ba.png">
正常引入后 报错
<img width="411" alt="image" src="https://user-images.githubusercontent.com/35387407/191448567-b51dbd65-a968-44c7-874d-d324232df5b9.png">

**Comment by qmhc** [comment]
这应该是一个 ts 错误，layout.value 可能为 `null`，你需要先进行判断。

**Comment by zhang19980518** [comment]
好的

**Comment by zhang19980518** [comment]
什么情况下不为空  下面这种写法它会一直为null
<img width="908" alt="image" src="https://user-images.githubusercontent.com/35387407/191450628-46300a19-f691-4f4a-8094-2d10aac37bae.png">
<img width="523" alt="image" src="https://user-images.githubusercontent.com/35387407/191450693-408ae372-5d7b-4f9e-9663-3b268cddcc41.png">

<img width="426" alt="image" src="https://user-images.githubusercontent.com/35387407/191450752-84a4f9b6-1a26-48db-9d24-de4571f7ec26.png">
<img width="496" alt="image" src="https://user-images.githubusercontent.com/35387407/191450872-52515df1-2385-4f9c-ac6c-5c2d153c6b57.png">

**Comment by qmhc** [comment]
你模版中的 `ref="menu"` 应该为 `ref="layout"`

**Comment by zhang19980518** [comment]
我的错
