### ISSUE TITLE
Bug(Bubble): Newline behavior

### ISSUE THREAD

**Issue by YangFong** [vexip-ui/vexip-ui#164]
![image](https://user-images.githubusercontent.com/70502828/192100708-e524f173-82ab-4c35-a151-c2ba6ace7a05.png)

**Comment by qmhc** [comment]
Could you provide the SFC link address?

**Comment by YangFong** [comment]
> Could you provide the SFC link address?

https://playground.vexipui.com/#eyJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2ZXhpcC11aVwiOiBcImh0dHBzOi8vcGxheWdyb3VuZC52ZXhpcHVpLmNvbS92ZXhpcC11aS5qc1wiLFxuICAgIFwiQHZleGlwLXVpL2ljb25zXCI6IFwiaHR0cHM6Ly9wbGF5Z3JvdW5kLnZleGlwdWkuY29tL3ZleGlwLXVpLWljb25zLmpzXCIsXG4gICAgXCJAdmV4aXAtdWkvdXRpbHNcIjogXCJodHRwczovL3BsYXlncm91bmQudmV4aXB1aS5jb20vdmV4aXAtdWktdXRpbHMuanNcIixcbiAgICBcInZ1ZS1yb3V0ZXJcIjogXCJodHRwczovL3BsYXlncm91bmQudmV4aXB1aS5jb20vdnVlLXJvdXRlci5qc1wiLFxuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9wbGF5Z3JvdW5kLnZleGlwdWkuY29tL3Z1ZS5ydW50aW1lLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJ2dWUvc2VydmVyLXJlbmRlcmVyXCI6IFwiaHR0cHM6Ly9wbGF5Z3JvdW5kLnZleGlwdWkuY29tL3NlcnZlci1yZW5kZXJlci5lc20tYnJvd3Nlci5qc1wiXG4gIH1cbn0iLCJtYWluLnRzIjoiaW1wb3J0IHsgY3JlYXRlQXBwIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgaW5zdGFsbCB9IGZyb20gJ3ZleGlwLXVpJ1xuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgVGhlbWVTd2l0Y2ggZnJvbSAnLi9UaGVtZVN3aXRjaC52dWUnXG5cbkFwcC5uYW1lID0gJ1JlcGwnXG5cbmNvbnN0IGFwcCA9IHdpbmRvdy5fX2FwcF9fID0gY3JlYXRlQXBwKEFwcClcblxuYXBwLmNvbmZpZy51bndyYXBJbmplY3RlZFJlZiA9IHRydWVcbmFwcC5jb25maWcuZXJyb3JIYW5kbGVyID0gZSA9PiBjb25zb2xlLmVycm9yKGUpXG5cbmFwcC51c2UoaW5zdGFsbClcblxubmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gIGxpbmsuaHJlZiA9ICcuL3N0eWxlLmNzcydcbiAgbGluay5vbmxvYWQgPSByZXNvbHZlXG4gIGxpbmsub25lcnJvciA9IHJlamVjdFxuICBkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKGxpbmspXG59KS50aGVuKCgpID0+IGFwcC5jb21wb25lbnQoJ1RoZW1lU3dpdGNoJywgVGhlbWVTd2l0Y2gpLm1vdW50KCcjYXBwJykpXG4iLCJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8QnViYmxlPmFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhPC9CdWJibGU+XG4gICA8QnViYmxlPuS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4reS4rTwvQnViYmxlPlxuXG4gIDwhLS0gVGhpcyBpcyB0aGUgZGFyayB0aGVtZSB0cmlnZ2VyIC0tPlxuICA8VGhlbWVTd2l0Y2g+PC9UaGVtZVN3aXRjaD5cbjwvdGVtcGxhdGU+XG4iLCJUaGVtZVN3aXRjaC52dWUiOiI8dGVtcGxhdGU+XG4gIDxkaXYgc3R5bGU9XCJwYWRkaW5nOiAyMHB4IDA7XCI+XG4gICAgPHNwYW4gc3R5bGU9XCJtYXJnaW4tcmlnaHQ6IDEwcHg7XCI+VG9nZ2xlIERhcms6PC9zcGFuPlxuICAgIDxTd2l0Y2ggdi1tb2RlbDp2YWx1ZT1cImlzRGFya1wiIGNsYXNzPVwidGhlbWUtc3dpdGNoXCIgOm9wZW4taWNvbj1cIk1vb25cIiA6Y2xvc2UtaWNvbj1cIlN1blwiPjwvU3dpdGNoPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHdhdGNoIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgU3VuLCBNb29uIH0gZnJvbSAnQHZleGlwLXVpL2ljb25zJ1xuXG5jb25zdCByb290Q2xzID0gZG9jdW1lbnQuZG9jdW1lbnRFbGVtZW50LmNsYXNzTGlzdFxuY29uc3QgaXNEYXJrID0gcmVmKHRydWUpXG5cbmlmIChpc0RhcmsudmFsdWUpIHtcbiAgcm9vdENscy5hZGQoJ2RhcmsnKVxufVxuXG53YXRjaChpc0RhcmssIHZhbHVlID0+IHtcbiAgdmFsdWUgPyByb290Q2xzLmFkZCgnZGFyaycpIDogcm9vdENscy5yZW1vdmUoJ2RhcmsnKVxufSlcbjwvc2NyaXB0PlxuXG48c3R5bGU+XG5ib2R5IHtcbiAgY29sb3I6IHZhcigtLXZ4cC1jb250ZW50LWNvbG9yLWJhc2UpO1xuICBiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS12eHAtYmctY29sb3ItYmFzZSk7XG4gIHRyYW5zaXRpb246IHZhcigtLXZ4cC10cmFuc2l0aW9uLWNvbG9yKSwgdmFyKC0tdnhwLXRyYW5zaXRpb24tYmFja2dyb3VuZCk7XG59XG5cbi50aGVtZS1zd2l0Y2gge1xuICBib3JkZXI6IDFweCBzb2xpZCB2YXIoLS12eHAtYm9yZGVyLWNvbG9yLWJhc2UpO1xufVxuXG5odG1sLmRhcmsgLnRoZW1lLXN3aXRjaCB7XG4gIC0tdnhwLXN3aXRjaC1iZy1jb2xvci1vcGVuOiAje3JnYmEoI2ZmZiwgMC4wNSl9O1xuICAtLXZ4cC1zd2l0Y2gtc2lnbmFsLWJnLWNvbG9yOiAjMDAwO1xuICAtLXZ4cC1zd2l0Y2gtaWNvbi1jb2xvcjogdmFyKC0tdnhwLWNvbnRlbnQtY29sb3Itc2Vjb25kYXJ5KTtcbiAgLS12eHAtc3dpdGNoLXNoYWRvdy1mb2N1czogdW5zZXQ7XG59XG48L3N0eWxlPlxuIn0=

**Comment by qmhc** [comment]
I think this may differently behaviors of `word-break` in different languages causing this issue.
