### ISSUE TITLE
Image loading failed   

### ISSUE THREAD

**Issue by YangFong** [vexip-ui/vexip-ui#165]
![image](https://user-images.githubusercontent.com/70502828/192729636-caf3bc33-1981-4dc2-8ad2-a1ec42a4e118.png)

---

localhost:

![image](https://user-images.githubusercontent.com/70502828/192729770-4ad01013-5002-4c29-999d-3690d0279c43.png)

**Comment by qmhc** [comment]
这是打包过程的生成压缩包存在问题，使用原始打包文件重新部署后已正常

**Comment by YangFong** [comment]
已确认恢复
