### ISSUE TITLE
`<Input>` value update design

### ISSUE THREAD

**Issue by YangFong** [vexip-ui/vexip-ui#169]
为什么现在的表现是失去焦点之后，才会更新数据，这有点不解。先不谈是否存在调整方式，现在的默认形式与多数设计不一。

![动画](https://user-images.githubusercontent.com/70502828/194868406-b3b1dcdc-e90f-44b2-88dc-77131b084804.gif)

**Comment by qmhc** [comment]
因为在 Api 设计上，双向绑定均基于 `change` 事件，以做到统一，不希望 Input 是特例。

不过考虑到确实会出现希望通过 input 事件双向绑定的场景，我觉得可以增加一个属性显式地控制这个行为。
