### ISSUE TITLE
Error: 找不到模块“@vexip-ui/icons”或其相应的类型声明

### ISSUE THREAD

**Issue by xiziliang** [vexip-ui/vexip-ui#172]
项目的`common/icons/src`下是不是缺少了index文件
<img width="987" alt="image" src="https://user-images.githubusercontent.com/54427136/195550682-cb6f7ebe-d71a-4085-97ca-04a07e74d40e.png">

**Comment by qmhc** [comment]
如果是初次运行项目前，需要先在根目录执行一次 `pnpm run build:common` 构建一次通用模块，见 [贡献指南](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md#setup)。

**Comment by xiziliang** [comment]
我在`build:common`会报错，所以我单独跑了下，发现在`build:utils`和`build:hooks`的时候会报错
<img width="1529" alt="image" src="https://user-images.githubusercontent.com/54427136/195575771-3c5905c8-f482-4354-a127-a3bc9876edda.png">
下边是我的node和pnpm版本
<img width="452" alt="image" src="https://user-images.githubusercontent.com/54427136/195575948-91d457e4-8bda-4065-8350-64569c53b321.png">

**Comment by qmhc** [comment]
你在安装时是否使用了非 `npm` 源？

**Comment by xiziliang** [comment]
> 你在安装的时候是否使用了非`npm`源？
这个没有

**Comment by qmhc** [comment]
这是由于上游 `@microsoft/api-extractor` 升级到了 `7.33` 之后出现了一些变化导致的，目前正在适配，将 `@microsoft/api-extractor` 版本锁在 `7.32.0` 可以暂时解决。

**Comment by qmhc** [comment]
使用最新的 `vite-plugin-dts@1.6.6` 应该不会出现此错误了。

**Comment by xiziliang** [comment]
可以了👍
