### ISSUE TITLE
[Style Experience][Form]: Negative margin

### ISSUE THREAD

**Issue by YangFong** [vexip-ui/vexip-ui#187]
## 描述

默认情况下，`<Form>` 会带有 `margin: 0px -4px` 的行内样式，这导致在某些情况下，会导致宽度超出，出现滚动条。

> [情况复现](https://playground.vexipui.com/#eNqVVV1v2zYU/Suc8mAZsGh3wF60JNvQbViAFSjaPgoIaImW2FCkQFJ2gsD/vYekLMlOWqRAAov33nN4P46unhPRdtq4rGUd/Wq1SvLkuVCEFIPDFklOgsXb9vxRdFkvvLFIGuc6m6/XnWRPtdG9qmgI6AUtdbs+BYO3SFYnij9P5rUotQr0b2bKAuR7fL0T8if5AuScb9/zDAjHzduoxvAXNG/FU9MrJ1pOuW2zrdEH+wrZGsY9N5nhquLmjcldYF5c4PmPhTomq6RlQlFnMf44d/JMSsOZ4391HTmSndEtWSCPRaHGAKGsY1JO7qGtU4wHRx9d45meEXxpeMs/H4QrmzFoZhuCC+WBirWc3JDFJ97JYPRCcISB/4YchKr0gd7f43h/D8OYeYr/pQ+HBx1RO1HTXh0M6+7UV146Xn3iOwCcwbjmQdwYbf5jqpLcwI+7b4m/UkuMyftSPvL2lqdDK4JN8QP5iHoE7KnhwOz5ihjuL1x6ovA6xQKkUA/gr3TZt1w5GjP/R6ILyqUL716AlIRAarj0TbDuSXLbcO7QisHVmFAIWhi8tLR2cmolNavgHrKZOUIxwePT844xl62unigKhHreN0JWqYcgmeOSuoarNA3FxKZhoipkPBvgYjUf8ZK20CciroBYLMED1Q2agOquHW+hYsdvfQ7XldiTUMhNkRxE5ZqcvNts9ociCX5E/KtNS/JWV1wiZodTkZC58w6MRLJt8N+prncI6IzucBTxOIQDEPy31+v4O7CsTzQ/pn13wYvzTxHH4/CIwvEUnn/JMjRQWII/NJxUzDz4B7wJzoi6hjKzLMJmfcZd81Ohrtez1uIY2hpgfsCn3d4yUwuVk83vw1K4jkIaMKURnSOWu75D8apGrf7TAO+4DaDc0ok9v9gWp1fVTyjoLEalz0dIAJcEZvBADRcv/49V0bGqEqrOya+b7tGnPSrDdkyNYbGuDP1qnNdQ9+gjv+i6lpz8jY7myAGAE3jYR/ssKCvfM9l7GmF9LAZdSmatr97nmtkQDXOu8ZqEzxN8H7RW3lZKbfnJ+LmHDcMZ5zJN+8WE3tTt3YocmM/1O9sZF66IT2UMuPj0zoZjtHbvpZ1votPDsItoKPx/YbEjIia2JIx0l/oFGpaf2JE0emjo3TIKbLiAYmjpwgvZbzWorFChhgGyIgEz7sh4+uM1NMlHq+GthqAm2nNhzSQ/Cb7UUpscF5g0y/aPXYaaHMrELxzZllm+DG/ClpUP8csaXXPMtn4R7gxTVjih8SpNgZM1Apa+0Fec02WeLbTHr9pRaDH3rTb4nEPM0D3WuajmKQXfRVqBqHGtpGGFvEIZwdEyleU1nZOrZ1NvWXq120FxG7r5bXkMpZ5hrKgVkyMUqM0mrpKzMK+7l308773lOCPRp9jR82sahi99toM2bU56hVck1jdtq+T4DamJwSs=)

若想覆盖该表现，就需要指定 `style` 或 `gap` 来控制。我想是否可以将 `gap` 默认值调整为 `[0,0]`，这样便于观察，减少改动（使用默认）。

## 其他

近期经历 `<img>` `line-height` 与 `<Form>` 负外边距问题，就发现页面上总能出现滚动条，困惑不已（在使用 `vw` 与 `vh` 长度单位时发生）。

**Comment by qmhc** [comment]
我将 Row 的间距样式作用在 css 变量上，以消除行内样式直接绑定 margin，以达到用户可以通过样式修改 margin。

**Comment by YangFong** [comment]
说起来也是，其实闹心的，`margin` 是行内 `style` 形式，导致不得不书写行内 `style` 覆盖，而不能通过 `class` 样式控制。
