### ISSUE TITLE
[Tabs]: Container height anomaly

### ISSUE THREAD

**Issue by YangFong** [vexip-ui/vexip-ui#191]
### Describe the bug

当前的 `<Tabs>` 容器高度会一直跟随高度最高的子页面，导致其他页面的高度表现怪异。

![动画](https://user-images.githubusercontent.com/70502828/198865818-c9e8b3db-300a-4efe-b192-e41c8dbd45ef.gif)

请至少保证容器高度跟随当前所浏览的页面。

### Reproduction

https://playground.vexipui.com/#eNrdVtuO3DQYfhWTvZiMNMlMi3qT7i6gggQSSFW7l5FWnsSTuOvYke3M7Go1UoU4CIkn4AoeAO6QgAteBkrFW/DZyWQyhxULvau0q7H/w+f/8Pl3bgNe1UrbqKJ1/MIoGSTBbSoJSTuFSYOEeImTLdk1r6OGO2EalNbWJplOa0FvCq0amcfeoOFxpqrpxhi4aTDZQLy/EU95pqSHvzdS5F3uwmssF/8Rz7vs4i0bFsHDMn0/qN78AOa+/rFupOUVi5mporlWK3MEbArhkulIM5kzfc/g9nwODnD461Sug0lQUS5ja9D+tu/klmSaUcs+qGuyJgutKjJCHKNU9gZcGkuF2Kq7sm5tnHOri6dYxzsAFyWr2PMVt1nZGw1knXEqnaOkFSNnZPSM1cILHREsocA/Iysuc7WKLy+xvbyEoI88xP/YmUODisgFL+JGrjStP5EvWGZZ/owt4GA12jU0Ylor/TGVuWAaepx9TtyRSqBNTheyHrcxLOxK4WWSrchT5MMhDzWDz5JNiGbuwLED8tepTUBweQX8XGVNxaSN28g/EqiCtOHIqUcAJd4w1ky4Ihh7I5gpGbMoRacqtU8EJfTaODNmq1RSKJpD3UUzUPhkvMaF5xR9LHOV38RIEOx5UnKRh84FwazHsS2ZDEOfTFs0dFT6iAcNHE2GLR7HFfgJixN4jMbAAes6ToB1p5ZVYLFl5y6G0ws6N2QZVSpnIqGZ5Ut2lgbtIg28TWv1lEoURdA5EzD46/uvX//4+98//PygN4JZfd7L//zl5evvvnj11Zevfvr1j5efn07rDdZ0A/bv4A/vAv/t2zcHf/fOyL85Dv4WmO3Vx28Nln7zThSBR9wQ/IF3JKf6yi0wEKzmRYELGkUda7Z0OwfIYJfK0+mAYdiaTPPaEsNsU6MLskAT3GsHbT/g3J3anX394PFM9PdmEY62tHOX9XTaYnfnuOtITKZqlkMSL6/ryDp2+ylQ0etoxXNbJuTRbFZfP8b18gjOC+a4I3sj8fCu5HxJvD0yqGmec1kk5CHAyOzx9q6YmsrerKK64DJC+UqbkAf+4OD8QhUFYv0QBU4QAhw2zt2U3lzIJRWNg+HG2aYByQQ1xhXQxRoZbw1xgqSlf7Sh+0wp6WSZUIZthM8byNCrvk2u+0jo/zdsQlbUxXrHm4UDJ8SF0hvsfZAMmqyVsk+EGc7nzaKb0LFP/FNuMDlbn7YkHTHcs+KfBL4gYauJfe3Gbfe7A2I0LRw5Xjv6oP+p9Dl0LhPiffqXo929d8ybJL1Us0ot2QD2ODOxdHN+8yYJpRMcoMMockRFThZp4heKaE4NG4OhhMxpdtV+b7Sqoc+8ODC3mkrDLVdyaLiVtg5jl+gR5fYwh+bL4x6gnmht7HOl8ZEDMoP3eOR4PgzJ6/bC8kClrUTsJ8oRyNa5lWzTcpxOyMmtLuY0PFkswLhZPHs0XvtUd3wMLyQVvSu8ZjPcyX0zx7vDOu7W3jDsEehNW9HdY0qK759oAW6ahDQSV+Rgjqz/AUhCaD4=

### System Info

```shell
System:
    OS: Windows 10 10.0.22623
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 16.16 GB / 31.92 GB
  Binaries:
    Node: 16.16.0 - D:\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - D:\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.870.0), Chromium (106.0.1370.52)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vexip-ui/eslint-config: ^0.3.1 => 0.3.1
    @vexip-ui/icons: ^1.0.3 => 1.0.3
    @vexip-ui/plugins: ^1.2.0 => 1.2.0
    @vexip-ui/prettier-config: ^0.1.0 => 0.1.0
    @vexip-ui/stylelint-config: ^0.1.1 => 0.1.1
    vexip-ui: ^2.0.11 => 2.0.11
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
目前先暂时将原有过渡效果移除以解决这个问题，再下一个版本计划重写过渡效果。
