### ISSUE TITLE
[message]: missing close callback

### ISSUE THREAD

**Issue by YangFong** [vexip-ui/vexip-ui#211]
### Description

当前的消息提醒，没有提供关闭回调函数。

看上去是有点无厘头，因为这只是消息提醒，而不是确认框。

### Suggested solution

当消息提醒关闭之后，执行（可选）对应的回调函数（也可以是 Promise 风格）。

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that request the same feature to avoid creating a duplicate.

**Comment by qmhc** [comment]
能否秒速一下具体的应用场景？

**Comment by YangFong** [comment]
细想了一下，我说不上必要的场景，因为存在对应的方式达到这种效果。说是必要的，似乎很不自然。

**Comment by qmhc** [comment]
如果是有具体业务场景的话可以描述一下，我们可以一起具体分析。

**Comment by YangFong** [comment]
就是后续发现，很多场景都可以自己完成模拟，并不是非要使用关闭回调不可，反而说，关闭回调中不知道做什么好，都不太合适。

就算是充当加载提醒，那么也是在 `then()` 中取消加载提醒，并发送对应的请求结果提醒。

**Comment by qmhc** [comment]
OK，那先暂时关闭这个issue。
