### ISSUE TITLE
Notice with Composition API

### ISSUE THREAD

**Issue by semivori** [vexip-ui/vexip-ui#217]
### Description

How to programmatically show notice in Composition API component? Something like this https://i.imgur.com/pkqRdCQ.png

### Validations

- [X] Ensure this issue neither a bug report nor a feature proposal.
- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that descript the same thing to avoid creating a duplicate.

**Comment by qmhc** [comment]
It [this](https://playground.vexipui.com/#eNqVVdtu4zYQ/RVWebAMWLJboC9aJ912W6AFesMmjwICWhrL3FCkQFJ2gsD/3kNSlpXEW2SBGCFn5hzO5ZB6TkTbaeOylnf5F6tVUiTPpWKsHBy2TAoWLN62p0fRZb3wxjLZOdfZYrnsJH9qjO5VnYeAXuSVbpenYPCWyeJE8fFkXopKq0D/bqYsQL7G1zshv5EvQF7y7XvKgHBk3kc1hr+heS8+N71yoqWcbJttjD7YC2RLGPdkMkOqJvPO5F5h3hzg+Y+lOiaLpOVC5c5i/HHu7JlVhrijn7uOHdnW6JbNkMesVGOAUNZxKc/uoa3nGA+OvnyJdf6C4G5HLd0ehKt2Y9DENgSXygMVb4lds9ln6mQweiE4xsF/zQ5C1fqQ399je38Pw5h5it/ch8ODjqitaPJeHQzv/lBfqHJUf6YtAM5gXNMgMkab37mqJRn4cfYN80dqiTF5X0ojb28pHVoRbIoO7F/UI2BPDQGzpwUz5A+ce6JwnWIBUqgH8Ne66ltSLo+Z/ybRBeXSmXfPQMpCYG5I+iZY9yTJ7ogcWjG4diYUghYGb15Ze3ZqJTWv4R6ymThCMcHj0/OOMZeNrp9yFAj1fNoJWacegmSO89ztSKVpKCY2DRNVIePJAGeL6YjneQt9IuIKiNkcPFDdoAmobu2ohYod3fgc1rXYhwWWv/TOacXcU0fXZWL7qiIL7bKPlRTVA0waGZbJEM7YP34bocuIjZTLyBnW32UZchOW4Q+1sJqbB7+AyJwRTYOhZ1mETUq4WU/1Cfd6OckaW1sZ0TlmyfUdLONF+Vs7UdGle4Lbrba9qpxAib4QNDXII0Lyodz0mTnhJBVsNnDd+S06DBk5NB6OW43shy1zmqkQOGNHPzKfa8wOeaHxr+7ZxQGwoCQ0uON1LVRTsB9W3SNbfRibvbYdV2NYy00jVIb+7ZDP94j1kXe6aSSxX9HhAjkAcAIPV3+ftbomWey57D2NsD4WA64ktxaGMJfMhmiYC9+m8CWA7y+tMXtWVFJbOhlve6+H9XKc03n6/zcxJrlq/HlQ13R6uFkLduA+1688hDhwwXwqY8Crr9zkyTJau0/STi/9aTFc+zwU/qewuI4RE1sSbuk23XJp4+MjtiyNrjw0b5DOcEKOqaUzr2z/gkABpQpFDJAFC5jxPYq7ny6hWTFaDbV6TxNa/CbK8h31asDSvx6nl05qU+AAk2bZ/rHLBpHiPxzZhqOcDz5ww6uH+BWLrilm07wJd4YrK/zNmQaerREw94VecJ4P82yhPf5ZG5UWc99og08n1Azh4+kU9TSl4HuVViDauVbm4U25QBnB0XIuy4u6YFfPptnw9Gq7heRW+erH+TGU+gJjRaO4HKFArVa4lK/DvPDe9vFl7y1hj0SfYkdfHrPj+KpmW4jTFqxXuCOxPsx7mHFy/A86I5O/) you want?

**Comment by semivori** [comment]
> It [this](https://playground.vexipui.com/#eNqVVdtu4zYQ/RVWebAMWLJboC9aJ912W6AFesMmjwICWhrL3FCkQFJ2gsD/3kNSlpXEW2SBGCFn5hzO5ZB6TkTbaeOylnf5F6tVUiTPpWKsHBy2TAoWLN62p0fRZb3wxjLZOdfZYrnsJH9qjO5VnYeAXuSVbpenYPCWyeJE8fFkXopKq0D/bqYsQL7G1zshv5EvQF7y7XvKgHBk3kc1hr+heS8+N71yoqWcbJttjD7YC2RLGPdkMkOqJvPO5F5h3hzg+Y+lOiaLpOVC5c5i/HHu7JlVhrijn7uOHdnW6JbNkMesVGOAUNZxKc/uoa3nGA+OvnyJdf6C4G5HLd0ehKt2Y9DENgSXygMVb4lds9ln6mQweiE4xsF/zQ5C1fqQ399je38Pw5h5it/ch8ODjqitaPJeHQzv/lBfqHJUf6YtAM5gXNMgMkab37mqJRn4cfYN80dqiTF5X0ojb28pHVoRbIoO7F/UI2BPDQGzpwUz5A+ce6JwnWIBUqgH8Ne66ltSLo+Z/ybRBeXSmXfPQMpCYG5I+iZY9yTJ7ogcWjG4diYUghYGb15Ze3ZqJTWv4R6ymThCMcHj0/OOMZeNrp9yFAj1fNoJWacegmSO89ztSKVpKCY2DRNVIePJAGeL6YjneQt9IuIKiNkcPFDdoAmobu2ohYod3fgc1rXYhwWWv/TOacXcU0fXZWL7qiIL7bKPlRTVA0waGZbJEM7YP34bocuIjZTLyBnW32UZchOW4Q+1sJqbB7+AyJwRTYOhZ1mETUq4WU/1Cfd6OckaW1sZ0TlmyfUdLONF+Vs7UdGle4Lbrba9qpxAib4QNDXII0Lyodz0mTnhJBVsNnDd+S06DBk5NB6OW43shy1zmqkQOGNHPzKfa8wOeaHxr+7ZxQGwoCQ0uON1LVRTsB9W3SNbfRibvbYdV2NYy00jVIb+7ZDP94j1kXe6aSSxX9HhAjkAcAIPV3+ftbomWey57D2NsD4WA64ktxaGMJfMhmiYC9+m8CWA7y+tMXtWVFJbOhlve6+H9XKc03n6/zcxJrlq/HlQ13R6uFkLduA+1688hDhwwXwqY8Crr9zkyTJau0/STi/9aTFc+zwU/qewuI4RE1sSbuk23XJp4+MjtiyNrjw0b5DOcEKOqaUzr2z/gkABpQpFDJAFC5jxPYq7ny6hWTFaDbV6TxNa/CbK8h31asDSvx6nl05qU+AAk2bZ/rHLBpHiPxzZhqOcDz5ww6uH+BWLrilm07wJd4YrK/zNmQaerREw94VecJ4P82yhPf5ZG5UWc99og08n1Azh4+kU9TSl4HuVViDauVbm4U25QBnB0XIuy4u6YFfPptnw9Gq7heRW+erH+TGU+gJjRaO4HKFArVa4lK/DvPDe9vFl7y1hj0SfYkdfHrPj+KpmW4jTFqxXuCOxPsx7mHFy/A86I5O/) you want?

yes, thx
