### ISSUE TITLE
Try set dark theme

### ISSUE THREAD

**Issue by zlodey509** [vexip-ui/vexip-ui#241]
### Describe the bug

I want to set dark theme vexip-ui in my project, but idk how
I imported 'vexip-ui/themes/dark/index.css' in main.js but theme also default :( 
pls help config

### Reproduction

https://www.vexipui.com/en-US/guides/style

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
You need to add a class named `dark` into `<html>`.
