### ISSUE TITLE
Event for theme change

### ISSUE THREAD

**Issue by zlodey509** [vexip-ui/vexip-ui#242]
### Description

How can I catch theme mode change event in layout in header-user dropdown?

### Validations

- [X] Ensure this issue neither a bug report nor a feature proposal.
- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that descript the same thing to avoid creating a duplicate.

**Comment by zlodey509** [comment]
How can i get this improvement?

**Comment by qmhc** [comment]
You can get it in `v2.1.0`.
