### ISSUE TITLE
Cant set local photo as layout logo 

### ISSUE THREAD

**Issue by zlodey509** [vexip-ui/vexip-ui#243]
### Describe the bug

I try set local photo as layout logo but it dont see this, am I can set not only photos from net?

### Reproduction

.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
You need to show your usage for this, then I can analyze it.

**Comment by zlodey509** [comment]
I have logo.png in \resources\assets\img\logo.png in my project and I try set it as logo in layout in \resources\assets\js\components\Layout.vue 
![image](https://user-images.githubusercontent.com/76591663/215332872-67107f17-a665-4bf8-be67-a6607c4cddf9.png)

then I open dev mode in Chrome and see logo has correct path but idk why it not showed
![image](https://user-images.githubusercontent.com/76591663/215332914-7d98e879-db06-4ebc-8f57-b17adaf9c235.png)

**Comment by qmhc** [comment]
You need to transfer it to the pubic dir, or you need to use `import` like the following so that vite can resolve the path:

```vue
<script setup>
import Logo from '...'
</script>

<template>
  <Layout :logo="Logo"></Layout>
</tamplate>
```
