### ISSUE TITLE
Set theme value in layout theme switcher

### ISSUE THREAD

**Issue by zlodey509** [vexip-ui/vexip-ui#245]
### Describe the bug

I need layout prop that can set value for theme switcher in layout cuz default value is light
![image](https://user-images.githubusercontent.com/76591663/216602596-705932ef-1a89-4daa-a21e-61fc8baf3d1f.png)

### Reproduction

.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
The default value of inner them switch in layout header is follow whether a classname named `dark` is in `<html>` element.

So why you need to set it manually?

**Comment by zlodey509** [comment]
I get user settings by API then doing this code: 
![image](https://user-images.githubusercontent.com/76591663/216781214-29e7faee-7210-4b42-8f9e-9962843bb3a8.png)

If settings.theme is 'dark' I add class 'dark' to <html> but switcher dont change
