### ISSUE TITLE
menu with using Vue-router bug

### ISSUE THREAD

**Issue by zlodey509** [vexip-ui/vexip-ui#246]
### Describe the bug

I using vue-router menu and notice that menu item not active if I dont click him
![image](https://user-images.githubusercontent.com/76591663/216603364-c9b2a050-86f5-4a85-950c-60b07da59dbb.png)
![image](https://user-images.githubusercontent.com/76591663/216603442-138a5caa-2156-4aca-be48-11d1d89a8b3b.png)
You can see that I on the same route but menu item got active only when I clicked him, pls fix this 

### Reproduction

.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Could you show your code of the router config and usage?

**Comment by zlodey509** [comment]
I set custom router data like this cuz I need to conside permissions
![image](https://user-images.githubusercontent.com/76591663/216781004-60c4d471-3f2a-4b29-8ce7-e9f9eea86c89.png)

That how I get data from function
![image](https://user-images.githubusercontent.com/76591663/216781088-ee6edb7e-cb12-4a8c-b54f-6dc4469eae4a.png)

And my props 
![image](https://user-images.githubusercontent.com/76591663/216781110-7ee9cbbe-6b20-4b3e-96a8-514b6a273270.png)
