### ISSUE TITLE
[Menu] Improve group visible item style

### ISSUE THREAD

**Issue by zlodey509** [vexip-ui/vexip-ui#248]
### Describe the bug

When I go to children menu item route and go to another usual menu item, active dont unset from menu item that has children route
![image](https://user-images.githubusercontent.com/76591663/216782629-04838243-6f6b-4cfe-bbd9-2247b755b00c.png)
![image](https://user-images.githubusercontent.com/76591663/216782682-8dcf2f13-095f-4d7c-8089-c9e16bff55ae.png)

Im on dasboard (first menu item) but "settings" menu item is actvie too
 

### Reproduction

.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
They are two difference state for menu item: `selected` and `(group) visible`. You can customize them via css variables.

You can play [this demo](https://playground.vexipui.com/#eNqdVsuO2zYU/RVCKWIZsOR2km4UezBNEKBZBA2SdjUaOBrp2mJGIlWS8gOOd0XRTdFuuusv9Av6PYP2M3r5sB6ubUxiGLZ4H+c+eHmorfdNVYXLGrzImygoqyJRcBkzQiavgdUk4pWinMlp7Lmn2CNSbQpASZmsgxXNVB6Ri6dfVutnqLuSUECqUJsnLCvgnVnG3uVkrAERejLuxMGlTAWtFJGg6ooUCVugr8IwqKVlxYUiW5KTHZkLXpIBpjroKF6lnLU6WNMqqGnX4CVbQsErkM/r4m5EXlC1wd88EeoNhRH5QYIYkdeJuAPR4FztgcYU4SXCNYBqUwGi6lK+s/04Fj1m2k8R17Koa399Q6bkWnd4q38IlnwLRUQG97/8/M/fP5GvBiMrXwheVxFRogYnSXNaZAJYZP31x2F0cRoA/WFJCSj797c/73/9o8XWH11bdNCfVnsklonXhgkQbY9//9fvTQiy68D0PS6OeVyc83hyzOMJerQON/vHFuVIVzD0qa70VLYrZkxaYUZlcltAZnfjQfEw8VPxeioXzw1kA20fTGk2zPFhaVL/3GF5+v80/SGZXjbJ9gxsstYg9/XZG+FuWak+SWQ3fFBzvj7dnJ7KItvTebQ1McP/mM1rlurDRbqc47toUgnKFkObhz6XvICQsjm3BpgxwkzGloYcJWmCMywYLtdVUOLpDZaJkPtagqARG4wg5QUXQc6XICLcCwD27KzlkkqKAxURAdl5S0unevTSTWJRbbouRW/kWWqS4QfJGdK4yTHeS2MvIlv0wG9jGpRJdcba5hN7SLV6jUyuVCWj8bhm1d0iTHk5RtWVZnCpxng2lF6HomaKlhCCLINbwVc4Dxgk9tx+GrwxCrFHAc5lBgI39QT+1RHbXsAD3ZmgjpVPVuL0/XKcMCyPYtnmh6k0/XowasergTy4ak73o2fWg6XYgvVBpq19rWjxAFhjdgrWDd0OB6hMKMMG4+A0N2wqAN3wNWJ06ppGnROHY/e60Sq/z6GEdyuq0rwx6sj6xkg2eK8mRXHu1n0LVYF3rJljRy5aZInFvGYgg7kpF7gUrKG0QUaXeONc5z7mOcSC/E4qwxvDbvYw7YOVHMceo1mEhmMUSbBoFK+wj3wVzma4ns1Q0rTL10kNw1qC74oaIr4GQFPcHjani7BmK5FUr9gHQwJvYY4I+zuoYwZCcPGtIT+BFqBz2VOd0flgctcuJmN/8AifB5b8YsZgRd5gPykm4wtAvyW+HAnQYQ8LoxlGGMxmpvMzM9SzGbZ/r+eFNsh4WiOZqfDHGsTGMjKm8f7RF1ua7d6bbKx9LkxVg089RWbH8Y6YE1+HfPxYRw4t2nRqYDvbbEry3fVkd91tZptJQdkdZqLRPn5sK7A79rLAQdCN01a6cdpPP4enG2LUAvQ0Doxc5gCqVbnS9V8Hj7OCJxrTZd1RmL00Gr0z1qfJM4ckw4sNKVA9hzkX4Guv0YHBnAqpXuiXA735w1DlwHwzE7j2dv8Bc9MBQg==) in playground.

**Comment by sgodf** [comment]
Whether different states should correspond to different styles by default. (my option

**Comment by qmhc** [comment]
The `selected` state which is different from `visible` has both color and background color.

Maybe this will lead a misunderstanding, I think we can improve it that only activate the `visisble` style when with any child selected.
