### ISSUE TITLE
Using tableColumn head slot

### ISSUE THREAD

**Issue by zlodey509** [vexip-ui/vexip-ui#249]
### Description

How can I have to use tableColumn `head` slot that it works? 
I try make it like screen below but it dont works
![image](https://user-images.githubusercontent.com/76591663/216821528-eeb54820-2498-41d6-9b32-57c5221a69bf.png)

### Validations

- [X] Ensure this issue neither a bug report nor a feature proposal.
- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that descript the same thing to avoid creating a duplicate.

**Comment by qmhc** [comment]
It works in playground, please check [this demo](https://playground.vexipui.com/#eNqVV2tv2zYU/SuEOtQyEMtJWruB5xTOshbrsBeaDvtQFSojXVusJUqjqLhZ6v++Q+phybWLtChg8dzXufeSl8yDc5Xn3l1JzsyZa0rzhGt66UvG5u/4bUJsFmZJmcri0nfqL99hs4hrDsT8mOVGRDrG+uz09NR3rHnj4NoaMclTgsJroQrN/sACZiIareke6NKgNTjLVEQK4M4RXDXM2JOYeNTivp7HZ+3K/LsuC52lzGjt4Pm4ozUf99Lccx/RkpeJRvwHprIN23ZYQPFNmElW6PvEJJNytRJypMQq1jN2kX/+sacM9b8LUi/nY/vTpWPcdIAHG8try8C226Ns5+NOWQ9UujGsC/5rdus7DdYW/FMXnfEwpKLITNEhuKpXHYWmJc8aDDl9F4urFVr7FQveRdsg5x1MkQRo4eqz4+gAhxrBd69sWBahErlmBekyZwmXK3jU2MmQijTPlGZoAS1PWMy2bKmwgwY4E4OO1PSwlS3u6LPIR6UYC3SygJ4vzYdm9Rlhl8ad+96weqj4mlLM2OA3Xh+AwUmFoxaAE8Bd1FZjxs7MCpvhw7AJYI7cAe8igpOzxhptxPKaF7Eg1YCUcpEAvpIrSsS/JQX/8KSIz8+nFwu94SF5mVo1yu1e7Bo0woYsZNZFg6OhgCYXqAdYW7BL77xP70Zn4fpWZesDFEmJIvhZ8TVNLqYvFiuDe2GWHqRnlA9Qs+Z9as9Pj1B71qf2Ow9jIYn9mZPiOvuK36tEFPyWdBy8zVakiheT6XRRxHR/tIatxQGilY+9Ik6PMH3eZ3pVRiJLspUo9D7Jm5irTAbvuJSkJheTyUKKcC34sTpW+gf4VR4e2eTJo/bgqztBwWuuUlLT6eR0oe9zkSTerfjvYPGgfYBXZd/ndV7XrToyvlyWMtQCQ7sz2VwM2xmOtGVYaCXkim2HVRYKE0JJO47NkJRw1HEScxklhCF0naCUbm1jDmaWkCfkMnMHoRFRNED4vnE7wdz6ajEcaiqWfENln0zsVhkOipy3/alrjuioSIHM0/sRvDRiTBBpSc72SFfiqm+MvR9UZTuxGeP7g8Er6vNxNTUxI50TpxqEhfepyCTeCja836C+gyRggv+t6ijl+Te0q/i+gzFr1r4Ta50Xs/G4lPl6ZfboGKKFGeGFHkfY32btqVJqkZJHRTrC7NhgKiOI79T5WH9jgHekRs3tccz/4oBuL+Ce7BtB6+vgaCa1vJ9ODXrpQV9j+8zwwsLW69FeO1aty73r6ng9emo9twIl+LzHdKdfapE8wq1VO+a2PrZbbCAMCYkCY+O012+oCGZ4qx69oiGrYW9cv2l3wncxpXSzETqMW6UO1ld+YAI3LU+SXaA6g85F/5byBPew3cf11W6g6vzZd0YzHtpzDODyJU7zIBJ3OHHvYxc8h0jI7VAZmrlVVWIXLM2w7RGt8tAOHc04kga8QR1xfoMA6yAA0pbLNaSGXlmQWyc1tHMR8xI1gpOlWHml3Ciev5GfKNQUvaUlPGiFg9lXI6Uy9YudJgoaZLg0s8/KXLLcjYll7A6e4LudhJI27C/UU4CMqwh2d4TBQybsfmIiQoRBENjKB3ZTB4Ed7ZU8S4xClIVlSlJ7eJyo+xtK4Ak0Pj754UFE24+WTaUf48FkPH7vKbIdx9W2ZK4J+fSpiexV3i4vrdtOm21Krg3bdL1u5o5JIuQaTIy3L192GVQde5VgI5jCGS1TOGNnvr3jBbFiRWY3DiyOhwjpnahO3fx0/GUyybjxWbPuCGwvrcR0prJpeZq/rHDTYQTqn2iZKXKN1cmegr29r2ORRKb5Q0/HJF27J7B2tv8Df3m1Aw==).

**Comment by zlodey509** [comment]
so strange, now it works...
