### ISSUE TITLE
[Select] Should filter by label by default

### ISSUE THREAD

**Issue by zlodey509** [vexip-ui/vexip-ui#265]
### Describe the bug

I try use filter in `select` but it not works
![image](https://user-images.githubusercontent.com/76591663/218833619-44666dd7-8888-4874-b6c6-de41abd2760f.png)
![image](https://user-images.githubusercontent.com/76591663/218833495-32a78fa8-6907-4d8a-a791-43038bd1a7d4.png)
![image](https://user-images.githubusercontent.com/76591663/218833540-deaf0f3a-dac8-4696-b071-d464d6e8a734.png)

### Reproduction

in docs same problem

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zlodey509** [comment]
Update: filter in select filtering by value, not label I think that incorrect

**Comment by qmhc** [comment]
Currently you can pass a custom function like the following to `filter` prop as a workaround:

```ts
import type { SelectFilter } from 'vexip-ui'

const filterByLabel: SelectFilter = (filterValue, option) => option.label.includes(filterValue)
```
