### ISSUE TITLE
[Table] Support custom sort

### ISSUE THREAD

**Issue by zlodey509** [vexip-ui/vexip-ui#266]
### Description

I need disable native sorter colums cuz when sorter arrows is clicked I send request for getting sorting data but vexip-ui sort it too

### Validations

- [X] Ensure this issue neither a bug report nor a feature proposal.
- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that descript the same thing to avoid creating a duplicate.

**Comment by qmhc** [comment]
Fixed by bb0f4af.
