### ISSUE TITLE
[Table] Set expanded data feature in table rows as accordion

### ISSUE THREAD

**Issue by zlodey509** [vexip-ui/vexip-ui#270]
### Description

I need expand only one row in table how can I get it?

### Validations

- [X] Ensure this issue neither a bug report nor a feature proposal.
- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that descript the same thing to avoid creating a duplicate.

**Comment by qmhc** [comment]
Now you can get it in v2.1.4, [playground demo](https://playground.vexipui.com/#eNqlV+tu2zYUfhXCHWoZi+U0rd3ASApnWbILdkNTYD/qQaGlY4u1RGkUZSdz/e77SF0suU7ndkVRi4fn8p07u+lcpam7yqkz7lxoitOIa3ozlYxdvOOziNg44JpfTjvmZ9ph47UIdIjz+ekpjhOVrPv0kHIZgBbiJ6Ibe5x2rJZKz3US5bFk+jElMBYSkBdBf0mPTcpcPFBQikK4gsSeBTTneaTBu2GwesIimutbw33ClFiExTfb1oat/A9KBLsjY+NMP0YGwqZJZSzlQSDkYszuz07TB/bNpqHyW/bidAtieVPbrS7uT9q6ZtxfLlSSywBeJ2rMuiuunH5/tuj7htDrNvkBeHdsQAf4a4qiXcRfnLVcM39uczD8xmMas82G3QN1snbnQmXaELfGDRAiXp7v2XbbMjAwFv7TJrtaFAaMMr4gaDla9OdkVot+SGZfInoTcxHVwmROB8UvBibJu5IZtMrYEBoVeKgoJWIDq7cmbjaazcKso1nX5rH6fkHYP1FX5aLZSi9NKx2tFhFtKkRQv14XEtvUhdweo6uk4LsVaxwzX4lUs4x0nrKIywW06MyWrYjTRGmGZBL3tVihithcJTGaIyc0xFT6iUTAzJxhlzWX895YLJtVBOilF92y3eA5jtc8CwWpimjLBOQruaBI/J2T9yePsvDsbHQ+0Wvuk5uoRcVc57YpUF1WmcKdVVHRESSQhue2ibeW2IR31oZ3pxN/OVPJ8gBEUiLzvld8ScPz0evJwtBdP4kPwjPMB6BZ8Ta0V6e1JTtUCbC0yukw3pdtvL9yPxSS2O8pKa6TT0DfRCLjM9Kh9zZZkMpeD0ejSRbS45OBrSUOoC907EV29ERkX7WRXuWBwDRdiEzvg7wLuUqk945LSWp4PhxOpPCXgj8V3IL/AL5Cw5GZHx5VmDcrQd4tVzGp0Wh4OsFGFFHkzsQ/B4MH7gO4Cvk2rrMyblP5V8+00zyX6KBEsuZWdsrdWVUG2/YKH0zzJRG5CKhTXUINXJuzHaHyd54o5hT9KjABWDK3fVvfQwxkt7ZyWZwFvi7R2xjn1Va2+wj/4O/FoBgfGBadk04xLzL3Q5ZIvE2s4mlFnXawFwqpmrUf8/Qz3IW5aQfTxpzxWNE6zcaDwRxhjR4hGaD/V8qVpAcyjQdgnJjJlulBgBozZ1flUouYXMriPpp6nZGC4LRTJsJqH4C4ItVXBNcVqeOsTQ5Itszv3X0GAj2ItJ+LI70suduulkQ3Pqh5YN9Qrp/ZyH6ljYaO2sCktiBMcR0buZZQy4hAsB72vNjx51pEX2zECj1lpCpmFCXaXUIPirHefD6Wmia8t09YuLf9Sh7clWR3UL7Ld5fvQorpbi20H9ZMDVqbecMEupPjVVUbKj1o7Nq3lEboTdsb5kVgJjJIxVyxS9ypW1rhqCQD4fINC51uIFbdE/Y+dICzB4ecBpSemUBVW1fGYjyINawVGuqhoxmH0yCvEUcMBs/D2fNAqcPlGFA9N8/IKZ3q2QmHyYcYQclcLNxcrhVPf5IfyNcUvKU5NFRbr8FGSiXqRzsRFTjIYKlmn71zyGI3Ihax032G7y6I1hdJa/YH4ikAxlEEuRXh/x9kzO47ZsYd63qejbxnC97z7JAu7pPIMASJn8cktYu3h3q8owiaAOP+2TcbEWzvLZqCP1TWq+7/6zeb/2KuGwDPnxscbqEbw9l8NJJuHXQsiKoGytTucEVCLoHLaPv4cedPkb+bCGVhwmi4TBiNnPm22+BweOy1IlObXUvHA4P07qoMhPlp6EtklHCjs0TduLCZtTcmT4VMjTMkHrgoLFL6O8JmI8dInewx2K18HYrIrMVtz9UhScdWCM6d7b/yXv1A).
