### ISSUE TITLE
[Select] Support custom filter in select

### ISSUE THREAD

**Issue by zlodey509** [vexip-ui/vexip-ui#272]
### Description

I filter data in select by API across different fields and I need to disable default filter by label 

### Suggested solution

/

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that request the same feature to avoid creating a duplicate.

**Comment by qmhc** [comment]
You should view the `filter` prop description of Select component. You can pass a filter funtion via it.

**Comment by zlodey509** [comment]
could you send an example pls?

**Comment by qmhc** [comment]
Is this you need: [palyground](https://playground.vexipui.com/#eNqlVW1v2zYQ/isHdahkzKbaYZ+0OEg3bNi+bEM77Ms0KIp1ithRlEZRfoHr/747krZsow2yFggS8e6ee3l4fLKP3vS9WI8YZdGNxbZXpcXbXAPcvEOFKwtZLZVFs8yjWlqFJo8g63orOz2QLXzl0e1N6gEEvknPMtFxWBnZWxjQjj2oUj8S0DIm17LtO2NhD7b7dWwf0MABatO1EN+tcSv7xSjT0Uo1xJwpRNtdjwTx9X5y7Z1gR5SLX1FrFkKPsIQ3xpQ7wYHJHhTqR9tk8PobOMwhKeYgZ7C8hWTP46vyAVUG9785MHy1l/A1vD7cz9m5LtWIGThTrg+z2VTMk5RdNreExLP4JwPnoSNXzRUzxIzRwSxcdrg9UXKOpUoHJthTGui1O4UwrLoeK7KI9bZfDP7yXPa23C42suJZv331qt9+d8zBOAJE88gTO4j3Q6dpExwsP1rzKIM9IejnFLpoy/6JaLawjRaLz3nUWNsPWZrW5WDVjpAVKrk2QqNNdd+mFHjHCzPYtJL0i87CjNrKFgUO7eLBdJsBDQHzyF1ByJ6ScY1mYVBXaHg7n1Pt7iPIi/JXvidaCOv2zClD9OWowSjaj2b21yRWg2P2M2uc5TgVmB6Y5NV9LnMXoIsiksjaXk1x9Yr/bxEH+lQRrsFrSUvZllJTHlrGk6CsDBKM1G0OzaQOI5IwhBjyBbNIgwpOzj8abPHdRtpVcwo6s10G70HS2y+VekqG3mKvSAnc29BlS/oRsyl2XDltTGbHlxMEgQwkEU0SV3Idz+GvJqE+ZzRQctbK7G8SBc/EVKzt6PGw7kwi4x0lDU3mDfHYbURR0LkoyHKiK+GmZmIcMAlDeXkDhgpKUstHMeqNKftf9HsSGazeYk0ZrKHHfhmGxnTm51JXJIkUgdwLt9HRMjpfwoLmIa7jJH5B37FXuVxr3MDvxKekZhKDhFuTehrksteDyYoqxEXhmC/cwhcF0X/0d4oDqm41tqit+HdEs/MiTW3cvyCBrw73rhsf3xg3Vfxl783dP4CsIeEGXr7kPoTPvVy6ImeX7gZMXBPHHQhXO/WlpP6H+uJsHz5M8/j7+1HRWjCNHMU0un9l9C0+TY9zG+TdjJ19aBDt5ApE8J+zfJ1WXck5Q9dnDnezzsP35DGnPhssK0GLhcZ+j3VnMGHU/CqglmawPzRSVbwKM2Eb1InbEDpHh/8A4z4Lpg==)
