### ISSUE TITLE
[Table] horizontal scroll for overflow content

### ISSUE THREAD

**Issue by zlodey509** [vexip-ui/vexip-ui#273]
### Describe the bug

I set the table min-width and when window width less than table width overflow content is not visible 
![image](https://user-images.githubusercontent.com/76591663/221415724-00241af9-59e0-4d0d-9b0a-06b618ee1073.png)

### Reproduction

/

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
You need to show your code, and better to make a reproduction via using [playground](https://playground.vexipui.com/).

**Comment by zlodey509** [comment]
https://playground.vexipui.com/#eNqVVFFP2zAQ/iteNpFUah32WlHENk1jD5MmQNrDMoWQXBuDY2e204JK//vunDRNK4qYhKjtu/vuu+/usg4+1TVfNhBMgzMHVS0zB+eJYuysEEt/wONNdieBWfckYZYElVCTlShcOWUfT09P68ck6BwZ6wJiH9HixC3QWTyAx6vNjagds+CamslMLRDZWQ8lqlobx9bMwJxt2NzoioXIMRyYfmQLJeZPQi2+ycza3u1iCY+injQiFrlWFkMSRQfHKrtgM4KMwkuQUrNf2sjiXTgibi0bzB2MgzaH5fdWK5RlTVUk29ckmLL1JlH417tOqqx+xbvVJAmwAronQelcbadx3Kj6YcFzXcVouiBprEO18B/euWmUExVwsNXkzuiVBYNJkmA8wIvxcQlmYkAVYMAcw794wXcv4YHtlaSdvEcr6ez75XSPvHoRK/aTxXPr9Xoz6iCqhzxo/3E99tz2YAVK8HjAdOffOCHfAOvdjsESKo0QDlCVCYUC4+D0k50bwDBcyzErX55+tHXPPO7Wd2e8KaGC65Vwedk7Dd72nddM4GpkUu4SdRUMFucKaomb4+dYZRVMWUhPoVfH72802k65watRDB9m56yMQtz9cMx+lxHyHGFB0YDK6A+uXqvEYEs1jj1maxE8amvIsGh8XqGOesXTFO9pii+9XBGRGvHGQtQVNUJ8AkBXbI+aiwVv1Mpk9Xd1D7mD4gq/LzPmDC7mvhsYo81lpgoJBj2AuBANjQPnbRF47hTiGUfhezzTt8TXomDFfqKeAslEBjBuCWMUh9IeFiYKzBCmqVc+9UOdpij/1q4lORQ6bypQjv9twDxdg0QkpHH7/sNaFJtbz6b1L+mriYj/u0W+44yJOYso5ckJZeYt2mzmYQdt9iVFPu22610zd0ykUA/IhNCen3cVtB37KnEQSDjyIuEojs78uCDebICmMfTvtgRwO1NXOv0M8LSSOiPMjvXA4HvpLdSZNqbnWUJWcBwlMO4zzLWBiKLGBw5zYaz7UgpZUPNH3JWgIj8TeA82/wCVRIxT

**Comment by qmhc** [comment]
You can view this [sfc](https://playground.vexipui.com/#eNqlVm1v2zYQ/iuEutUy4EhuWruBFxfOshTbsDckAfahGlRaOluMKVKjKLue6/++IyXbkicHXgsEsXm8e+65N543zk2WecsCnJFzrSHNONXwLhCEXMdsab/g10c65UBGMdV0HDjmI3BIrtcc8LhisU5G5FW//+13gVOZ7IxuJS9SQQRNjep7pnJNfsMD2rP4YgFrlM6MtBKOLBoKX/f7CHbt11Cehf6FtiBzFH4t8M9yWod8sscvRruZNwhSezwDrZKVlfHL0lz7tYLhMY8UyzTJQRcZ4VTMEVHntiQszaTSZEMUzMiWzJRMSQer3jGGkRSYO1NVMjYK7gfjZVM6ZvGIdF51euUJo8fjLc0TBmonhJQyjuIbMQfO/i4g/JPyPLm8HF5N9IpG4Ek13ynvi1032F3u6oV3FmInxzShaHCFdAnZWmGd3mWT3oOW0WKq5KKFIiiWhz8ouoDB1fDtZG7kXiTTVnpGuYWaNW9Se9M/Qe11k9qvNEqYAPJ7Bopq+R9+d5zldAo6Ce/lHFT+djAcTvIE1idzuLdoIVpiHCVxeILpmybTmyJmkss5y/UxyYeEKinCRyoEqMHVYDARLFoweiqPpX4LvxLhzCIPzurBuyWD8D1VKajhcNCf6HXGOPem7J/W5KF2C6/SvsnrsspbIP7qmtErhw1Hy+k55XTl3lMuBb6jlnWwkwbOiGzQDP/2qhcpzZ7RLv0GDg6oOQdOonWWj3x/hhz5Gi1jnJul8gRoX2Spj4oT8w7kGp8G/IdnTxVCsxQ8yNMLHIZVDgoNA6eKyqL7KFyCulAgYlCgzvM2abFsuD+6e4YCfGLZRcHOjLLSboZaCb20Fdm3W8qLcpvZL/RRw9g7mOw9MPN+npu5hlHDCcNkfTqK4qBfaMb/txNrdMpJ1c1bbEqcHYE42Iz7PREpQDP8bdAjydHCqHTwrhJ7fvUb4nD5mEAKDyumo2SvVJM1lTeE4QKinB8cVRHU1tM9ZBzXk50Ns0vN84aickjtynO7u8lReFSCoGD8jiRuB9dlp0c+JC7y7GJAbo1K14xzmYmDs1Ti8KC3EsGilhcUg0bxCvMoV14Y4jkMUbJPl2tIdb0iB7cKqov4BgBV8YEUMzb3CrFSNPtJPEGkIb7HlTwmWuGwN9VAKal+pCLmoFADDBdDQ2Iz2jsXLHdjYhm7nRf4vYNCG4uAFfkD88mQjKsA7ZbQw+QYt8eBsRg9dMLQZj60DR+G9sUr7yU3CrGMihSE9nBnq/UDcERCGh9ffLNh8fajZVPqJ+aHBiJ+3bzZ+uP7PyOuIfDypeHhldjjsXVSK7oN0LUkdj1QlfbAizOxQF4G7fPnQzxl/e44toVJo9EyaTR25rt3Oj32WoHpzY6V47YGfbiqEmE+anhScEkNZsW6dmEra29MnUqbPc8EaOxhY4HS38NMKnCNVe9Iwa6424Tx2LRC19MJCNd2CJ6d7b81gval).
