### ISSUE TITLE
[Select] on removing item from multple select bug

### ISSUE THREAD

**Issue by zlodey509** [vexip-ui/vexip-ui#275]
### Describe the bug

idk why but when I try remove from multiple select items (except last) page is refreshing
I get options by API and `roles_ids` value too
![image](https://user-images.githubusercontent.com/76591663/221655337-81297418-b9ce-4d16-8e48-6e3f753cfed3.png)

![image](https://user-images.githubusercontent.com/76591663/221655521-b33533b9-dd19-41ff-83c7-d2132c4c8fb4.png)

In playground I tried it but there it works correctly

### Reproduction

.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Would watch the `role_ids` somewhere and refresh the router?

**Comment by zlodey509** [comment]
No, I just send it to server on form submit

**Comment by zlodey509** [comment]
It works!

**Comment by qmhc** [comment]
What are the steps to reproduce refreshing page?

**Comment by zlodey509** [comment]
Just click on x-mark first of selected option, it refrshed page
