### ISSUE TITLE
[Table] Strange bug with Table in Tabs

### ISSUE THREAD

**Issue by zlodey509** [vexip-ui/vexip-ui#276]
### Describe the bug

I set tabs and I clicked on tab with table I get data by API but table has strange view: 
![image](https://user-images.githubusercontent.com/76591663/221686468-ac9fe902-96ff-43c6-ad7f-2a2efc707d68.png)
TabPanel in code: 
![image](https://user-images.githubusercontent.com/76591663/221686680-701f53ef-644d-4dbf-98c9-c0ded7794eb3.png)
![image](https://user-images.githubusercontent.com/76591663/221686770-ce20ed2d-7441-4c20-ab3b-276a8c62bb25.png)
I notice that if open/close chrome devtools the table become normal

### Reproduction

/

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
You can try using `refresh` method of tanble instance after tab switched.

**Comment by qmhc** [comment]
TabPanal have no `show` event, you should view the [docs of Tabs](https://www.vexipui.com/en-US/components/tabs#tabs-events).

**Comment by zlodey509** [comment]
I dont understnad when I need refresh table, on which event? Could you pls send example demo

**Comment by zlodey509** [comment]
thx finally it works
