### ISSUE TITLE
[Table] Visual bug after 2.1.5

### ISSUE THREAD

**Issue by zlodey509** [vexip-ui/vexip-ui#278]
### Describe the bug

after adding scroll in Table in 2.1.5 version tables had scroll or short view:
![image](https://user-images.githubusercontent.com/76591663/221940400-d8dbe011-1816-4149-bedb-b1b697ccc28d.png)
![image](https://user-images.githubusercontent.com/76591663/221940500-bf4f1aa4-116f-4cba-9538-254c6f39d814.png)

### Reproduction

/

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
I don't quite understand the issue you describe...

**Comment by zlodey509** [comment]
I try to explain that after 2.1.5v tables in my project that were in normal full-width view now forever with x-scroll or reduced in screens I send

**Comment by qmhc** [comment]
Maybe you can create a reproduction in playground and show me the reproduce steps. 😂

**Comment by qmhc** [comment]
Are you mean: set total columns width small than the table width, and the table body doesn't fill the entire table?

**Comment by zlodey509** [comment]
I mean that more part of tables after 2.1.5v has x-scroll and another part of tables is reduced I set demo below (but idk how to reproduce reduced table maybe it depend on `TableColumn`s amount

https://playground.vexipui.com/#eNqVVm1v2zYQ/iuEOtQy4EhdVruBERfOshTdsDckAfahGlRaOluMKVIjqbiZ6/++I0XbkmsHGWBA5r0899zxyOM6uKqq6LGGYBxcGigrTg28TwQhl/d0xoGMM8nrUuhJEvh/SUDGOTUUJfaTBO8vY2eLbpdxCwOXOlOsMkSDqSvCqVigk0EE1LKyksqQNVEwJxsyV7IkPSTSS0Qck4/AK1BkXovMMCk0yaggMyC1hpwYSZiYo9o8VUByyGtn1MLMYc4EXDeE9+jwhVVnNcMQicgQ1RCfE5lYGqHNu+MafrIiQtbNhxBBSxiT3gem0Pl3XPQGW9USnlAztxqnaOQbrz9E+JWeAOCoeIH/L3J26PnQFtEsA62lCpVc9ffeBPM0tRIExRE6bOWb56NdLb7hSVHknezn734i8NdU1faFL6kroIdjOfp9vwXC6Li8prpgoLZCKCnjNqBYAGf/1JD+Rbkuzs9HF1OzohlEUi22xrtatx22ym0dUecgtnLkjaLhhSPf5Numd96ld2dktpwpuTxCERTT6U+KLmF4MXo3XVh5lMnyKD1rfISac+9Se/vmBLUfutR+o1mBnUr+wINCjfyG3w1nms7AFOmtXIDS74aj0VQX8HSyhjuPI0QbjIMijk4wfdtlelXnTHK5YNockrwrqJIivadCgBpeDIdTwbIlo6fq2Ngf4dcgvHCThy/qwZtHBukHqkpQo9HwzRRvG8Z5NGP/Hi0eWh/h1fh3eZ37uiXCnprLuLkl3Y0ZDILmEtPRg5YCb2XHO9lKk2BM1uiIv53pWUmrZ6ybyEmAd6tdJ0FhTKXHcVyLarmwhY5RNbWXtjZxjptk15GqhWElRKDLMzwAKw0KgySBz8ThxSh8BHWmQOSgQJ3Cnx6x7QQ80D0T1F/hJzPx+m46XhiVR7FibZ44RJl29XoxastrBzndYTJ7E56uR8esA8uwBF8OmO7ta8P4C2Cd2SlY33sbbCDsdIEFxsbZjc5MAbrhq2BAioO57G1Q58VR7F8Pe+V9ASXcrZjJip1RS9Y1XuMc14Zy/tyIvoWK4zBxfezHkRU1R8q9LMLdgPPDDQWT96QIezl77A3IpyJEnn1MKGxR6dvD11RiH6yU2PYYrUFwqI2CYtIoXmEdcXKmKa7TFCW7coWWVD/CB0rok+ojvgVAU9weMWeLqBYrRaufxQNkBvJbfPlMiFF4MLtmoJRUH6nIOT5yJgQsF0tDYsM5XQiOu3VxjMPeK/zfQ6HLRcCK/In1ZEgmVIB+jzDA4tiwh4mxHCP00tRVPnVNnabufmr0kluDXGZ1CcJEOGHV0x1wREIan199t2b55rNj09gX9j2HiP/3FLkdx/t5TkIb8vVrGzlq0CYTB9vaZpdS6MJud91v5p4JZ2KJTCza16/7DJodu+HYCLZw1soWzvrZ/9Hpgji1AtuNPSfHaQpmr/Kp208LTwouqcX0rFsKt5dOY3em8dnxLIDmEbYSKPMjzKWC0HoNDgzcCLouGM/t5vcjU4AIXU/gOtj8B1f85B0=

**Comment by zlodey509** [comment]
now tables work as tables before 2.1.5v (without scroll om overflow content)
