### ISSUE TITLE
Overflow poppers in Modal

### ISSUE THREAD

**Issue by zlodey509** [vexip-ui/vexip-ui#282]
### Description

Is it possible make poppers in `Modal` are visible, not scrollable?

![image](https://user-images.githubusercontent.com/76591663/224417870-1e103925-4cd1-4155-b356-6bfaf6cae7d5.png)
Its now, I need that options will be visible straightaway

### Validations

- [X] Ensure this issue neither a bug report nor a feature proposal.
- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that descript the same thing to avoid creating a duplicate.

**Comment by qmhc** [comment]
You can using `transfer` prop of components which have any popper, to make the popper render in `<body>` or other you like.

**Comment by zlodey509** [comment]
how render poppers in current modal? cuz using just `transfer` tag without value it render in `body` and popper not visible basically

**Comment by zlodey509** [comment]
My setting modal and select props in pic below but idk why options view not like in your demo (`FormItem` no matter cuz without him I have the same problem)
![image](https://user-images.githubusercontent.com/76591663/224494512-5e588ba4-e5bf-4775-b5e0-03230669068f.png)

**Comment by qmhc** [comment]
Have you change `z-index` for any eleemnt of them?

**Comment by zlodey509** [comment]
I set `.vxp-modal__wrapper` class `overflow: auto` prop cuz without it overflow contnent look like in screen below
![image](https://user-images.githubusercontent.com/76591663/226964434-14596fa7-51ed-4f46-a468-69d7eda668c8.png)

**Comment by qmhc** [comment]
Do you specify a `height` to the modal (or `top` and `bottom`)?

**Comment by zlodey509** [comment]
Yea I set fixed `height,` cuz if I not do it modals are overflow the window like in screen below and I want that modals without fixed `height` will fit in the window
 
![image](https://user-images.githubusercontent.com/76591663/227223823-114e249e-9613-4d3b-8768-7e2d7d11c4f9.png)

**Comment by qmhc** [comment]
Emmmm, I think currently you need manually change the `z-index` of `.vxp-select__popper` for the Select inside the Modal. 😂

I will improve the mechanism of `z-index` for components later.

**Comment by zlodey509** [comment]
`z-index` doesnt work in my way
Ok, I now try to describe current problems with `Modal`: 
1. `Modal` without fixed height with a lot of content is cut off in window like in screen below
![image](https://user-images.githubusercontent.com/76591663/227223823-114e249e-9613-4d3b-8768-7e2d7d11c4f9.png)

2. `Modal` with fixed height with a lot of content that not fit `Modal` is overflow like in screen below (and `Modal` overflow window if fixed `height` < window height like 1st paragraph)
![image](https://user-images.githubusercontent.com/76591663/228245121-4c8bc8c9-8940-4261-846a-793462cc307d.png)

3. `Modal` with `overflow: auto` property and fixed `height` is fix 2nd paragraph but `Poppers` are scrollable like in screen below
![image](https://user-images.githubusercontent.com/76591663/224417870-1e103925-4cd1-4155-b356-6bfaf6cae7d5.png) 

The reslove I need:  `Modal` without fixed `height` has to contain any amount of content and no overflow window screen

**Comment by wjys995** [comment]
You can view this [sfc](https://playground.vexipui.com/#eNqdVm1v2zYQ/iuculUyYEtJ031R7SDrMGD7sHVo+q0qVEY6W2wokqMoO56b/77ji2XZq4O2QGJTd88998qTd9EvSqXrHqI8mhtoFacGrgtByPx1b4wUxGwVLIpIadZSvS0iclNxVt2jiFaGrYEsyA/+VETOkJA3CoSjyDyH5/tT1pR7wHrWyhp47u0GqiLyaqOp6JagwxMz3GLe2e89JN+w2jQo/fniYpA1wFaNQeHVQYiOKJ9VnHYdKmpopfWNgTh9CHj+F7X+bystOSd9B7Pt7I5qMhBeXlz8hKl3DjDrzNZFpGhdM7HKyeVL9fBqSB/5FKa4lBoxgjBBrtA2v4etfR7BCLmVLZBKCgPCDMaZOhDdAofKkFwqw6SwKYQTMu7LdD3PPOys/xdYju8JYJ6NC+PbmLk+4nmejeYFH7E4TBnSgekV4VSs0JnBOFHLWiW1ITuiYUkeyVLLlsQ4dLE1RO+dIcMwISRZUt7BZK8KGaPuffzGncllPCX784vR+Wp0fhl/sEH6sEKItnHYRamgRkm+4vKO8iQ9jAVJ1w/KH8sy1GVCdjbzodsXrwrxaPkGe2vTuRaUpZJKgQ42/86YqOEhJziRwQwjslGg+2ga+cJ06adOCryBzqbYS4soJzu0wL8BOmupegLt21ZEWFv7XESNMarLs6wX6n6VVrLNUHVjm9aZrGb4gc+p7oVhLaTQtbM7LTcdaHRSRNMRX4bCNeiZBsxI4+U8w3/zBeyRwxPdE07hgalZz85mEvTH6QRh2n6Ryxc/rTpXr69mHVkNlDcDJ7Nzer4eR7AjWjccJ5Ee8L1h/CtoHewcrWW1I4QD1FImsMA4OMN1rDSgGb4BpqQ5vpe4ewMKtUGRZuFdMVa/a6CF2w0zVTPARrJT+A7XUWcobtnBXcjDoey/v/RvQXG88TsrIUTQFnISW2E89SK3ZxJ7z8J7QqNAC4KixTVpkrhma9wG75sEo55ggskorMmHiTd7tF/u4+C6lXgd0LdnCvxhS2ExULHBCstNWpb4XJYoGQqZ2BAnKb5CkpDoxHnyJAjH5oklW6W92Giq/hCfcGlA/Rb34gIXOl7bUyBoLfXvVNQcNGJwRV67YCQOpNMluCkHIxd7Ej/Dc+zEQ24CNuRvrDjD0BINaL+GKRbNBvD/RFmNvuKydN0p3fiXpWvRHiG5hdSy6lvckek/Peitfw1hSB+f/bhj9ePHEJm3aOz2R9ZvvXPDZBDCliSxjp8/t/5Tz7hYOOqjUXDpJcH9fjZGLR/HxZm4x7gs7+fPh4x8T3/jODS2pBblS+pt7XP6VJkcQIOd4thpugbAjJWhIPbrhFcKLqnlDpkcqVzXnc727mA5RN4ArVMcP9DmNeDPAEis5fQEsGS6M782jNd+UCapaUAkboKcJHr8Dzc6cpc=) and as a wrokaround currently.

**Comment by qmhc** [comment]
You can view this [sfc](https://playground.vexipui.com/#eNqdVm1v2zYQ/iuculUyYEtJ031R7SDrMGD7sHVo+q0qVEY6W2wokqMoO56b/77ji2XZq4O2QGJTd88998qTd9EvSqXrHqI8mhtoFacGrgtByPx1b4wUxGwVLIpIadZSvS0iclNxVt2jiFaGrYEsyA/+VETOkJA3CoSjyDyH5/tT1pR7wHrWyhp47u0GqiLyaqOp6JagwxMz3GLe2e89JN+w2jQo/fniYpA1wFaNQeHVQYiOKJ9VnHYdKmpopfWNgTh9CHj+F7X+bystOSd9B7Pt7I5qMhBeXlz8hKl3DjDrzNZFpGhdM7HKyeVL9fBqSB/5FKa4lBoxgjBBrtA2v4etfR7BCLmVLZBKCgPCDMaZOhDdAofKkFwqw6SwKYQTMu7LdD3PPOys/xdYju8JYJ6NC+PbmLk+4nmejeYFH7E4TBnSgekV4VSs0JnBOFHLWiW1ITuiYUkeyVLLlsQ4dLE1RO+dIcMwISRZUt7BZK8KGaPuffzGncllPCX784vR+Wp0fhl/sEH6sEKItnHYRamgRkm+4vKO8iQ9jAVJ1w/KH8sy1GVCdjbzodsXrwrxaPkGe2vTuRaUpZJKgQ42/86YqOEhJziRwQwjslGg+2ga+cJ06adOCryBzqbYS4soJzu0wL8BOmupegLt21ZEWFv7XESNMarLs6wX6n6VVrLNUHVjm9aZrGb4gc+p7oVhLaTQtbM7LTcdaHRSRNMRX4bCNeiZBsxI4+U8w3/zBeyRwxPdE07hgalZz85mEvTH6QRh2n6Ryxc/rTpXr69mHVkNlDcDJ7Nzer4eR7AjWjccJ5Ee8L1h/CtoHewcrWW1I4QD1FImsMA4OMN1rDSgGb4BpqQ5vpe4ewMKtUGRZuFdMVa/a6CF2w0zVTPARrJT+A7XUWcobtnBXcjDoey/v/RvQXG88TsrIUTQFnISW2E89SK3ZxJ7z8J7QqNAC4KixTVpkrhma9wG75sEo55ggskorMmHiTd7tF/u4+C6lXgd0LdnCvxhS2ExULHBCstNWpb4XJYoGQqZ2BAnKb5CkpDoxHnyJAjH5oklW6W92Giq/hCfcGlA/Rb34gIXOl7bUyBoLfXvVNQcNGJwRV67YCQOpNMluCkHIxd7Ej/Dc+zEQ24CNuRvrDjD0BINaL+GKRbNBvD/RFmNvuKydN0p3fiXpWvRHiG5hdSy6lvckek/Peitfw1hSB+f/bhj9ePHEJm3aOz2R9ZvvXPDZBDCliSxjp8/t/5Tz7hYOOqjUXDpJcH9fjZGLR/HxZm4x7gs7+fPh4x8T3/jODS2pBblS+pt7XP6VJkcQIOd4thpugbAjJWhIPbrhFcKLqnlDpkcqVzXnc727mA5RN4ArVMcP9DmNeDPAEis5fQEsGS6M782jNd+UCapaUAkboKcJHr8Dzc6cpc=) and as a wrokaround currently.

**Comment by qmhc** [comment]
How about [this](https://playground.vexipui.com/#eNqdVtuO2zYQ/RVWKSIZsCWnu31R7MU2RYH2oU2RzVscKFxpbDFLkSxF+VLH/97hxbLsxou0QBKTM2fOXDnKPvpJqXTdQZRHMwON4tTA3UIQMnvTGSMFMTsF80WkNGuo3i0icl9yVj6hiJaGrYHMyXf+tIicISFvFQhHkXkOz/e7rCj3gPWkkRXw3Nv1VIvIq42mol2CDjdmuMW8t79HSL5hlalR+uN02suMVCjp7+iD8knJaduiuIJGWrcYw5m+NTtH39DtpAa2qk1OXk2n6/q1x4WcZn9QG+JDqSXnpGthsps8Uk1aJ+hZFK0qJlZIcau2yECOiiWHbU5oZyRKAyeyKqzFUmoECMIEuUGL/Al29j6AEfIgGyClFAaE6Y0zdSJ6AA6lIblUhklhEw4nZDzW826WedhV/7dYvP8TwCwblsf3O3MNx/MsGwwWXrFkTBnSgukU4VSs0JnBOFHLGiW1IXuiYUkOZKllQ2KcztgaovfWkH7qEJIsKW9hdFSFjFH3IX7rzuRVPCbH8w+D883gfBt/tEH6sEKItmvYW6mgQkm+4vKR8iQ9DRFJ11vlj0UR6jIie5t5xVrMdpcT2/PXVtJPxRSvB+uhZ7QsrWtKUSipFOjA8veEicrOzM10GswwRhsXBhSNI1+qNv3cSoGP19ksjtJFlJM9WuCfHjppqHoG7Ru5iLDa9r6IamNUm2dZJ9TTKi1lk6Hq3raxNRnmaOw91Z0wrIEU2mbyqOWmBY1OFtF4wJehcA16ogEz0viur/DffwV75vBC94xT2DI16djVTIL+PJ0gTJuvcvnip2Xr6vXNrAOrnvK+52R2cq/X4wx2RuuG4yLSE74zjH8DrYNdo7WsdoRwgBrKBBYYB6d/oKUGNMOPx5jU5y8V13ZAoTYo0ix8Zobq9zU08LBhpqx72EB2Cd/jgmoNxe3buwt5OJT969fAO1Acd8DeSggRtIGcxFYYj73IbZ7EvrPwidEo0IKgaH5H6iSu2Br3w4c6wahHmGAyCGv0ceTNDvbH/XNy3Uh8DujbMwX+sLewGKjYYIXlJi0KvBcFSvpCJjbEUYqfliQkOnKePAnCsXliyVZpJzaaqt/EZ1waUL3DTTnHFY/P9hIIWkv9KxUVB40YXJp3LhiJA+l0Ce7O3sjFnsQv8Bw7cZ+bgA35EyvOMLREA9qvYYxFswH8O1FWoa+4KFx3Cjf+ReFadERIbiGVLLsGt2b6Vwd65z9MGNKnF9/vWXX4FCLzFrX9HiDrf31z/WQQwpYksY5fvrT+U884nzvqs1Fw6SXB/XE2Bi0fxsWZeMK4LO+XL6eMfE9/4Tg0tqQW5Uvqbe09fa5MDqDBTnHsNG0NYIbKUBD7c8ErBZfUcodMzlSu605ne3ey7COvgVYpjh9o8wbwPwaQWMvxBWDJdGt+rhmv/KCMUlODSNwEOUl0+AdDY4cx)?

**Comment by zlodey509** [comment]
It almost works cuz if Modal has small content  it looks stretched like in screen below:
![image](https://user-images.githubusercontent.com/76591663/228594791-d34f2076-bb85-459f-a296-78c967969a6c.png)
