### ISSUE TITLE
[Table] Non scrollable overflow content

### ISSUE THREAD

**Issue by zlodey509** [vexip-ui/vexip-ui#283]
### Description

after fix all-time horizontal scroll in table, the issue https://github.com/vexip-ui/vexip-ui/issues/273 is actual now

### Validations

- [X] Ensure this issue neither a bug report nor a feature proposal.
- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that descript the same thing to avoid creating a duplicate.

**Comment by qmhc** [comment]
Please view this [sfc](https://playground.vexipui.com/#eNqlVW1v2zYQ/iuEOtQy4MhZFruBERfOshTbsDckAfahGlRaOluMKVIjKbue6/++IyXbkitnWQsYsHgvzz33Qt7Gu8nzYFmAN/KuDWQ5pwbehoKQ60c65UBGCTV0HHr2L/ScZqe7lbzIBBE0AzR4x5Q25Dc8hB5hydkC1iidWWklHK1YYlIUXp6fI9R1v4byDPAvtAWXo/DrYH+W0zrgkzt+IdbNvEGOuuN/YlUS/L7u10qPRx0rlhuiwRQ54VTMEcVoV36W5VIZsiEKZj2Ski2ZKZmRDrawY31jKbBctltkbG389zbUpuTOkhHpfNvplSdMGY+3VKcM1E4IGWUcxTdiDpz9XUD0J+U6vbgYXk3MisYQSDXfGe+7W3fYKXctQp2D2MmxOigaXCFdQrZOWKd30aT3YGS8mCq5aKEIiunoB0UXMLgavpnMrTyIZdZKzxq3UHPuTWqX5yeofdek9iuNUyaA/J6DokZ+xu+OM02nYNLoXs5B6TeD4XCiU1ifrOHeo4VoiXFUxOEJppdNpjdFwiSXc6bNMcmHlCopokcqBKjB1WAwESxeMHqqjqV9C78S4YVNHrxoBu+WDKJ3VGWghsPB+cSsc8Z5MGX/tBYPrVt4lf5NXhdV3ULxV9fevvK+4e3yel55wXTwpKXAR9GxDnfS0BuRDbrhb296ltH8GesybujhBbXn0EuNyfWo3y9EvpjbMvdRNbGXX5t+gi2y50AVwrAMAtDZGY7/SoPCIKFX5eHw+ihcgjpTIBJQoE7hT1psGwGPdM8EhY8sPyvYyUwqfTOdShhkrVh9bdYcgli7er0Ytea1h5zsMZl9B0/Xo2HWgGVYgo9HTA/2hWH8BbDO7BRsNXlbHCCcc4EFxsHZP+uxAnTDpfz5417ZoK4SB/1qeR+Ujylk8LBiJk73RjVZ03hDGC4LyvkhUJVBbZXcQ85xlbg5tuvOPkUoKi+U21B+dzflCo9KEBSM35LU7yRs2emR96mPPLuYkF+j0rVXr6zEIVgmcewxWongUEsFxaRRvMI6ylUQRXiOIpTsy+VbUt2g0OBXSXUR3wKgKbZHzNg8KMRK0fwn8QSxgeQeZohgFF7MphkoJdWPVCQcFFqA5WJpSBw4p/PBcbcujrHfeYXfHRS6XASsyB9YT4ZkfAXot4QeFseGPU6MJRihE0Wu8pEb6ihyr1Opl9waJDIuMhAmwP2q1g/AEQlpfHj1zYYl2w+OTWmf4s63iP/3FrmO4+s8I74N+fq1jRyUaOOxg6212aXku7C7rlfNPDDhTCyQiUX79OmQQdmxO46DYAtnrWzhrJ/9Dk4XxKkV2GnsODnuUjAHVZW6/avhScEltZgV65rC9dJpbGdKnz3PFGgS4CiBMt/DTCrwrVfvyMAtoNuU8cQ2vxuYFITvZgLP3vZfL3fCpA==).
