### ISSUE TITLE
Strange bug with scroll content

### ISSUE THREAD

**Issue by zlodey509** [vexip-ui/vexip-ui#285]
### Describe the bug

When I scrolling content by move y-bar by mouse the page acting strange like refreshing (scrolling by mouse wheel dont have this trouble)
 
[127.0.0.1_8000_dashboard - Google Chrome 2023-03-18 17-53-11.zip](https://github.com/vexip-ui/vexip-ui/files/11008957/127.0.0.1_8000_dashboard.-.Google.Chrome.2023-03-18.17-53-11.zip)

### Reproduction

idk why

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zlodey509** [comment]
Ok, another qstn, how to disable `Layout` Scroll and set browser default?

**Comment by qmhc** [comment]
> When I scrolling content by move y-bar

Is this the inner scroll of Layout?

**Comment by zlodey509** [comment]
Yeah, its scroll of Layout main content
I notice in that case page is rerender, not refresh and it happen in all pages in my project
