### ISSUE TITLE
[NumberInput] @change event doesnt work with sync prop

### ISSUE THREAD

**Issue by zlodey509** [vexip-ui/vexip-ui#296]
### Describe the bug

`NumberInput` @change event doesnt work with sync prop
I use `NumberInput` like in screen below: (function that I call on change has to console log data but I dont get it):
![image](https://user-images.githubusercontent.com/76591663/229526611-99947870-9ab7-40fb-a41d-f82e9843a80f.png)

### Reproduction

https://playground.vexipui.com/#eNqVVG1vmzAQ/isWmwqRElNp37IkyjZNWr9MUzvty5gohUtwa2xmTJIqzX/fnaFAoqbqpKrB9/Lcc69771NZ8k0N3tSbWShKmVhYRIqx2fe6uANzpcrasupRpWyZ5olawzzymo8sGEUe20wKnYGcbhJZk879oryyj5LeRbKbbEVm8yn7cHlZ7j5G3mIWDsCbaOWiEbEm4C9CmbL9njk8djjMwhItZ+GAJD6r1IgS+YGtSyaRFUa0FYaIlChKbSzbMwMrdmArowvmY6Y+OaZaVbbFnpPFTLnwC8wJ1atapVZoxbpM98SSvLQELvU68FuVjw4HItZQwcDe2GtiV/y+0gor65yjZ2nkYWLogn+d6aRIylesSUIypE/vyMutLatpGNaqfFjzVBchqpZUl8qGmcB/+OamVlYUwKEqJndGbyswGCTyxgO8EIUbMBMDKgMD5hz+8gXbo4AnuleCwk6Uk1qczaTVH6fTCnnxIlboxo2nlavXm1EHXh3kssMU1O/z9TgyO4IVWILdCdPevrZCvgHWmZ2DJVQaIRygIhEKC4yD0018agDdcLPHLD8Z/dYGda2Yh+0F6JU/cyjgZitsmndGA9mx8Z4JXKVEyj5Qm8Fg0a6hlLhnbo5VUuBm+yTyXXXc8gaj5yk3+DSKoWC+YHngZ2Ljj9nvPECeI0woGFAZ/cHtayrRBys0jj1GaxC6xbUswaRRvMU66i2PY3zHMUq6cgVEasTrCoI2qZE7B4xcsT1qJda8VluTlFfqHlIL2TUelzmzBhfz2AyM0eZbojKJR23O8MwsuvvhdAE47uTiGAf+O/xuz0mkFGzZD6ynQDKBAfTbwBiLQ2FPExMZRvDj2FU+dkMdx1j+Z72WZJDptC5AWf63BvN4AxKRkMbtu/d7kR1uHZvGPqeTiYj/u0Wu44yJFQso5MUFReYN2nzuYAdtdinRve273jazZyKFekAmhPb01GfQdOyrxEGgwpEVFY786JufL4hTG6Bp9J28ygFsr2pTp58BnlZSJ4TZsh4oXC+dhjrT+HQ8c0gyjqMExn6GlTYQkNf4xGAlTGW/5EJm1PwRtzmowM0Evr3DP7yap+w=

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
`sync` prop just makes `v-model:value` based on `input` event. It doesn't change `input` or `change` event logic.

**Comment by zlodey509** [comment]
No, it has difference cuz without `sync` `change` events are work on unfocus

https://playground.vexipui.com/#eNqdVG1v0zAQ/itWQEsqtc4kvpW2GiAk9gWhDfGFoCxLro03xw6O03bq+t+5c7IkLes0kKY1vpfn7p572XkfypKva/Cm3sxCUcrEwiJSjM2+1sUtmEtV1pZVDyplF2meqBXMI6/5yIJR5LH1pNAZyOk6kTXpyDR2D1RW9kGSsEi2k43IbD5l787Py+37yFvMwkGEv0O+Ltp/BioXjYg1sX4QypTtdszhsf1+FpZoOQsHlOCzSo0okQ2wdckkZoURbYUhIiWKUhvLdszAku3Z0uiC+cirT46pVlVDYsMMm5PZTLkcFlhYa3FCGallrVIrtGIdFzuqg7y0BC71KvBblY8Oe0q9SRZT88Zek13F7yqtsNPOOXqSRh6Wji7415lOiqR8wZokJMMC6R15ubVlNQ3DWpX3K57qIkTVBTFX2TAT+A/f3NTKigI4VMXk1uhNBQaDRN54gBeicA1mYkBlYMCcwr94xvYg4JHuhaCwFeWkFicrafWH5bRCXjyLFbqB5Gnl+Ho16sCrg7zoMAX1+zQfB2YHsAIp2B5l2tvXVshXwDqzU7CESiOEA1QkQiHBODjdTqQG0A0vzZjlR8vR2qCuFfOwvUi98nsOBVxvhE3zzmggOzTeMYGrlEjZB2orGKziFZQS98zNsUoK3H2fRL5jx613MHqacoNPoxgK5guWB34m1v6Y/cwDzHOEBQWDVEa/cPsaJvpghcaxx2gNQre4liVYNIo3yKPe8DjGdxyjpKMroKRGvK4gaIsauXPAyBXbo5ZixWu1MUl5qe4gtZBd4fmZM2twMQ/NwBhtviQqk3j25gzPzKK7H04XgMudXFzGgf8Gv9tzEikFG/YN+RSYTGAA/dYwRnIo7HFhIsMIfhw75mM31HGM9D/ptSSDTKd1Acry3zWYh2uQiIRp3Lx5uxPZ/sZl09jndFQR8V+3yHWcMbFkAYU8O6PIvEGbzx3soM2uJLq3fdfbZvaZSKHuMRNCe3zsK2g69lniIBBxZEXEkR9989OEOLUBmkbfyascwPaqtnT6GeBpJXVCmG3WA4XrpdNQZxqfLs8ckozjKIGxH2GpDQTkNT4yWApT2U+5kBk1f8RtDipwM4Fvb/8HU1vaRw==
