### ISSUE TITLE
[Select] on removing item from multple select bug again

### ISSUE THREAD

**Issue by zlodey509** [vexip-ui/vexip-ui#297]
### Describe the bug

[275](https://github.com/vexip-ui/vexip-ui/issues/275) that issue actual again :(

### Reproduction

https://playground.vexipui.com/#eNqVVW2P2zYM/iuEO9QO5tjtsO2DlxyuGzasH4YN7b7Vhc9nM2f1ZEmV5SSHNP+9lOSXJGiKFggciy8PyYekfAheKZVsewyyYGWwVbw0eJMLgNVfUreQtbJGvs6DDZ3+se95AE4/WLwmJ1BaKrLZlrzHLg8GfW5Wb5FjZfwRoO25YYrjeK44lrq8nwVSGSbFsmqwehxlmRd2hD+85YHX3axSjz/mk44JjQnYMpzQCXKxSk9KpGNXaaYMdGh6BbwUDxTE+AJYq6Q2cACNm5geZWXYFuEIGy1bCImx0EJUlI+BiRxYT6bRwcb0lGTw7pcYfn2fi+Ni9hrKIZ9XWpdPiUWODsBRPJgmg5c/wTGGqIiBLWB9Ax6Ql/fIM7j71znDDwcGP8LL4108RcvAiWwsCrZKfZFDweaJI3SVVFiTJNnu1bJzHIJDb8v9csdqG/7nFy/U/jdCcRjW7yaIA09Ll3zopKCRcU75KM2DDA5kT7/JdNmW6ivWQ6MC4tOe86AxRnVZmvZCPT4klWxTUt3alnUmrRk96JzoXhjWYoJdu7zXctehpiB54FgY8FISblEvNYoaNepr+LdfsD0LeKH7SlDcM7Xs2dVKBv15OYMwab+I5alPqs7x9c2oJ14T5O2EyewAXufjzOwMlhEF+4tMZ/veMP4NsM7sGqxFtSNEA9SWTBDBNDjTMla0XQbpyoqhudjFwYZ0gzhJh6ttVv7fYItvd8xUzWR0Ijs3PgCjLS05nwMNFZxs/htUdundHIuypeULrSh07Lh7JVqMU67pqAWQgLa5icKabcMY3jUR5bmggqKTVBbvaXc9E3OwVtLYUzSP4FC9oqSiSbwjHuUuKQo6FwVJJroim9Qi6TuMhqLs3WAByJTaIzbsIenFTpfqtfhA1wHWb3BDCEbTYp6bodZS/12KmqMmC7S52DQkDZzTRehyty4u4yh8Ru8hCV0tAnfwH/HJKJlII/lt0d6wNuxlYaymCGFROOYLN9RFQfSPesmtQS2rvkVhko896if/TaA07p7R7Vgf71w23r6h29wifu8WuY4DsA1ENuTz5zZy4tHWawd70mZXUuTCjl0fmjlnwpl4pEws2qdPcwW+Y39yGgRLnLWyxLmbn96T64Q4tXafoNDJuwbRzKqhdPt3gicFl6XFHLI+UbheOo3tjPeZ8mywrBMaJdTmd6TPH0bWK74w2DDdmT8axmvb/EViGhSRmwk6B8fPS1DoPg==

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
The reason is that the internal buttons do not have a type specified, and they will trigger the form to be submitted.
