### ISSUE TITLE
[Select] Focus event isn't emitted in single mode with filter

### ISSUE THREAD

**Issue by zlodey509** [vexip-ui/vexip-ui#300]
### Describe the bug

This issue [264](https://github.com/vexip-ui/vexip-ui/issues/264) was fixed only on `multiple` select but on `single` mode it doesnt work

### Reproduction

.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
I can't reproduce this in a simple usage, would you show how do you use the select?
