### ISSUE TITLE
[Table] Page crashes if it has Table component

### ISSUE THREAD

**Issue by zlodey509** [vexip-ui/vexip-ui#303]
### Describe the bug

after 2.1.11v release ALL `Table`s crash the page (it seems like freeze and I cant do anything) in ALL project components with them, I guess it because of https://github.com/vexip-ui/vexip-ui/commit/89df1fc2a57ef370d43be7cabca7ff6730e5518e that commit cuz in versions before 2.1.11 it nothing crash

### Reproduction

.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Maybe fixed by 4dfccb8a7725023117ace6dfed4910c23dafb6c8.

**Comment by zlodey509** [comment]
No, it doesnt fixed
I notice that when it crashes my CPU was overloaded to 100% and page with `Table` component rerender an infinite number of times

**Comment by qmhc** [comment]
Should be fixed in `2.1.14`.

If you want the `main`'s height is fixed, you can add `fixed-mian` prop to `Layout`.

**Comment by zlodey509** [comment]
na zhri: 
https://playground.vexipui.com/#eNqVVmtv2zYU/SuEOtQKEMttWruBkQTOshbrsBeaDvtQFyojXVusJUqjqLiZ6//eQ1JSJMcuUvRh8dzXuZeXl9x4l0UR3FbkTb0zTVmRck0Xc8nY2Xt+kxKbRnlaZbI8n3v119xj05hrDsT8zD2r3hhcWSUmeUZQeCNUqdmfWMBKxMMV3QFdGLQGp2WuNCmgG2M+1aqiY6bvCpoyJwrNYmtUcxVbzWdtTERtSLMnMS14lWrjiql8zWDTqkHxbZRLVuq71BDLuFoKOVRimegpOy2+9HSh/U9J6uJsZH86TkbGSwfY2FBBmxHbbltmo149DdCp0J6iNYZ17X7Lb+Zeg7W1+9xFpzyKqESZnOCyXnUUmpK9aDDk9EMsLpfYpQcseBdtg5x0MEUSoIXdZ8fRHg41gu9e2bAsIyUKzUrSVcFSLpfwqNGEkIqsQIcwbAEtjlnCtmyh8owN0M6DjtTsYSub3dIXUQwrMRLYyRJ6jM2l+USM+35j52zAywhi88eJ6/6HCPH8D8Zy4xIytZqywe+8bvbBscNRLMAp4C5qyzVlz80K3fLxqAlgjtMe7yKGk+eNNfYZyyteJoJUA1LGRQr4Ui4pFf9VFP7L0zI5OZmczvSaRxTkatkot83aNWiEDVnIrIsGx44DGp/agm0t2KV30qd3rfNodaPy1R6KpEQZ/qL4isank1ezpcGDKM/20jPKe6hZ8z61l88OUHvRp/YHjxIhif1VkOI6f8DvdSpKfkM6Cd/lS1Llq/FkMisTujtYw9ZiD1HnY6eIkwNMX/aZXlaxyNN8KUq9S/I64SqX4XsuJanx6Xg8kyJaCX6ojk5/Dz/n4ZGbPH5UD76+FRS+4SojNZmMn81wnESaBjfi/73Fg/YeXs6+z+ukrps7MnO5qGSkBYZ6Z/T5mMZTnHnLsNRKyCXbHrksFEaIknZemykq4ajjJOEyTglT6ipFKf3axhzMPKVAyEXuDyIjoniA8H3jdsT59dVjONRULPmGyi6ZxHcZDsqCt/tT1xzRUZESmWd3Q3hpxJgg0pKc7pB2YrdvjH0YuLId24zx/dHgjvrZyI1VDFHv2HOTsgw+l7nEO8CGnzfo3EMSMMHfVnWY8eI72i7+3MMcNuu5l2hdlNPRqJLFaml6dATRzMz4Uo9i9LdZB6qSWmQUUJkNMTvWGNsIMvfqfKy/EcBbUsPmejnkf7ZHtxdwR/adoPV9cTCTWt5PpwaDbK+vkX2GBFFp6/Vorx2r1uXOfXa4Hj21nluBEnzZYXqvX2mRPsKtVTvktj62WzQQhoREgdE47f0cKYIZ3qEP7nDV3uKQ1oJgVL9Yu+L3CWV0vRY6Slq1DrarvmEC9y1P0/twdR5Wy/xzN/I7KlLcyBuDtNe8AXEWLWSfJXZY2GV7rgGdX+B0D2JxixP4IfHB+ggJ+h1aR5hj1mxrfux/96GzHMcBsZ2n2r8TcRQDgjUqjJMdhliHIZC2kL6heBRUJfl1okc2knMCdWyeXIhlUMm14sVb+ZkiTfE7WsCLeYE/UCSlcvWrnTYKOngfXbSz0cp8qnMxRpa7P3iCb8zKbm6S1uxvVFyAmq8I9rd47isyBB4mKmLzDgtDuzuhbf8wtFvUaOSpUYnzqMpI6gAPGXV3TSm8gdKnJz9tRLz9VDNzFgmeV8brj565tjNwGS6YbwI/fWriB87j+bl13WsFm55fh296o7PlXV6pkCvwMn6/fr3PyO3p6xRNY0pqtFxJna1ZB98rk1VQZLp4YCV4ypDuCuuCmJ8dv7lMc25815n0RHbXrczs3b1lyzwhHuPexEDVP9MiV+Qby+MdBfsWuEpEGrtGOQp0QtK3HWQRb/sN6HjTZQ== 

Playground crashes when I set `TableColumn` sorter prop

For comparing the same code on 2.1.10v na zhri:
https://playground.vexipui.com/?vexip-ui=2.1.10&vue=3.2.47#eNqVVmtv2zYU/SuEOtQKEMuJW7uBkQTOshbrsBeaDvtQFyojXVusJUqjqLiZ6//eQ1JSZMcuUvRh8dzXuZeXl1x7V0UR3FXkTbxzTVmRck2XM8nY+Xt+mxKbRHlaZbK8mHn118xjk5hrDsT8zDyr3hhcWyUmeUZQeCNUqdmfWMBKxP0l3QOdG7QGJ2WuNCmga2M+0aqiY6bvC5owJwrNYmNUcxVbzZM2JqI2pNmzmOa8SrVxxVS+YrBp1aD4NsolK/V9aohlXC2E7CuxSPSEnRVftnSh/U9J6vJ8YH86TgbGSwdY21BBmxHbbFpmg616GqBToT1Fawzr2v2W3868Bmtr97mLTngUUYkyOcFVveooNCV70WDI6YdYXC2wS49Y8C7aBhl2MEUSoIXdZ8fRHg41gu+tsmFZRkoUmpWkq4KlXC7gUaMJIRVZgQ5h2AKaH7OEbdhc5RnroZ17HanZw1Y2vaMvouhXYiCwkyX0GJtJ84kYD/3GLliPlxHE5o8T1/0PEeL5H4zl2iVkajVhvd953ey9Y4ejWIBTwF3UlmvCTs0K3fLxqAlgjtMe7yKGk9PGGvuM5TUvE0GqASnjIgV8JReUiv8qCv/laZkMh+OzqV7xiIJcLRrltlm7Bo2wIQuZddHg2HFAozNbsI0Fu/SG2/RudB4tb1W+3EORlCjDXxRf0uhs/Gq6MHgQ5dleekZ5DzVrvk3t5ckBai+2qf3Bo0RIYn8VpLjOH/F7nYqS35JOwnf5glT5ajQeT8uE7g/WsLXYQ9T52Cni+ADTl9tMr6pY5Gm+EKXeJXmTcJXL8D2XktTobDSaShEtBT9UR6e/h5/z8MRNHj2pB1/fCQrfcJWRGo9HJ1McJ5Gmwa34f2/xoL2Hl7Pf5jWs6+aOzEzOKxlpgaHeGX0+pvEEZ94yLLUScsE2Ry4LhRGipJ3XZopKOOo4SbiMU8KUuk5RSr+2MQczTykQcp77vciIKO4h/LZxO+L8+uoxHGoqlnxDZZdM4rsMe2XB2/2pa47oqEiJzLP7Prw0YkwQaUlOdkg7sds3xj70XNmObcb4/mhwR/184MYqhqh37LlJWQafy1ziHWDDzxp05iEJmOBvq9rPePEdbRd/5mEOm/XMS7QuyslgUMliuTA9OoBo+iIYBi9fDWL0t1kHqpJaZBRQmfUxO1YY2wgy8+p8rL8BwDtS/eZ6OeR/ukd3ai4VxLIBd2TfCVrfFwczqeXTYXAanJ7U6dRgkO31NbDPkCAqbb2e7LVj1brcuc8O12NLbasUAiX4ssP0Qb/SIn2CW6t2yG19bDdoIAwJiQKjcdr7OVIEM7xDH93hqr3FIa0FwaB+sXbF7xPK6GYldJS0ah1sV33NBO5bnqYP4eo8rJb5527kd1SkuJHXBmmveQPiLFrIPkvssLDL9lwDurjE6e7F4g4n8EPig/UREvQ7tI4wx6zZxvzY/x5CZzmOA2I7T7V/J+IoBgQrVBgnOwyxDkMgbSF9Q/EoqEry60SPbCTnBOrYPDkXi6CSK8WLt/IzRZridzSHF/MCf6RISuXqVzttFHTwPrpsZ6OV+VTnYowsd7/3DN+Yld3cJK3Y36i4ADVfEezv8NxXZAg8TlTE5h0WhnZ3Qtv+YWi3qNHIU6MS51GVkdQBHjLq/oZSeAOlT89+Wot486lm5iwSPK+M1x89c21n4DKcM98Efv7cxA+cx4sL63qrFWx6fh2+6Y3Olnd5pUIuwcv4/fr1ISO3p69TNI0pqdFyJXW2Zh18r0xWQZHp4p6V4ClDuiusC2J+dvzmMs258V1nsiWyu25lZu8eLFvmCfEY9yYGqv6Z5rki31ge7yjYt8B1ItLYNcpRoBOSvu0gi3ibb3qBzb0=

**Comment by qmhc** [comment]
You can advoid to use primitive object in `TableColumn` (in template) as a workaround.

```diff
- <TableColumn :sorter="{ type: 'asc' }">
+ <TableColumn :sorter="sorter">
```
