### ISSUE TITLE
Set the popper components dynamic z-index

### ISSUE THREAD

**Issue by zlodey509** [vexip-ui/vexip-ui#307]
### Description

1. How to config that (in docs i found nothing about this)?
2. How to config for example z-index for `Notice` component global?

### Validations

- [X] Ensure this issue neither a bug report nor a feature proposal.
- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that descript the same thing to avoid creating a duplicate.

**Comment by qmhc** [comment]
1. Can use the install options or `ConfigProvide` to specify a `zIndex` initial value. (This part is missing in document, sry)
2. Can specify a `z-index` style for `.vxp-notice`. All `Notice` items are under a wrapper that has `.vxp-notice` class.

**Comment by zlodey509** [comment]
For best practise, I need wrap inside one `ConfigProvider` all poppers or wrap every popper singly?

**Comment by qmhc** [comment]
If you use `app.use` to install, you can do like:

```ts
import { install } from 'vexip-ui'

app.use(install, {
  zIndex: 12345
})
```

If you not use `app.use`, I recommend you wrap app inside a `ConfigProvider` to instead of ths above.

**Comment by qmhc** [comment]
Well, I‘’m developing a hook function for better usage. Use like:

```vue
<script setup lang="ts">
import { provideConfig, configProps } from 'vexip-ui'

// For multiple
provideConfig({
  props: { size: 'large' }
  // locale, icons, zIndex
})

// For single
configProps({ size: 'large' })
</script>
```
