### ISSUE TITLE
[Scroll] Content rendered too many times

### ISSUE THREAD

**Issue by gltjk** [vexip-ui/vexip-ui#316]
### Describe the bug

When the content within the Scroll component is scrolled, it is rendered every bit the mouse wheel scrolls, which might lead to low performance of the page.

To check this, just open the following reproduction link, and then open the browser console. Though this issue only addressed the Scroll component, it is the same with the Native Scroll component.

Ideally, everything in the content should be rendered before scrolling and should not change unless as a result of Vue's reactivity. Scrolling should not trigger the change.

### Reproduction

https://playground.vexipui.com/#eNqVVcGK3EYQ/ZVCDpaGjFp2QgKRd8wmIZDcgte3KMhaqWbUXqm702rNzDIeSCAQyCeEHHzwwZfkB2x/jdnF/gtXtzQazeIxNiy76qpXr6peVfduvG+VYssWvdg7MVirKjN4PxEAJwVfQmMuK5wlXp2twxUvTBnDl1/fUet7cC51gTqGZaaDMFyuVdhZwvOswcm9xHMkRHOWa1lV0DYYXpJTQ1wiX5SGWO9+cWfAEVLBMpxLTQ4BXMA3iQfxBV7a8wgGsNmAgO329e9/0JdGQVkf4toE/tW/z6//e3b17M/rF/9c/f387cun10//ou83r/73Pxcw2W6HXJHa1Rd1BXY9R9Q0fZ1EIyno6GSAJpcKC7Iw227T9aVgYyNVVhRcLGL4Sq3hrlUoEZTtJHKhPUuuuTLQoGlt9nkrcsOlGLdg6NekY8ylaGSFrJKLzmyNmmK1AHve8TtSovOmHq+V1KZhjxspaJ6OJtlZEy+GDYXQzwAN60x9AN0plHi0HvaceKUxqomjqBXqYsFyWUfkOrU6NYako190ZroVhtfIsKnDcy1XDWpKknjTEV9ExiVtS9c76mP8p+/BHiS84ftAUlxzFbb8aCe9/7Cd3sjq93J102V54/T6aNZR1EB5OnByO/njehzADmg5SbC+Ueke3xpefQStgx2jtax2hWiB6owLEpgWp9sY2ECukcLoPZlCCVuYa1mDT/PzE9FjyNebWdS/O3vnwxJrPFtxk5cDaGQ7BG/ohWhMRhdwSNR3QJhEWG0MPEBVwazbY5HVGINvTb5Tx13DoL9sw80iw+w+lIFPD4E/hV/KgOqcUEPBqJTJr+4ydpdpl6yWtPaUrWMYrrCBjJom84p0lCuWpnROU7IMcgW2qAmjFzLom5oQvyUgKI1HzPmCtWKlM/WTeIy5weIBzonBaLqYhzDUWuofM1FUqAmBtpbdS+J8AbrabYirOPBv0bdPRteLwBX8THpyKibQSHFLnJI4Nu3NxnhBGfw0dcqnbqnTlOTf+WVlAYXM2xqFYb+1qC/PsCImKuPRrc82vNg+ctV0+FK7rvxPvUVu4gB8DoFNefu2zcw6ttnM0Y7G7FoKXNrd1Pth7iupuLigSizbkyf7DrqJ/VDRIljhLMoKZ+PsNzsuiHNrtNvoO3tTIpq9q2/d/hnxSVHJzHL2VY8cbpbOYyfTxQx1lpgVjFYJtfkO6T8qBjZqegMw57ox35e8KuzwJ8yUKAK3E3T2tu8A4yPUaA==

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
You can view this [vue sfc](https://play.vuejs.org/#eNp9UV2L2zAQ/CtbUbADiX1pCwWThJS+9AcU+qKH89mbxD19Ia3THsb/vbt2Lk1TuCdJo9nZ2Z1BfQmhOPeoKrVJTewCQULqw067zgYfCQaIeFhC423oCVsY4RC9hYyLMu20a7xLBDYdYSvMPPuGxnj44aNp32WLVwL5cCE8XLFELwYZfdXO8wVsd5APwq7g8f3AZ3GuTY9j+P0I44JLtTv0rqHOOyBMxCWDdiAVM5P11g/3CAOjYDfFEV2LMWfjFwXx5A0Wxh/zrBbnwCTqo5PpJoFNOe+It8MPQhtMTcgvgM1pDdU00Far6dQK9o3pmmcGxKlWE5GpKdRuN8hi/1oYRxYXfBIrT+v5IkFIzVcRgvrJnxG+d8RrwzPGF+osLoHdArs+cjqdu84xC4nAprxaVUs157qydSh+Ju84+Wl8fflIWlXzQgTjlOWt1YkopKosexeejwUnVu75r4y9Ew+r1tv9x+JD8elz2XaJbvECk109Rf8rYeSOWi1vxEsGeZDVvAqMbza74/7T8O7vv6bSkxMc1fgHFTUB+A==).

Attributes update (although value actually has not changed) will trigger template render function be called. (Ideally should not trigger if  the parameters same, you can follow this [issue](https://github.com/vuejs/core/issues/8180))

If the template render result is same to prev, the Doms do not get any update.

**Comment by qmhc** [comment]
https://vuejs.org/guide/essentials/computed.html#computed-caching-vs-methods

You can see above documation of Vue, this behavior seems to be expected.

**Comment by gltjk** [comment]
> https://vuejs.org/guide/essentials/computed.html#computed-caching-vs-methods
> 
> You can see above documation of Vue, this behavior seems to be expected.

Thanks for your reply. I know it is the expected behavior that methods are triggered every time the component gets rendered. I just don't think it necessary to re-render the content when it is scrolled. It should be natural that the content is not rendered every little bit it is scrolled (unless in a virtual list where new content keeps appearing and old content disappearing.) Maybe this could get optimized on the Scroll component's side?
