### ISSUE TITLE
Nuxt module 

### ISSUE THREAD

**Issue by alphaelf** [vexip-ui/vexip-ui#317]
### Description

it is good to have this amazing ui library with best vue framework, Nuxt

### Validations

- [X] Ensure this issue neither a bug report nor a feature proposal.
- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that descript the same thing to avoid creating a duplicate.

**Comment by winchesHe** [comment]
Hi, thanks for your suggestion, we just finished Nuxt Module , if you are interested, you can check this repository to use

https://github.com/vexip-ui/nuxt

**Comment by qmhc** [comment]
Vexip UI Nuxt module now is included in nuxt/module, linked https://github.com/nuxt/modules/issues/642.
