### ISSUE TITLE
组件[Wheel] 加个滚动条，滚轮有问题，结果上下乱跳

### ISSUE THREAD

**Issue by dmyz** [vexip-ui/vexip-ui#319]
### Description

我这滚轮有问题，结果上下乱跳

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that request the same feature to avoid creating a duplicate.

**Comment by qmhc** [comment]
请提供一下复现以及操作步骤。
