### ISSUE TITLE
当使用RadioGroup时，group的value与其的radio的value之间存在误导性

### ISSUE THREAD

**Issue by Ljry-yiyi** [vexip-ui/vexip-ui#320]
具体情况，请看示例！

**Comment by Ljry-yiyi** [comment]
[https://playground.vexipui.com/#eNqVVm1PG0cQ/isrp8qdJfvcfnVxRFpVbb5FpN9C5By+NV64t+7t2SDH0qnlpQhIK5UqQGjUVo2aVqIuaoQs4pD/Qn2H/Ym/kNndO/uOhChBCN/OPPPMM7MzZ9q5m66rNX2cK+emGLZcU2f4xqyN0NSMbhDnS+r4LmoWLcfAZrmpmz6uzObEpzebE8AECqi6Q8FLgAcRG/FPAKHyIl6OzZqIBJtg1CeMGWfZ1OewmVjFYZKrJJJJifJZaJQGF3ls2eSElk7niV1kjltGn3zsLn06ZhBZyqjdlk8e6nQkmeQopn4kZxwXvvxpFGyc7zwLt3+Gh+i3tfMXK9Gj44v+1jxXcL6/IgiHr3bCx0/gFAb9QW872u0K96C3GR5xM+WaE/BF//HUHC3FKYbBFsAlweBkLRWXBIlm/B98mwq6efvWaH0r2gjCtb2Efth9Hu0+LKOz4GCiVigCtaNgP+z1Rqvb4Y/fI5EDQSWDF8eDl6+gvLPglxR7ePAs/OfJaG9VOmW94epxUsCg91BoGvT3o4ONYbcbdvtR8CdIhIfh+vOo+8Og93ciP9o9Pf/jJPp1/fzwFMSE/x5BvSk2sEEktCHTpFQXeSmbf2Xh6dsb3xakGZxuXvT35bVBUHQE8g5lAaPfV6Lv/hv0DjM3F57sDLtPIZVSsxVAgQ6Z+izYldFnwV4m4VQptTNw9GqUuAx5mEFTTd2eh0lkclGI5TqUoTaiuI46qE4dCymweAoPrDm2x5J5rHCIqij5xC4WCcx328AJvS4jRcpRCsk0c8WoU+DKUqBHT7OgBfdN0HDzKAvCnOker01WA9pzhZyU72kLnmPDu6LNSWBBpXU2B/sEWwS/Y2jR0t13oOUtwauEb3wZHhqMuV65VPJtd3FeqzlWCVzTvLUeKxkE/sBZo77NiIU17FnFOeq0PEwhyWxOFBXzlcDYxLRIsW1giulV/NNvwWYSXvK9IyleIm7RJ1dWEvuz5cRGzXorV0m8ybSaJ/r13qypqDHl9JiT8IG6uh8ZWIaWQAuWLimd4H1GzPegFbCraDkrHyEYIEsnNjQYBme8NDWKIQy+qwqocWl7Ygz4YrNWir/TJs6vG9jCd1qE1RpjUMqWBbfhy8tjumlOEsUVpHZ1BrsmrKSYY1u3+OJwkyK6I/ZfzSdTTuFIbQSGyg3UUBWDNGHf7jZU0JmHgtSUlPw9WHvZiUkyy4Gxh2ySQbBKhw5Fg7kFfXRaWrUK52oVLON2qVxUXvM9rMZF5YGfEwAUrseuk3nNt1tUd2/ZC7jGsDED76cKYhQWMwvDlDr0K902TEwBgbkWLsOBgRM+FQvtPEQoVpVr8MzfY6IWG7fQbegnATEqxRDXxAVoDk97uTBiQAalWhWdr4qhrlah/YnfMTnAcGq+hW2mfeNjunwHm8AEMu5f+6hNjM59oUbiG/ytC4wfukXixhEidaTylNev88yaZKtUBG3qmkVJqkib3Hp8mRMlJrEXQQlne/BgUoG8sS9MGATeOI7ijeNx/Fm7uiHCTTGfRkXYvQbGbOKKS+cfKT7HNh2dc8aqUw5xl8LDb0bGjHU2sG5oMEqYss8w/L+HVR5VuASoE+qxzxvENPjl5zXWwLYqZgLOuc5rx14dxQ==](url)

**Comment by qmhc** [comment]
谢谢你的反馈，请问为啥又关闭了该 issue？

**Comment by Ljry-yiyi** [comment]
> 谢谢你的反馈，请问为啥又关闭了该 issue？

因为后来发现，在这边，radio的label是用户习惯的组件的value，而插槽里才是可以 放置radio对应的label（取的名称）。想了下，可能之前因为某个问题，才会有了现在插槽放radio的label，而label属性放value。。之前提这个问题，是因为这样可能会有误导性或者二义性。

**Comment by qmhc** [comment]
好的，谢谢你的跟进，我们经过检查发现文档中对于 Radio 的 `value` 属性的描述确实存在错误。

在 #322 完成后将改为新的 `value` 的描述：单选框的值，当与 `label` 全等时单选框被选中，与 RadioGroup 组件一同使用时无效。
