### ISSUE TITLE
[Nuxt Module][Warn]: Unrecognized slot name

### ISSUE THREAD

**Issue by alphaelf** [vexip-ui/vexip-ui#323]
### Describe the bug

i use `X` prefix for components and when put `<template #main>` in `<XLayout>` i get weak warning `Unrecognized slot name`
same usage with other ui framework (e.g. element-plus) works fine, even slot name auto-suggestion functionality

### Reproduction

none

### Steps to reproduce

just install fresh nuxt app with vexip ui module and run dev server

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700
    Memory: 14.51 GB / 31.75 GB
  Binaries:
    Node: 18.8.0 
    Yarn: 1.22.19
    npm: 8.18.0
  Browsers:
    Edge: Spartan (44.22621.1702.0), Chromium (113.0.1774.42)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vexip-ui/icons: ^1.2.0 => 1.2.0
    @vexip-ui/nuxt: ^1.0.0 => 1.0.0
    vexip-ui: ^2.1.20 => 2.1.20
  IDE:
    Intellij IDEA 2023.1.1 (Ultimate Edition),
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
I made a test project on StackBlitz: https://stackblitz.com/edit/github-hqzmvc?file=app.vue

Could you reproduce this issue in the project?

**Comment by alphaelf** [comment]
This is not a problem with the prefix. Rather, it is an issue with how the named slot definition in ui components, which IDEs may not be able to resolve. As you can see from the images, the Element Plus Nuxt module uses a different approach to defining named slots, which makes them recognizable by the IDE.

this is for element plus:

![element-plus-no-warn](https://github.com/vexip-ui/vexip-ui/assets/19430683/ec64b777-e469-4aeb-8443-d08c53c343bb)

good suggestion available slots:
 
![element-plus-slot-name-auto-suggestion](https://github.com/vexip-ui/vexip-ui/assets/19430683/fca8caa3-9310-4c85-b4c1-eea74c481719)

and this is for vexip ui no suggestion:

![vexip-ui-slot-name-auto-suggestion](https://github.com/vexip-ui/vexip-ui/assets/19430683/8b80e21f-1700-4867-a0b7-04bded9895d0)

and nor recognized:

![vexip-ui-slot-warn](https://github.com/vexip-ui/vexip-ui/assets/19430683/121749c6-de4e-4c9f-b792-86174f50bd09)

and i think maybe element plus use vue `renderSlot` method for component slots
