### ISSUE TITLE
Space between Label and Input

### ISSUE THREAD

**Issue by technbuzz** [vexip-ui/vexip-ui#334]
### Description

Here is the code 
```
  <Form :model="formModel" style="max-width: 500px;" label-suffix=":">
    <FormItem label="لقب" placeholder="لقب" :label-width="32" prop="name.ur.title">
      <Select :options="options" size="large"></Select>
    </FormItem>
  </Form>
```
and that how the result look like
![image](https://github.com/vexip-ui/vexip-ui/assets/1523391/34ec90da-6ef1-456b-89c4-2bef048bbe59)

**How can I create a space between label and input?**

PS: I am using Urdu language here.

### Validations

- [X] Ensure this issue neither a bug report nor a feature proposal.
- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that descript the same thing to avoid creating a duplicate.

**Comment by qmhc** [comment]
I think you can using `padding-inline(-start|-end)` and `margin-inline(-start|-end)` to replace `padding` and `margin` style.

By the way, rtl support is in progress, but it may take take some time to complete.
