### ISSUE TITLE
[Docs][All] prefixed with '123'

### ISSUE THREAD

**Issue by ryuhangyeong** [vexip-ui/vexip-ui#336]
### Describe the bug

All components Docs Prefixed with '123'

https://www.vexipui.com/en-US/component/masker.html

<img width="1100" alt="image" src="https://github.com/vexip-ui/vexip-ui/assets/27342882/0eaeedcd-1f57-43e2-9840-45ff7e96e6f9">

<img width="1056" alt="image" src="https://github.com/vexip-ui/vexip-ui/assets/27342882/dc9ea964-a30f-48b4-8825-e7c221191aab">

The same thing happens with all component documents.

### Reproduction

https://www.vexipui.com/en-US/component/masker.html

### Steps to reproduce

https://www.vexipui.com/en-US/component/masker.html

### System Info

```shell
Chrome
Window 11
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Completed in e6c5b09.

**Comment by ryuhangyeong** [comment]
@qmhc Is it about to be distributed? still same problem

**Comment by qmhc** [comment]
Now it should show an message when the value is invalid.

![image](https://github.com/vexip-ui/vexip-ui/assets/40221744/c08554d3-220a-44f9-968e-f89b9238d968)
