### ISSUE TITLE
Badges' texts appear too high in Firefox

### ISSUE THREAD

**Issue by Extarys** [vexip-ui/vexip-ui#358]
### Describe the bug

Under Firefox, the text inside badge is too high.

![image](https://github.com/vexip-ui/vexip-ui/assets/11581433/6aec1cf9-97cb-4a30-a92e-7736ae99afea)

### Reproduction

https://www.vexipui.com/en-US/component/badge.html

### Steps to reproduce

1. Open Firefox
2. Navigate to https://www.vexipui.com/en-US/component/badge.html

### System Info

```shell
Firefox Nightly 115.0
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Extarys** [comment]
I opened a webcompat issue too about this, but it's usually quite simple to get it right with css. Nonetheless, something is going on. I'll post the link once the issue exit moderation queue.

**Comment by qmhc** [comment]
Emm... In my machine, it looks OK.

![image](https://github.com/vexip-ui/vexip-ui/assets/40221744/b3db4419-a753-4afa-b6f3-8eb64446b749)

**Comment by ryuhangyeong** [comment]
window 11
filefox (113.0.2) - 32bit

<img width="782" alt="image" src="https://github.com/vexip-ui/vexip-ui/assets/27342882/f96f5487-7501-4caa-a56d-ef1310c0509e">

I'm not experiencing any problems in my development environment either.

**Comment by Extarys** [comment]
Are you both on Windows? Just to make sure

**Comment by qmhc** [comment]
@Extarys Yes. I also noticed that it's no difference on Ubuntu. Which Linux system are you using?
