### ISSUE TITLE
Nuxt3 中，切换主题模式无反应

### ISSUE THREAD

**Issue by Administrator-M** [vexip-ui/vexip-ui#360]
### Describe the bug

操作步骤：
1. 新建nuxt3项目
2. 添加Vexip UI 模块
3. 复制文档中[ 布局Layout ]  基础用法代码示例到页面

结果：
点击右上角用户图标切换主题模式无反应
![image](https://github.com/vexip-ui/vexip-ui/assets/55430579/c121892b-2f09-4cfe-993f-7f551cb78f5d)

![image](https://github.com/vexip-ui/vexip-ui/assets/55430579/26cac44e-0766-4693-9ee7-eaa15182a6f4)

### Reproduction

无

### Steps to reproduce

1. npx nuxi@latest init my-app
2. npm i -D @vexip-ui/nuxt
3. npm i -D vexip-ui
4. npm run dev

### System Info

```shell
无
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Administrator-M** [comment]
解决方案：在页面中 import 'vexip-ui/css/dark/index.css'  添加暗黑主题

**Comment by qmhc** [comment]
请在 Nuxt 模块选项中添加 `importDarkTheme` 打开自动引入暗黑主题样式，参考 https://github.com/vexip-ui/nuxt#module-options。
