### ISSUE TITLE
Two fields inside the same Column when using Form

### ISSUE THREAD

**Issue by Extarys** [vexip-ui/vexip-ui#385]
### Description

(Please rename to a more appropriate name, I got brain fog)

Provide an example or the necessary tools to use `Row` and `Column` inside `Form` so it's easy to put multiple fields inside the same column.

As an example, having two `Number` fields under `Input` shown in the screenshot, where each field takes 50% space and use the same gap as defined in the `ConfigProvider`.

![image](https://github.com/vexip-ui/vexip-ui/assets/11581433/a3f02ec6-e3de-4b12-b27d-db33378200b4)

### Suggested solution

Make ConfigProvider's `formItem` also apply the configuration to row and column childrens.

### Additional context

Not sure if this is currently possible in any way.
When I can manage to make it so that both fields are on the same column, I also need to tweak every container, so it fits with the cap and alignments from the parent.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that request the same feature to avoid creating a duplicate.

**Comment by qmhc** [comment]
Is [this](https://www.vexipui.com/en-US/component/form.html#form-layout) you need?

Currently `Form` and `FormItem` have built-in `Row` and `Column` respectively. You can pass `gap` prop to `Form` or `span` prop to `FormItem`. Refer to Form API.

**Comment by Extarys** [comment]
An image is worth a lot of words.

What I'm trying to achieve:
![image](https://github.com/vexip-ui/vexip-ui/assets/11581433/dafa1b6a-9ff7-4c22-8d6d-23459f873ea4)


Currently:

[Playground](https://playground.vexipui.com/#eNq9V9tu3DYQ/RV2U2RlwKtNgz4UCztw66aNH5IGjtE+dIsNLY12mVCkQlFrG44/yN/hH+sZ6rKSb4mTtEjgJWeGZw5nhkPqfPRzUcTrikaz0Y6nvNDS07O5EWInVWsMdvatydTytbNrlZITs8LZotydj/DLkhSaopyPYDr3/G/nN+tyMcttShpmGWYveTwfidlSFhA9fYLxu6r0KjvDtCxkQhPpbGVSKLQ8Jj2RWi0NlN4WPewG/QBEaztYvLI5VjErTIzMaWCPFQemqLyY9kGmLcq9yIdXl9nVpSOTALP14Cg7AM1v5GJflolEWDf4SScZumgtxcwWXlnDKfCO6I96BvOdaWvzcB5vSFPiNyzKZj7kUFv1GTSj4L3WftL3d5OJuEngV5Tdxn0aZkPnbPFaJe+xvZ1pb/LgvR4prpHWlQ+zoSu26Fz1Jre6EpPJje3h6IhEy5JDlGk6nfwg+Ad+hta9dftWV7kRM73kE/IjCLYAnk79RC9FZo2f5JSqCgX/7IhKsKhX3Y54Y+OvnToVKYk1mX6wTZUfhwqsfcP1MBqvgr4ucZx+SlSJnDNLrPmCmh/QELkyKpfcHQZ0GPv/4mMrl4CLXBLTcvJYqlLk8vRb8pqVVZapU8xeyqVB41Nm+TsnuOX8CdY3yoOPe5f83vIB1C2xt2mlvLCVKMmtVb+zqTJoQxto/NxoACfKJythCzITLssNYqhXW1IrftOhf0FGmsUgdnVZyLOryyFJKqTim+J+kl/hNx3LY2sM5aiKvus31XGZOBV63lf4//ys3sn0AEfHGamFsf2j/OcRoi8dyRsdrZFzP2uH/wE9mXBohq5ZicDlqLq9MvwCbCVNqqkWg/4eOWddJ3/Os+Bts/gm6CGV5BubenxvwmtRM+V99J819Ytn2jx5pr2HEKZ1znFgfFUgA4aj4esnj8oL67w4F3gWbOMPB2BN4kJkzuZijHfVmCE6s2uHvzPcW9OpKiaVmqoE92lYxAMv8nIpdhk+Gr8gra34yzqdfjfeag26B1YwqwlE5xedfvBOg805RyClTFbaz+rZ3CeaJBqfppnwrqLtWiorbxOLUJCHIpO6bDWITkIrqxG6mZiP5iOWQ3MR9EyJY9/BO/pQKUdpDyTI8fQzM/H0SYOqlzPxU4CZG/zfmdaRR5xH26M6hmX8rrQGj1UgC3hupPMRfNWrOtNJLot7rFnCMuSI56g974tyNp1Wpni/jLHvKVR7XAalR2XgD+axqww/GWIq88mxsydoo3ASAtDhTbm3kpvg6YgA8d16O/7eLbYDh9d09zhtyufOnTT64XYaYZzfijUt/ZmmOOE76gGovVUd5LXyvjseA7MBrEIITq8x3dhXXunPgA1md8EyKpcQCiiXyiDAKJzu5CY4W57wsbQtVnefb4UTJ7XeGDSeYdXYAKHRxdPm02ujPFrhzmnuj9aoJ2uM25N9SAUf+lDJ/OEzE2MWjUN8QreKtto6d5g6IyDYfSZW0Ridbrwt/l5F4LCFLUU9N1v/oHnUsej1IXyeeXirEQJqrZDYEMQniKQ9iRcLzBcLSLqARUxqK65KiprwbAGfAWCKBHEfjitz4mRxYN7hE4LSQ8qAwJ3omlm4J16ES8LBgpgL07AouaCLKHDnJYFxNH6EMXfLsBdDJwKNMFcgEznCujVx32a31zemUngYLxYhh4tQ1osFwt/q0f1gkNqk4ndC/KEid1Z/A4HG20ffn6v04m1gU9uv0MQZ8aHnKGRcCJWJiF0+fsye4xptdzfA9tIcthQFt23Wm2RumGhl3oMJo338uNlBnbHnOrx7ojFbceB4HY/juwMS1C5cQeMgL1dEfqNqts4/PTxrtJWM2bDuKUIug4YzU6/peK5IpjFKiZz/hXDXUMSrtq8ZZMqVfn+ldMrJ34r9ikwUagLz0cW/rjkHfQ==)

**Comment by qmhc** [comment]
Is this helpful? [SFC](https://playground.vexipui.com/#eNrFVt1u2zYUfhXCHWoZSKQ128VgJEW2otty0a5IdlcXLiMd2UwpUqUo24GbB+pz9MX2HUqWZS8O3IthQBCT5+c7H885PNR68GtZxouaBuPBuaei1NLTy4kR4vyVNbmavXN2oTJyYlw6W1YXkwF+WZJBU1aTQTCG+e/WFWJc2Iw0jHLs3vB6MhDjmSwhOvsR67u68iq/x7YqZUqn0tnaZFBoeUv6VGo1M1B6W3bILfYV2DVW0L+1BXyYETZGFtSzhv2VKWsvki1AskF4AvP629f821dHJgXaBttRfgV6R4P/C77veW2XO8mo/L0mTpam1Vi82AnzGMN3Tq1ERmJBxvc4mrq4JceJRk45e7/wWs+a1Q4mUN8G6+YQqCmlqlKWvc7gtT3VgbQdQUwUyqhCcuV3CDL+/0jR1i4FPTkjZurkrVSVKOTqP6Q6ruo8Vyvs3siZQdsrM/tDywq35phjnCdomCPbrDvnDWlK/fZAVbvv4zY2YmxLD7J8p9sVzM6TRntsXJmyZx+dVTf1baG8uKzCLwLMpck0NWKQuyTnrOvkr3kXgm+d9yGvqSLfWjTrg7e7ETRTLNkdYxCeJ705h22VOlV6AcS6RBoNV9o3g00VpXVerIUjPueCxIPInS3EEBNzyN6dxV6FO8PLBa1UeVqrRKXIcHDihRdtzsWFeD/8K6zFi+GJ2KzPeuufhh82Xt1ghd+GVbR+GG30O9MZNmvOQka5rLUfNzshUk0SN0DTWHhX00kjlbW3qUVqyEORS11tNMhWSnOrkcCxGOIMQjwEFbPhxHfIjj7XylG26883aSzOfsZ24idezzDtzgLKxOBvYvLahD4S/T6JRmL9mDZ0S6s8T5ryoViDk0FTjSq+q6zBgxY4TTbSyQAsm4Cd6WkhyyesG/aTAarNe7Sr92U1TpLalJ9mMZKVQHXJvVT5JFP4h33sauNVQTFVxemts8uKHIJMBm02Al4C4YLcKd4bZJXH9+P4l4/Y7gTc0z0RtG3Egydp9bvHaYVx8ShWEp6wOOWR9h2oPa8Ocu+iHM7HjtkOrEIKVntMt/a1V/oI2GB2CHbTs2igQiqDBKNxuhmQ4kJ6wgfViZgfnhQK11RqvTVoI8OqtQFCq4uT9vNsq/x7TgXdLJVP551RT9Yab8bBNZU8KUIn83cSri+LhiE/YeTxRdrcXV87IyC4eCnm0TBTC8yg9/MIHEY4UtQLM/qAibO9v02wAt9yHtEahIDaKCQOBPESmbTLeDrFfjqFpEtYxKRGcV1R1KZnBHwGgCkKxCM8rs3SyfLK3OF5ouyaciDw+NozC0/Ln2FSOFgQc2EaFi0XdBEF7uwSGEfDZ1gPIQxnMbQUmJ6FApnIEfwWdILkcNj9g6kMEYbTaajhNLT1dBrmYzvjNRtkNq0LfHvEn2ty9837Chofn/2wVtnDx8CmsZ/je5MRv/cehYoLoXIRccjnzzly3KBdXATYXpnDkaIQdlP1tphbJlqZT2DCaF++bE/QVOy1RiNw4tiKE8d+vI4PJySoXXi3hkFezYn8VtUenX96eNZoKxmzZd1ThFoGDVem8el4zklmMVqJnP+N8EpRxF4newa5cpV/NVc64+KPYj8nE4WewH7w8A8fQ1vS)

I think this case you'd better specify `span` prop for each `FormItem` which are in the same column.

Or you can use nested `ConfigProvider`: [SFC](https://playground.vexipui.com/#eNq9Vm1v2zYQ/iuEO9Qy4Ehrtg+DkRTZim7Lh3ZFsm914TLSyWYqkSpF2Qlc/6D+jv6xPUfKtuzEgQsMBYKYvHvuuRcej1r2fq+qeN5Qb9Q7c1RWhXT0cqyFOHtldK6m76yZq4ysGFXWVPX5uIdflmTQVPW458GA/2lsKUalyagAKMfuDa/HPTGaygqi05+xvm1qp/J7bOtKpnQirWl0BkUhb6g4kYWaaiidqTbMLfclogso6N+aEjYcETZaltRBA3+pq8aJZEuQrBme4Lz69jX/9tWSTsG25raUXyK8o8kf0HctD1V0KbhcjB6JpUBh9Ej8NhTFFD9iJVY7/sFzZRY7Ra3dfUFc9ILuRuLFHvyxXN9ZdScyEnPSrpOtbsobsg/swfDWa0LqiJtSVSvDJ3UK620tDpb7qEBEqbQqJffMTkDw8QMjMo1NEY2cEgdm5Y1UtSjl3f8T2ahu8lzdYfdGTjWugtLTvwpZ4yYdG/VZggbo9lWy21hHduYm42sqKHXb1Op233URMGJkKodcuGnbFWBnSdAe61embNllZ9V1c1MqJy5q/wsHM6mzgoIYwV2QtcZu5K95551vjfcpr6gm1yLC+uBACIIw+B6W8yzpjEZs69SqygkwNhXKqKc8ssIsVGVlrMM1tsR5zgkXOLemFH0M2T5bbxB7DbABXszpTlUnjUpUigp7I1440dZcnIv3/X/8WrzoD8V6fdpZ/9L/sLbazGLYraOKlqvBWr8z0IFZchUyymVTOAykUKC0IIm7UNBIONvQMEhl40xqUBpyUOSyqNcaVCulmSlQwJHoIwchVl7VGXUBaelzoyxlu/ZhCp7+iu3YjR3PwhennmWs8TfWeaN9H4lun0QDsXxM67ulVZ4l4fhwWL1hL5xGHd/WRuMN9DGN19JxD1EGhxvoSSmrJ9Ah+nEPp817tKtzVT1KkkZXn6YxipVAdcG9VLskU/iHfWwb7VRJMdXlyY01i5osnIx7bTU8XwLhnOwJnihUlef04/wXj2B3HO7pnnDaNuLBTFr9bjqtMC4f5Ur8axWnPPG+g7VjtaHcuyiH67ED26FVKMHdXqRbfONUcQSthx2iXfcsGqiUSqPAaJzNDEhxIR3hG2woZocnhcI1lUWxBbSegWoxYGh1cdJ+0W2V/86opOuFculsA+rIWvB6HFxRxZPCdzJ/WuH6sqjv6+NHHl+k9d11jdUCgvOXYhb1MzXHDHo/ixDDAClFHTeDD5g42/sbnJX4/HPwFhg8a1BIJATxApU0i3gywX4ygWRTsIiDGsRNTVFbngH4mQBQHBCP8LjRCyurS32L54myK8rBwONrD+aflr/9pLBAEMfCYRi0nNdF5GNnEx9x1H+GdR9Cn4umhcD0LBWCiSzBbk5DFIfd7iemMnjoTyb+DCe+rScTPx/bGV8wIDNpU+IrJP7ckL0P7yvC+Pjsp6XKVh99NAE/wycqM37vPfInLoTKRcQunz9nz3FgOz/3tJ1j9ilF3u361NvD3EZSKP0JkTDbly/bDMKJvS7QCFw4RnHh2I7X8eGCeLX171bfy+sZkduq2tT5p8NndGEkc7ZRdxT+LL2GTybYbOKckcxitBJZ9wfhlaKIrYZ7gFzZ2r2aqSLjwx/EbkY68j2BfW/1H7omacM=)

**Comment by Extarys** [comment]
Thanks Chief! The second option works like a charm <3 Sorry for the trouble.
