### ISSUE TITLE
[Table] No work column sort

### ISSUE THREAD

**Issue by zlodey509** [vexip-ui/vexip-ui#387]
### Describe the bug

Columns which `sorter` object was declarated in <script> way no work but `sorter` object that was declarated in `TableColumn` way work correctly. I use @row-sort event in which I make request to server and get data. Also I noticed column that declarated in <script> has no `metaData` that has `TableColumn` sorter.
![image](https://github.com/vexip-ui/vexip-ui/assets/76591663/86b6c8b3-5161-4275-9600-2e502b9e059a)

### Reproduction

idk

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Could you provide a SFC showing how the sorter object doesn't work?

**Comment by zlodey509** [comment]
[Index .txt](https://github.com/vexip-ui/vexip-ui/files/11715105/Index.txt)

https://github.com/vexip-ui/vexip-ui/assets/76591663/bccaf989-5c09-4cbd-a89f-437fbc55aee0

**Comment by qmhc** [comment]
In your case, the `sorter` in TableColumn is a static object, so it won't trigger the componet update.

But the `sorter` object in `columns` prop is reactive object. And somewhere triggers the Table update, then columns will be re-parsed.

The paths maybe `columnSort` -> `column_filters` changed -> `watch` -> `getSubscriptionsByManager` -> `subscriptions_by_manager_data` changed.
