### ISSUE TITLE
[Collapse] Expanded CollapsePanel doesnt work

### ISSUE THREAD

**Issue by zlodey509** [vexip-ui/vexip-ui#389]
### Describe the bug

When I try to close panel in code by setting `expanded=false` its no closes
![image](https://github.com/vexip-ui/vexip-ui/assets/76591663/de65320b-fbc1-4300-b104-30569f61011e)
that how I bind Object.expanded with `CollapsePanel`

![image](https://github.com/vexip-ui/vexip-ui/assets/76591663/6d39feb9-a231-413a-b28b-4b743d9dfea0)

![image](https://github.com/vexip-ui/vexip-ui/assets/76591663/cd42aa5a-fdb0-47dd-b6e3-039a3e9f3c2e)
that where I try to close it

### Reproduction

idk

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Are you using `Collapse` component wrap those `CollapsePanel`? If so you should control `expanded` in `Collapse`, or remove it.

A simple [SFC](https://playground.vexipui.com/#eNqVVVFv2zYQ/iucOtQyYMvdw148O8haDFjfiqZv06Bq0tliQ5EcRdkOXP/3fUfJlpzVRQokjnn33Xd33x2ZY/S7tcmupWgZrTzVVuWe7lItxOqdUSq3DX3INSmxm9emJLWkg811SeU6jc5f00h46RXB9B5nS/jQXnRxv8CbO2f2c/9kGaJo49MopEASe/dgahKF0Z5jvBEbqdRqYV8GWC2uqgw2/j0exbk6cTqdrau3rfdGi/tCyeJx1IFYi5+GbvrUn8x2q6jL0gXCsVqMRMKxKZy0XjTkWytUrrdg9U3gkLU1zoujcLQRJ7FxphYTKD3hQPTT+KHGNYPiTa4amnKSjrZP4Z8UiaYwlkpYkt3Bzou+6ywDAVQ+cpl1fpjvZemrpfj1zRt7+C3VaB1kTIDIaBZ1NTXJl8ZoTDyEpWdrGi3FERH4uUDndW6/g+6USiO0xec0qry3zXKxaLV93CaFqRdw3bNejV+UEh84J67VXtaUUFPP/8FuNOSQJI1mI74FjDtyc8fr5Mjd4r//BvYq4TPfd5LSQdp5K2920vuv2+mNSf1Nrk78pGiCXi9mHUVdKO8vnJK357YeV7ArWgkJDs8qHfCtl+oFtAF2i5ZZeYWwQHUuNQTG4lxuQuEIYXhxZqL635W4oCSuRq7UAOgzA9VjwND7kkX/fg3OTxXV9LCXvqguoJGtB5+v4EeyCtcvbLLOa1qKCZsmQZ9wrePpec8djk4LGNZ3ooonpdxNZuKvKkYNU7QUj9JM/8ZF7rQYktUGi49sHUNg7Rw5GoJ5DyXNPskynLMMlotgMRc1TdqG4l6eKfiZAFAMSG/kNmn13uX2vf5ChafyI56dtfAOV/MaRniO3Z94eBQ5IIhr4TIMVi74Yn6EupBQcTx5he8TGEMvmvbiA4SVKCZ2hLgdzSAOp33emOS3bZJlYYZZWOssg/xnv1EMKE3R1njek39bck8PpMCEMj6/+vkoy9PnUE2Hr/gxBeOP3qMwcSHkRsSc8vVrzpx0bOt1oB2NObQUh7TnqffDHCpRUj+iEmb7+nXooJvYHwqLwMIxioXjOP6e3BYkuB0ec/iDvamI/ODqW+c/Iz6jlcm7fyCh6pEjzDJ4eDJdzKXOivIywSqR829pYxzFHDV7BthI1/h3lVQlD3+a+Ip0HHYC5+j0Hw343DA=) for testing CollapsePanel expanded.

**Comment by zlodey509** [comment]
But which `CollapsePanel` event on open/close panel I need to use? In docs no info about this

**Comment by zlodey509** [comment]
What about this issue??

**Comment by qmhc** [comment]
You can use `toggle` event or watch the `expanded` changes.
