### ISSUE TITLE
ES 的打包产物缺少 Confirm 组件的样式文件

### ISSUE THREAD

**Issue by ihola777** [vexip-ui/vexip-ui#392]
### Description

使用默认代码，调用的Confirm弹出框位置在屏幕左侧，修改哪个property可以放到屏幕中央？尝试了自定义class，不起作用。
需要覆写组件的样式吗？

外层使用的tailwindcss
```
import { Confirm, Message } from 'vexip-ui'
const confirm = async () => {
    const isConfirm = await Confirm.open({
        title: '提示',
        content: '是否同意用户协议并注册账号?',
        contentAlign: 'center',
        actionAlign: 'center',
        confirmType: 'primary'
    })
    if (isConfirm) {
        Message.success('已注册')
    } else {
        Message.warning('已取消')
    }
}
```
![图片](https://github.com/vexip-ui/vexip-ui/assets/38958623/828066da-442c-4789-8bdb-5b414e2e8920)

### Validations

- [X] Ensure this issue neither a bug report nor a feature proposal.
- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that descript the same thing to avoid creating a duplicate.

**Comment by qmhc** [comment]
你的截图看上去似乎是样式没有生效，或者你是否修改了一些其他内容？单一个截图我难以分析原因。你可以尝试一下是否能在 (Playground)[https://playground.vexipui.com/] 中复现。

**Comment by ihola777** [comment]
> 你的截图看上去似乎是样式没有生效，或者你是否修改了一些其他内容？
> 
> 单一个截图我难以分析原因，你可以尝试一下是否能在 [Playground](https://playground.vexipui.com/) 中复现。

根据快速上手那一章的自动导入样式的配置会有问题，重新在main.ts里面引入样式就ok了。
```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import { createStyleImportPlugin } from 'vite-plugin-style-import'

export default defineConfig({
  plugins: [
    vue(),
    createStyleImportPlugin({
      include: ['**/*.ts', '**/*.vue'],
      libs: [
        {
          libraryName: 'vexip-ui',
          esModule: true,
          // 引入暗黑模式基础样式
          // base: 'vexip-ui/es/css/dark',
          resolveStyle: name => `vexip-ui/es/css/${name}`
        }
      ]
    })
  ]
})

```

**Comment by qmhc** [comment]
经测试，在最新版组件库不存在这个问题。
