### ISSUE TITLE
How to custom scss variables in Nuxt3?

### ISSUE THREAD

**Issue by lmy1991** [vexip-ui/vexip-ui#402]
### Description

使用https://www.vexipui.com/zh-CN/guide/style-config.html#%E9%80%9A%E8%BF%87-sass-%E4%BF%AE%E6%94%B9 的按需引入并没有生效

### Suggested solution

比如可以通过```@vexip-ui/nuxt```设置全局变量实现

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that request the same feature to avoid creating a duplicate.

**Comment by qmhc** [comment]
在 Nuxt 中，你需要通过 `nuxt.config.ts` 中的 `vite` 属性更改 Vite 配置。

下面是一个简单的配置实例（假设你的变量文件为 `@/style/variables.scss`）：

```ts
const vxpStylePresetRE = /vexip-ui\/style(?:\/dark)?\/preset/

export default defineNuxtConfig({
  modules: [
    '@vexip-ui/nuxt'
  ],
  vexipUI: {
    importStyle: 'sass',
    importDarkTheme: true
  },
  vite: {
    css: {
      preprocessorOptions: {
        scss: {
          additionalData: (code: string, path: string) => {
            return vxpStylePresetRE.test(path)
              ? code.replace('@use \'./design/variables.scss\' as *;', '@use \'@/style/variables.scss\' as *;')
              : code
          }
        }
      }
    }
  }
})
```

**Comment by lmy1991** [comment]
之前没有配置
```
vexipUI: {
    importStyle: 'sass',
    importDarkTheme: true
  }
```
但是加上之后就会报错，如下图
![image](https://github.com/vexip-ui/vexip-ui/assets/12825728/1f7b62a5-8187-44ff-80dc-53ed468c5721)

**Comment by qmhc** [comment]
请确保 `additionalData` 中执行的内容替换仅在预设样式 `preset.scss` 中。

**Comment by lmy1991** [comment]
可以了。谢谢。
是我代码需要```@import```，改成```@use```之后就行了。
