### ISSUE TITLE
Slider component does not support decimal points

### ISSUE THREAD

**Issue by lmy1991** [vexip-ui/vexip-ui#405]
### Describe the bug

如题。
还有建议Slider加个插槽，用于自定义滑块，最好返回value
![image](https://github.com/vexip-ui/vexip-ui/assets/12825728/23aa149a-a6e2-481f-a673-b4c2e42cbe34)

### Reproduction

https://playground.vexipui.com/#eNp9VNtu2zgQ/RVCXVQU4NApuvti2MZuiwDdojc0easLVZXGFhOKZEnKduD43zscXeymF8CwxZnDmTNnjnVIvCun/1krti0ks2QeoLGqCLBcacbm10pW4OIjY9uLxlSgZttCtbBYJfS7SrrkrJEaY89O52Ifz5djwAewGLkUI8aHexULIfRiJ6tQz9jfl5d23+WX82nXnZgcDtTueFzp+fSMIx596aQNzENoLVOF3mDJ4FcJZmVjjQvswBys2ZGtnWlYioOm8WJptA+MyrJFRMx123zFfvyZ+CeLfbrKy2SSdIUumsKKW280CnWIrFZ9ArvN2AG54QfRwWPttdw8wpamsVKBe2+DxN50p1NilRRKmd1rigXXwmSIlzWUd7+I33qUaYYP1oEHt8VFjLlQuA2ELn11/Q72+DwmcYetQvQfkh/BG9VGjh3sRasrpH2GI7b/0+hSb2781T6A9sNQPxAN9xYo+gkdA3tpL1o5paCoRBTuc0QeCY+IFl7+QaXTZM/Fc7o3SB5d3BRSY0kUfNx76QB9gvaesPonA4woiUbAkU6AnieiegxW6HNi+LOckjc1NHC9k6GsR9BZrAcPhvsIVqHfaCZdNDBjaQylpACZmGfDxA6PTjMMLJas5mklt+mEfao5cshwJH7WJvuMnh0UGZo1ptUBu3UVqGqXKHAgDPOd1JXZscKzQt9nIs8xkeeYGpXjkV0mWg+81ynDRrESQkVvdHDOuFcF+QQv4x9qSY2Mgi7HgdjFK8SJp0/wOcUgsdWwYx9QOulhvjWyWnKOvjZqCxMU4RbK8HgAWWGfNM9pVzm9SvIcZR7yRkVAZcq2AR3Etxbc/TUorIRkvjz56yCr45csDv7q5u2bN1LfXSnUEtV6YLpV6lSpji8P7FWHYP1sOm21vdvg4M108Mm/8WXkw7SS+EVUROk97ZwxuWY8knn6NHISXbXFgsqeLZqG5STSsPd+nScmClkik1jt4eE0W7eqnj5PIyoKG+/FZ/F7qSjtIPoxpbivAcIp1Y8ef87qGa1MEWt2rvqBew+gndNbNe6uuzvyraGoBHoJXHgBa+OAx1uTR4C1dD68rKWqokkyEWrQnLyD5+T4HS4QQmM=

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lmy1991** [comment]
大佬啥时候可以发个新版修复。项目快上线了。

**Comment by qmhc** [comment]
计划在明天晚上发版，希望没有影响到你的项目上线。

**Comment by lmy1991** [comment]
非常完美。感谢
