### ISSUE TITLE
[Tree] Split single node slot into label, prefix and suffix?

### ISSUE THREAD

**Issue by shaoerkuai** [vexip-ui/vexip-ui#409]
### Description

![image](https://github.com/vexip-ui/vexip-ui/assets/117460332/667450f2-15d9-4795-87c0-0c36851b5f83)

我最近在做一个文件树，参考了一下NaiveUI给出的一个案例：
![image](https://github.com/vexip-ui/vexip-ui/assets/117460332/28728dc9-31d9-47d7-beba-f6d0636830bb)
![image](https://github.com/vexip-ui/vexip-ui/assets/117460332/e34bd1ab-8ccd-49e2-851e-23ae3f237163)

它是通过修改每个node的prefix实现文件夹的展开和收起图标切换的，看了一下vexip-ui的设计，似乎目前只能完全重写node插槽，才能动态修改icon，但我可能只是保持label不变，改一下整个节点的前缀，因此，是不是将node插槽拆成三个部分：prefix、label、suffix更好一些？

添加前后缀时，也不需要再多补样式了，整个插槽完全重写感觉会有样式问题，需要补下样式，哈哈

至于添加suffix的建议，如果是对于资源类的树，后缀可能需要表示“资源可用性”之类的，如下：
![image](https://github.com/vexip-ui/vexip-ui/assets/117460332/7aa70116-1ccb-4031-b6be-213f57b40dfc)

### Suggested solution

Split single node slot into 3 different-postion slots.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that request the same feature to avoid creating a duplicate.

**Comment by qmhc** [comment]
其实你通过 `label` 插槽可以做到你描述的功能，不过需要自己分割内容😂。
