### ISSUE TITLE
Add Option to place the select component's filter input on top of the option list instead of current control position. 

### ISSUE THREAD

**Issue by johnson0903** [vexip-ui/vexip-ui#416]
### Description

Due to my belief that placing the input field on top of the label displaying the selected item doesn't clearly indicate the filter functionality to the users, is it possible to add a feature to position the input above the options, or can this actually be achieved by combining the existing components of vexip-ui?

由於我認為將輸入框放在原本顯示所選項目的 label 上，無法很明確的讓使用者看到過濾功能，是否可以加入將 input 放到選項上方的功能，或是其實可以透過組合 vexip-ui 現有的 component 就能達到呢?

### Suggested solution

Add a props so that user can decide where to display the filter input

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that request the same feature to avoid creating a duplicate.

**Comment by johnson0903** [comment]
I saw that the select component added a prepend slot in v2.2.7. Maybe I can achieve it through this feature.

我看到 select 元件在 v2.2.7 加入了 prepend slot, 也許我可以透過這個功能達成

**Comment by qmhc** [comment]
@johnson0903 你好，這個功能大機率最終會加入正式的特性中，目前我正在考慮關於它的實現方式。

使用即將在 `v2.2.7` 加入的新插槽可以實現該功能，但需要使用者在 `Select` 外部自行完成選項的所有過濾邏輯，並且不容易確保其能和 `Select` 內部的選項屬性一起良好地工作。
