### ISSUE TITLE
When using this package, the browser generates a large number of network requests

### ISSUE THREAD

**Issue by johnson0903** [vexip-ui/vexip-ui#418]
### Describe the bug

我發現當使用套件時瀏覽器異常卡頓，透過 devtool 可看到套件不斷產生大量對套件路徑的 reqeust
似乎在 dev mode 才會產生此問題，瀏覽官方文件時不會發生

### Reproduction

https://playground.vexipui.com/?vexip-ui=2.2.5&vue=3.3.4&typescript=5.2.2#eNp9VO2O0zoQfRXfcEUcqTgS6P6ptivuohUL4kvsSvygKETJtPGuYwfbabfq9t2ZsZO0rACpUp2ZMzNnjk+yT5yt8v+7Tmx6SObJmYe2U6WH86Vm7KyWm3DA40XvvdHM7zpYLJPOyra0u2XC5rIyGiPvy7WWq53U69eqdG6ZDIWM7fesdWt2OAyd8tgqTsjjiLP8ZDA+usrKzjMHvu+YKvUaJ/jYVLadsZ7tmYUVO7CVNS1LkX1KhVPyEZ0J+HID97J71suceLtQRAcfOC6oKU+vQCnDvhir6n/SjNhFPjg9mSVxxrO27MStMxpV29MqyyGBLOdsj8viD9HeYfuVXD/CVqbtpAL7sfMSx4eaqM8yKXH69m2IedvDbIxXDVR3v4nfunuK0a2AA7uBZTLlfGnX4GP68voD3ON5Sram7hWi/5L8DM6onjhG2EWva6R9ggts34TVUe0bd3nvQbtxqV+IknlC9Osyme4hBEUtSLhvhDwEPCJ6ePUXlY6bvRAvQt0oOVm6LaXGlij4ZInKAvoLvT5jzZ+NI9ELuNIRMPBE1IDBDkNOjG/OMXnTQAvXW+mrZgKdxAbw6LnP0Ck0XdhJly3MWUqhNCgQzM+zcWOLj1YzDCzOWcNTfHHSGfvacOSQ4Ur8ZEz2DV07KjIZ3PTa47TYIXSNiRIXwjDfSl2bLSsdK/UuE0WBiaLA1KQcJ3aZ6B3wQacMB1EnhIrB6GCtsVdl8AkWA02jQUZBzHEI7KgkcOLpEzzTixbYatiyTyiddHC2MbI+5xx9bdQGZijCLVT+8QKyxjlpUYS7KpzfKSgKlHnMG0WA2lR9C9qLHz3Y3TUo7IRkvj/5dy/rw/eMFr+6ef/undR3lwq1RLUemO6VOnZq6KODsxrvOzfP8153d2tcvM1Hn7x8Lp6L//Cz5nwemIjKxc8MY3LFOHF5+pQoidhssQhdT+457MqDRuO1D7d5JKKQJBKhbg8Px9XiTQ3seUoo0pXq6Cz+rFRIWyA7piHuGgB/TA2b099JP6OVKalnNNUv3AdAuPLwZaWri7UT3wbKWqCVwPoLWBkLnKpmjwAraZ1/1UhVk0cy4RvQPFgHn5PDT0ujSZI=

### Steps to reproduce

這是文件提供的範例檔案，打開 devtool 切換到 Nextwork 可看到大量零碎的 request

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
在 Playground 中的請求裡大部分是請求 `.d.ts` 的類型文件，用於為編輯器提供類型提示。

在開發環境中，如果你使用的是 Vite，我猜應該是圖標庫（`@vexip-ui/icons`）引起的大量請求，你可以在配置的 `optimizeDeps.include` 選項中指定它：

```ts
export default defineConfig({
  optimizeDeps: {
    include: ['@vexip-ui/icons']
  }
})
```

**Comment by johnson0903** [comment]
感謝你的回覆，使用 `optimizeDeps.include` 確實減少大量的 request,
在開發環境中，我還有看到其他來自我沒有使用的 component 的引用請求，
是否是因為 Nuxt module 載入所有 component，這在生產環境中會被 tree-shake 掉嗎?

**Comment by qmhc** [comment]
> 在開發環境中，我還有看到其他來自我沒有使用的 component 的引用請求，

一些 component 會依賴其他的 component。

> 這在生產環境中會被 tree-shake 掉嗎?

會的。

**Comment by johnson0903** [comment]
感謝回答，但在我的 Nuxt 3專案中我只用了 collapseTransition 的元件，卻會發送將近 500 個和 vexip 相關的 request
這樣是正常的嗎?
![image](https://github.com/vexip-ui/vexip-ui/assets/16976349/daede610-74cf-40d8-ae1c-bb2db367905b)

**Comment by qmhc** [comment]
在 `optimizeDeps.include`  中加上 `vexip-ui` 即可 😂

**Comment by johnson0903** [comment]
感謝你的回覆與調整，我關閉此 issue

**Comment by johnson0903** [comment]
感謝你的回覆與調整，我關閉此 issue
