### ISSUE TITLE
about Nuxt , install template 

### ISSUE THREAD

**Issue by hangxingfu** [vexip-ui/vexip-ui#420]
### Description

Hi, I saw the command on the official website
yarn create vexip --template nuxt

<img width="998" alt="image" src="https://github.com/vexip-ui/vexip-ui/assets/38324705/48981cac-939e-4641-988a-8d1ee911711d">

Update dependencies version?  => this options , yes or no , both are mistakes

node: 18.16.1
yarn: 3.2.4

Thanks

### Validations

- [X] Ensure this issue neither a bug report nor a feature proposal.
- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that descript the same thing to avoid creating a duplicate.

**Comment by qmhc** [comment]
It's fixed in latest (create-vexip) version.
