### ISSUE TITLE
Tree suffix & prefix could be parts of Data[] using h() function

### ISSUE THREAD

**Issue by shaoerkuai** [vexip-ui/vexip-ui#440]
### Description

Vue提供了h函数用以动态创建VNode
当前Tree的prefix和suffix是通过template声明的，对应统一后缀的场景下，当前的设计是OK的
```
<template>
  <TestTree :data="data">
    <template #prefix>
      <TestIcon :icon="TestPaperTestPlaneR"></TestIcon>
    </template>
    <template #suffix>
      <TestLinker type="primary" @click.stop>
        Suffix
      </TestLinker>
    </template>
  </TestTree>
</template>
```
如果只用模板插槽的话，可能自由度还有一点受限，希望可以有更高的灵活度，比如说，某个data数组里面的元素prefix和suffix是动态处理的，这时候可以借助h函数来创建，参考如下：

### Suggested solution

Data类型数据类型声明，可增加prefix、suffix属性，传入h函数，例如naive ui的：
```
      data: [
        {
          key: "文件夹",
          label: "文件夹",
          prefix: () => h(NIcon, null, {
            default: () => h(Folder)
          })]
```

这个案例下，data内的prefix通过h函数创建，是一个icon。

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that request the same feature to avoid creating a duplicate.

**Comment by qmhc** [comment]
好的，我将关闭这个 issue。
