### ISSUE TITLE
Tree貌似树的结构解析和视图渲染有点问题

### ISSUE THREAD

**Issue by shaoerkuai** [vexip-ui/vexip-ui#442]
### Describe the bug

参考以下测试数据
```
const data = [
  {
    id: 1,
    label: "父类文件夹",
    parent: 0,
    type: "folder",
    expanded: true
  },
  {
    id: 2,
    label: "main.py",
    type: ".py",
    parent: 1,
  },
  {
    id: 3,
    label: "data.json",
    type: ".json",
    parent: 1,
  },
  {
    id: 4,
    label: "测试文件夹",
    parent: 1,
    type: "folder",
    expanded: true
  },
  {
    id: 5,
    label: "common5文件夹",
    type: "folder",
    parent: 4
  }, {
    id: 6,
    label: "common6文件夹",
    type: "folder",
    parent: 5
  }, {
    id: 7,
    label: "common7文件夹",
    type: "folder",
    parent: 6
  }, {
    id: 8,
    label: "common8文件夹",
    type: "folder",
    expanded: true,
    parent: 7
  },
  {
    id: 9,
    label: "common9.py",
    type: ".py",
    parent: 8
  },
  {
    id: 10,
    label: "common.py",
    type: ".py",
    parent: 5
  }
]
```

在模板中这样使用，：
```
  <Tree :data="data" :link-line="fileTreeLink">
    <template v-slot:prefix="prefixSlot">
      <file-icon :icon-id="prefixSlot.node.data.type" :folder-expanded="prefixSlot.node.expanded"></file-icon>
    </template>
  </Tree>
```

然后展开到common7文件夹时，渲染就不正常了：folder图标渲染成了python图标。

我的file-icon组件是通过拿type来判断的，上面的data是folder，但是渲染出来的疑似`prefixSlot.node.data.type`变成了.py，
从tree组件拿的节点数据错了：
![image](https://github.com/vexip-ui/vexip-ui/assets/117460332/72983ae7-19e3-444a-8393-02d85e7ad6ed)

如果进一步展开common7，更有意思了：
![image](https://github.com/vexip-ui/vexip-ui/assets/117460332/2e783855-8c57-41b7-a512-b8ca17478c09)

link-line渲染也错位了（common7图标恢复，应该是因为我有一个watch props，重新展开以后这里type又传对了？），说明应该是vexipTree处理tree的树结构时可能有些问题？
我仔细看了下，目前唯一的硬性条件：parent有效和id唯一，测试数据应该是满足的。
这个方便帮忙定位下不？
（公司这边进不去webide，上面的代码去掉file-icon应该也可以直接用的。）

### Reproduction

/

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
连接线问题已修复，将在下一个补丁版本发布。

关于 `prefix` 渲染不正确的问题，如果有新的信息可以确认是组件的问题，可以重新打开这个 issue。

**Comment by qmhc** [comment]
你的 `FileIcon.vue` 存在问题。

有两点需要注意的：

1. 如果你不使用响应式变量，你应该将计算使用哪种图标组件的过程放进渲染函数中，以确保正确的依赖收集：

```ts
export default {
  props: ['iconId', 'folderExpanded'],
  setup(props) {
    return () => {
      let fileIconRef

      switch (props.iconId) {
        case undefined:
          break
        case ".py":
          fileIconRef = VscodeIconsFileTypePython
          break
        case ".json":
          fileIconRef = VscodeIconsFileTypeJson5
          break
        case "folder":
          if (props.folderExpanded) {
            fileIconRef = VscodeIconsDefaultFolderOpened
          } else {
            fileIconRef = VscodeIconsDefaultFolder
          }
          break
        // 未知文件类型？
        default:
          fileIconRef = VscodeIconsDefaultFile
      }

      return h(fileIconRef)
    }
  }
}
```

2. 如果使用响应式变量，`ref` 的定义应该使用 `const`，并且使用通过 `.value` 来修改里面的值：

> 你这里可以使用 `computed`，当然使用 `ref` + `watch` 也可以。

```ts
export default {
  props: ['iconId', 'folderExpanded'],
  setup(props) {
    const fileIconRef = computed(() => {
      switch (props.iconId) {
        case undefined:
          return undefined
        case ".py":
          return VscodeIconsFileTypePython
        case ".json":
          return VscodeIconsFileTypeJson5
        case "folder":
          if (props.folderExpanded) {
            return VscodeIconsDefaultFolderOpened
          } else {
            return VscodeIconsDefaultFolder
          }
        // 未知文件类型？
        default:
          return VscodeIconsDefaultFile
      }
    })

    return () => fileIconRef.value && h(fileIconRef.value)
  }
}
```

如果使用 `ref` + `watch`，`fileIconRef` 会变成像这样：

```ts
const fileIconRef = ref()
watch(
  [() => props.iconId, () => props.folderExpanded],
  () => {
    switch (props.iconId) {
      case undefined:
        fileIconRef.value = undefined
        break
      case ".py":
        fileIconRef.value = VscodeIconsFileTypePython
        break
      case ".json":
        fileIconRef.value = VscodeIconsFileTypeJson5
        break
      case "folder":
        if (props.folderExpanded) {
          fileIconRef.value = VscodeIconsDefaultFolderOpened
        } else {
          fileIconRef.value = VscodeIconsDefaultFolder
        }
        break
      // 未知文件类型？
      default:
        fileIconRef.value = VscodeIconsDefaultFile
    }
  }
)
```

**Comment by qmhc** [comment]
连接线在最新版下已经是正常状态，请确保你成功更新了版本。

![image](https://github.com/vexip-ui/vexip-ui/assets/40221744/4b1c937d-5d27-4385-b7fe-974bb61ae0ce)

可以在 [Playground](https://playground.vexipui.com/#eNqdVdtu20YQ/ZUFXYQUIFNNHV8iWEabwEBapBfEfjMDhSVH4trLXXZ3qQtkPbdAn9sv6HvRhwYo8jtt0s/o7C4pUZScOjEMm5w5e2bmzHB24SmZ9L4oinBSgtf3TlUiaaGJAl0WhMV8PIg8rSLvLOKJ4EqTNNYxGZCriC8iTvCHpn3ysOueWfw9sD6JvHc/vX73x5u3v/7495vX//z2V+RVgCKWwHWffFq963kBBj8SLAW5gsGsiHkKyKxlCca2tJ5GyM/aIfOY8rCYrzhq6qatDu/y3eI8aHOaYsNrJfg264b1f3gftXnf/vnzv7//crc8tZ4fL89hO2Qi8lzww+2Yd8SoU3nk6JvcR7u5jz6Y+3Cb+3g39/EHcx9tc5/s5j65N/em7q2Axzv78Hh3zMf3ndSTnawP6++nRXtfVid8xF9G/LTnPnn8wPFFQ16wWAO+EXJ6KQFI33wEuAXMv8gjjPKbffzjIAiqj5C9QsKIzhC6cFtiadeGAWHyzhaarMgSQ9uzvc14PRMQHzfsXtejeSGk3s/jwn52uKesFlHlwPXUJwvkxF9Ea4WbakTHLSwqVFAG8ttCU9xk9oxLI/JixsT0K2trdBbPZJDc7LBfq5mxRR6WrEBOYKUwbstYjkE79/nFNzDD55UzF2nJEP0e5wtQgpUmRwd7UvIU027gbLZf2tIpH1+q85kGruqiNhI1clvrVeRNYEaL/ZL2rDFMQyMcTkA9X4go4el7VFpXdhAeVBPkJDeXiN2/WqHgritkQRIJ2EO8XbokI0sykiInPgbxzaytUBSvFSxpDajyRFSFQYbKF9Z31dp5mUEOF1Oqk2wFatgqcH19vYCC4fVla+Jxjl+Ib0y+VcDeekGnrljiq+QEDYMzkgV+Sid+l1xlAebQwZKCRpjOy85akTpYLkquMZpjsKzOEWNBaA6mlKdiSmJFYj7vhMMhOoZDdK2UC0x2nbBUEFQ6dTCQYUJoWA06SCnkM1xN2Dg8DCaaCSQYOF8ANjtzxOYU+Hv47KPRZsthSr5D6aiC04mg6VkQ4FwLNoEuinANiW4XQFOM4w+HtldDpecMhkOUufbj3kRAKpIyx4UT/lCCnF8AQyZM5tXeJwuaLl91TOHPLr9+/hx3yjlDLVGtW8JLxtZMGS4VEyvTulD9Xq/kxc0YC8979Zx8bhaF0r2U4h+bSpgoZXuO23JEApPMgwcmp9CxDQaWttFoW2xgRar7XrVznYnZfJiJYbu9XdfmWlWlH/gGZYQ158xzeLdU1i3BzKNv7SoD0GtXVbr51+ATnInYcLqp2si9AtieI8L1zp1d5ZtBnIY4SyD1ExgJCYE51W0BRlQq/TSjLDVD0gl1Bjyws4Pv3vI/cDFiZQ==) 查看。
