### ISSUE TITLE
[Select]: Wrong kind of value passed to 'selected' slot

### ISSUE THREAD

**Issue by Nalca** [vexip-ui/vexip-ui#445]
### Describe the bug

For the component **Select**, The **selected** slot sometimes received an unexpected type.

According to the [documentation](https://www.vexipui.com/en-US/component/select.html#select-slots), both the **select** and **default** slot should receive a **SelectOptionState** object for *option*, and only that.

Yet, for the **default** slot, sometimes the *value* (a string / number) is received instead of the **SelectOptionState** (which is an object)

### Reproduction

https://playground.vexipui.com/#eNqVVW1P40YQ/isjHzrbUrChtF/SEF1BSNeWvujgG0bBZ0/ihfWuu7tOQCH/vbO7tvMCRaqEyHrmmZln3nbXgVZF+kvTJMsWg3EwMVg3PDc4zQTApGRLd6BjM71BjoWZpE0v8gIYy8YwKfR5FnSnLIC65YY1HGFc58/HJl8cF7IVhjCnJ1nQeSAffTz4pJ03LAmyBu8INjtQgPUa5lLVuYm8egRhbxTGsNkMTtO9LA7ilDjPidz/CtPZfBxlkvqC9J/fFaTT7mco4rVcDA4uWmMo+peCs+KJ+MwKKQwKk+iGJBidxMTrkmOugMvFJPX4IdrQh1t8NrnCHJbHtSyRj5c5b5Ecdv6oHWMlV7ZBpz/Rh6czSX139/KgT10o1hjQaNoGeC4WZGaopaRldSOVgTX85QrzO75cSjFnC9jAXMkawiU+s+a4ZeHPO+BC1k1LPdqiWtwDKJzv6SwNoq5N1x8N5xYzOYh6dz+N7mwma3AJjyELfsiCEZH+TkWgL28AJITN6AB59h6ShG+RP76HJKFD3seUSSbmrSicfG9yxpCLlxFo2aqCXGmjmFjE/QHWNpBPtEat8wVSog9Ha4/fjOBofeOQnbt480DBvInkmNBQRJ2hZQEwDJDjnrRCV2xuPsR0o3Z6cnLi9Yr6rgTsByYNzX3fld5F1xafjeuGq4YHbTF9/6MohvPpIYFHyUQUZpkIY2s8Sf380bQFo8CPyHGdN8mjloIuKFezrFPQVI5hTczoj9BGk2sajAOsjc84Kt85b+M3JwtyzuXqNyczqkXXemdTYfH0jvxRP1tZFjQKNaol0mz0OtrBBdKyWfXVzZ+0lDtKWsyWE/oD5TekrraWo4ddtKIk2js4x/ZXlzpV/FZfPVMhdZ/UHlHz0qCT3mVBv5WpEyZlYgt3b5F+1gnR4uUHVdpmdpacObu+5Pb1qHMmyCUVfLvydBsZpGdlBNWb1R5QjOaEUnp7ewwY8tDpkv6R2ipvK6zxZsVMUQ2gHVkH7ufxGzachtHlJPKa1jG0otBVwF12NJ5dxt0O+HmtopAuynAEd1VEHGJKKdoJE9/H24r0wWr71lE072Fnz3NKiMTRiolSriDX9oaIk9mMFLOZXZa+cpFlFyetxqirU0yBrCeCJt2go1JSfc3dnJAx3R/T4XZwuggdO2viOEXhJzqHJHRsBa7gbyod0zhZSlZOo4jmWvIljqgIj/SYHSbASooTzmauVzNtXjjOZlTmXi+5BZSyaGu74/+0qF78s0hkHj4drVm5eYht4l9v/7i+ZuLpilMtqVqvIFrOt54q+yxQrMqYRo/TtBXN04ISr9N+Tr7YR0sbesfon6OSFFq7ngOwOUSWzOfPllPivZ2fO7c7jXbJRq5Ifd+7dm6ZcGJJTKy319dtbr5VHf0otChbWGtnz8l/l8qpFdp5DJ1cV4hmq+pStz87/qTgMrc+/VTtce8ArufuWra987YD3wrzMqFZQmUukN4pjKzV6AAwZ0qby4rx0g5JnJgKReRmh76Dzb/CH2us

### Steps to reproduce

Using the playground link :
 - Select an option
 - Read the log, you should always read 

 > [object Object]  // (I pass the value directly to the String constructor, so it's expected).

<br />

Once an option is selected, you should see a line like

> selected, 3

This should not happen, since we expect an object and not a string / number.
Also, the number of message logged is really important considering there is only 3 options in the select. Maybe a cache should be considered.

### System Info

```shell
Vexip UI: 2.2.17
Vue: 3.3.10
TypeScript: 5.2.2

Browser : Firefox 120
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Thanks for your report, there patches will be released in the next two days。
