### ISSUE TITLE
[Feature Request] tag 可否为prefix、suffix增加undivied属性，以选择性隐藏分隔符？

### ISSUE THREAD

**Issue by shaoerkuai** [vexip-ui/vexip-ui#446]
### Description

![image](https://github.com/vexip-ui/vexip-ui/assets/117460332/0a8eb2b7-98c3-4996-9bd6-bb8faa364cb7)

需求：
设置标签prefix、suffix后，会有一个分隔符。
有时候希望不显示该分隔符，但仍能使用suffix、prefix属性表达标签前缀，期望tag能提供一个boolean属性，设置为false时，则不显示分隔符。

当前做过的尝试是：

我试着去除.vxp-tag__unit的border，发现整个所有的边框都没了，所以这个分隔符相当于是标签单元都带了一个，我这边自己实现似乎不太好比较优雅的处理。
目前我这么搞，给border都设置成0px：
![image](https://github.com/vexip-ui/vexip-ui/assets/117460332/51a95695-3329-470f-85a7-563da9739b1e)

😂有点奇怪

### Suggested solution

根据undivided的值，增加tag节点tag-unit的样式vxp-tag__undivided，设置border-left、border-right为0px
但可能需要调整下元素的间距

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that request the same feature to avoid creating a duplicate.

**Comment by qmhc** [comment]
这个功能主要是用于标签内有明显区域划分，我觉得如果单纯放个图标你应该不是希望图标和内容有明显的间隔，而是挨在一起。
