### ISSUE TITLE
Alert、Reslut、Timeline 增加独立的 `info` 类型

### ISSUE THREAD

**Issue by shaoerkuai** [vexip-ui/vexip-ui#449]
### Description

![image](https://github.com/vexip-ui/vexip-ui/assets/117460332/45c76ce3-a7ee-4872-9de7-7c4fc039bd8c)

如果主题色是红色，似乎就没法用蓝色的Alert了。。。

个人觉得可以加一个布尔prop，是否以主题色渲染info类型，默认是true以兼容已有项目，为false则以默认的info渲染颜色？

### Validations

- [X] Ensure this issue neither a bug report nor a feature proposal.
- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that descript the same thing to avoid creating a duplicate.

**Comment by qmhc** [comment]
或许添加一个 `color` 属性支持自定义颜色会是更好的选择，就像 Button 和 Tag 那样。

因为主题色并不是一个内置的固定值。

**Comment by qmhc** [comment]
已在 b31d239 5ac3055 0bce250 7845ce2 和 84d0b85 中更新，随下个版本发布。
