### ISSUE TITLE
Image组件Bug

### ISSUE THREAD

**Issue by whenTheMorningDark** [vexip-ui/vexip-ui#459]
### Describe the bug

1.点击预览image图片
2.滚动鼠标滚轮把图片缩到最小
3.随意拖拽一下图片
4.再次滚轮放大图片，发现图片已不在屏幕内了。

### Reproduction

https://www.vexipui.com/zh-CN/component/image.html

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
再次放大的时候你的鼠标是否停留在比较远的地方呢？缩放是会以当前鼠标所在位置为中心点进行放大的。

**Comment by whenTheMorningDark** [comment]
> 再次放大的时候你的鼠标是否停留在比较远的地方呢？缩放是会以当前鼠标所在位置为中心点进行放大的。

我并没有放到很远的地方，我甚至都不移动鼠标

**Comment by qmhc** [comment]
那你是否可以录制一下你操作时的表现，以及提供一下 `System Info`，我按照你文字描述的步骤，无法在文档中复现你所说的问题。

**Comment by whenTheMorningDark** [comment]
> 那你是否可以录制一下你操作时的表现，以及提供一下 `System Info`，我按照你文字描述的步骤，无法在文档中复现你所说的问题。
![动画1](https://github.com/vexip-ui/vexip-ui/assets/30688843/3d797b55-4e4d-4450-a159-eaff1077f17a)

![Uploading image.png…]()

**Comment by whenTheMorningDark** [comment]
![image](https://github.com/vexip-ui/vexip-ui/assets/30688843/3b1c7e91-3d5c-4d3a-9a5a-04b058e198e0)
感觉有点像是这里的问题

**Comment by whenTheMorningDark** [comment]
![动画1](https://github.com/vexip-ui/vexip-ui/assets/30688843/94119e71-2780-45cc-8d69-8180ae80d2cb)

**Comment by whenTheMorningDark** [comment]
还有就算是我点击拖拽黑色遮盖层的区域，也会拖动图片呢

**Comment by qmhc** [comment]
> ![动画1](https://private-user-images.githubusercontent.com/30688843/299934840-94119e71-2780-45cc-8d69-8180ae80d2cb.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjIxNjAsIm5iZiI6MTcwNjI2MTg2MCwicGF0aCI6Ii8zMDY4ODg0My8yOTk5MzQ4NDAtOTQxMTllNzEtMjc4MC00NWNjLThkNjktODE4MGFlODBkMmNiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA5Mzc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZTI3ZmY5MGQ3MmM4YmEyNDIyYmY1NjdmYjczOTVhOTk2MmFjZDg4YzgwNDhlNjljYTM2YTY4N2RjODkyMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FTyLZ1KDKuZp1ENHwBHgsotcH2qCgBcS68QRtF7XROY) [ ![动画1](https://private-user-images.githubusercontent.com/30688843/299934840-94119e71-2780-45cc-8d69-8180ae80d2cb.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjIxNjAsIm5iZiI6MTcwNjI2MTg2MCwicGF0aCI6Ii8zMDY4ODg0My8yOTk5MzQ4NDAtOTQxMTllNzEtMjc4MC00NWNjLThkNjktODE4MGFlODBkMmNiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA5Mzc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZTI3ZmY5MGQ3MmM4YmEyNDIyYmY1NjdmYjczOTVhOTk2MmFjZDg4YzgwNDhlNjljYTM2YTY4N2RjODkyMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FTyLZ1KDKuZp1ENHwBHgsotcH2qCgBcS68QRtF7XROY) ](https://private-user-images.githubusercontent.com/30688843/299934840-94119e71-2780-45cc-8d69-8180ae80d2cb.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjIxNjAsIm5iZiI6MTcwNjI2MTg2MCwicGF0aCI6Ii8zMDY4ODg0My8yOTk5MzQ4NDAtOTQxMTllNzEtMjc4MC00NWNjLThkNjktODE4MGFlODBkMmNiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA5Mzc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZTI3ZmY5MGQ3MmM4YmEyNDIyYmY1NjdmYjczOTVhOTk2MmFjZDg4YzgwNDhlNjljYTM2YTY4N2RjODkyMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FTyLZ1KDKuZp1ENHwBHgsotcH2qCgBcS68QRtF7XROY) [ ](https://private-user-images.githubusercontent.com/30688843/299934840-94119e71-2780-45cc-8d69-8180ae80d2cb.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjIxNjAsIm5iZiI6MTcwNjI2MTg2MCwicGF0aCI6Ii8zMDY4ODg0My8yOTk5MzQ4NDAtOTQxMTllNzEtMjc4MC00NWNjLThkNjktODE4MGFlODBkMmNiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA5Mzc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZTI3ZmY5MGQ3MmM4YmEyNDIyYmY1NjdmYjczOTVhOTk2MmFjZDg4YzgwNDhlNjljYTM2YTY4N2RjODkyMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FTyLZ1KDKuZp1ENHwBHgsotcH2qCgBcS68QRtF7XROY)

这个就是鼠标移到了外边的地方，在最小的时候，鼠标距离图片可能只有10px，但是随着放大，这个距离也会跟着放大，随意图片就越走越远了。

**Comment by whenTheMorningDark** [comment]
> > ![动画1](https://private-user-images.githubusercontent.com/30688843/299934840-94119e71-2780-45cc-8d69-8180ae80d2cb.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjIxNjAsIm5iZiI6MTcwNjI2MTg2MCwicGF0aCI6Ii8zMDY4ODg0My8yOTk5MzQ4NDAtOTQxMTllNzEtMjc4MC00NWNjLThkNjktODE4MGFlODBkMmNiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA5Mzc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZTI3ZmY5MGQ3MmM4YmEyNDIyYmY1NjdmYjczOTVhOTk2MmFjZDg4YzgwNDhlNjljYTM2YTY4N2RjODkyMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FTyLZ1KDKuZp1ENHwBHgsotcH2qCgBcS68QRtF7XROY)
> >       
> >         [
> >           
> >         
> >             ![动画1](https://private-user-images.githubusercontent.com/30688843/299934840-94119e71-2780-45cc-8d69-8180ae80d2cb.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjIxNjAsIm5iZiI6MTcwNjI2MTg2MCwicGF0aCI6Ii8zMDY4ODg0My8yOTk5MzQ4NDAtOTQxMTllNzEtMjc4MC00NWNjLThkNjktODE4MGFlODBkMmNiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA5Mzc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZTI3ZmY5MGQ3MmM4YmEyNDIyYmY1NjdmYjczOTVhOTk2MmFjZDg4YzgwNDhlNjljYTM2YTY4N2RjODkyMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FTyLZ1KDKuZp1ENHwBHgsotcH2qCgBcS68QRtF7XROY)
> >           ](https://private-user-images.githubusercontent.com/30688843/299934840-94119e71-2780-45cc-8d69-8180ae80d2cb.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjIxNjAsIm5iZiI6MTcwNjI2MTg2MCwicGF0aCI6Ii8zMDY4ODg0My8yOTk5MzQ4NDAtOTQxMTllNzEtMjc4MC00NWNjLThkNjktODE4MGFlODBkMmNiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA5Mzc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZTI3ZmY5MGQ3MmM4YmEyNDIyYmY1NjdmYjczOTVhOTk2MmFjZDg4YzgwNDhlNjljYTM2YTY4N2RjODkyMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FTyLZ1KDKuZp1ENHwBHgsotcH2qCgBcS68QRtF7XROY)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/30688843/299934840-94119e71-2780-45cc-8d69-8180ae80d2cb.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjIxNjAsIm5iZiI6MTcwNjI2MTg2MCwicGF0aCI6Ii8zMDY4ODg0My8yOTk5MzQ4NDAtOTQxMTllNzEtMjc4MC00NWNjLThkNjktODE4MGFlODBkMmNiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA5Mzc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZTI3ZmY5MGQ3MmM4YmEyNDIyYmY1NjdmYjczOTVhOTk2MmFjZDg4YzgwNDhlNjljYTM2YTY4N2RjODkyMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FTyLZ1KDKuZp1ENHwBHgsotcH2qCgBcS68QRtF7XROY)
> >         
> >        [ ![动画1](https://private-user-images.githubusercontent.com/30688843/299934840-94119e71-2780-45cc-8d69-8180ae80d2cb.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjIxNjAsIm5iZiI6MTcwNjI2MTg2MCwicGF0aCI6Ii8zMDY4ODg0My8yOTk5MzQ4NDAtOTQxMTllNzEtMjc4MC00NWNjLThkNjktODE4MGFlODBkMmNiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA5Mzc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZTI3ZmY5MGQ3MmM4YmEyNDIyYmY1NjdmYjczOTVhOTk2MmFjZDg4YzgwNDhlNjljYTM2YTY4N2RjODkyMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FTyLZ1KDKuZp1ENHwBHgsotcH2qCgBcS68QRtF7XROY) ](https://private-user-images.githubusercontent.com/30688843/299934840-94119e71-2780-45cc-8d69-8180ae80d2cb.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjIxNjAsIm5iZiI6MTcwNjI2MTg2MCwicGF0aCI6Ii8zMDY4ODg0My8yOTk5MzQ4NDAtOTQxMTllNzEtMjc4MC00NWNjLThkNjktODE4MGFlODBkMmNiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA5Mzc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZTI3ZmY5MGQ3MmM4YmEyNDIyYmY1NjdmYjczOTVhOTk2MmFjZDg4YzgwNDhlNjljYTM2YTY4N2RjODkyMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FTyLZ1KDKuZp1ENHwBHgsotcH2qCgBcS68QRtF7XROY)
> >       
> >         [
> >           
> >         
> >             ![动画1](https://private-user-images.githubusercontent.com/30688843/299934840-94119e71-2780-45cc-8d69-8180ae80d2cb.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjIxNjAsIm5iZiI6MTcwNjI2MTg2MCwicGF0aCI6Ii8zMDY4ODg0My8yOTk5MzQ4NDAtOTQxMTllNzEtMjc4MC00NWNjLThkNjktODE4MGFlODBkMmNiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA5Mzc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZTI3ZmY5MGQ3MmM4YmEyNDIyYmY1NjdmYjczOTVhOTk2MmFjZDg4YzgwNDhlNjljYTM2YTY4N2RjODkyMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FTyLZ1KDKuZp1ENHwBHgsotcH2qCgBcS68QRtF7XROY)
> >           ](https://private-user-images.githubusercontent.com/30688843/299934840-94119e71-2780-45cc-8d69-8180ae80d2cb.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjIxNjAsIm5iZiI6MTcwNjI2MTg2MCwicGF0aCI6Ii8zMDY4ODg0My8yOTk5MzQ4NDAtOTQxMTllNzEtMjc4MC00NWNjLThkNjktODE4MGFlODBkMmNiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA5Mzc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZTI3ZmY5MGQ3MmM4YmEyNDIyYmY1NjdmYjczOTVhOTk2MmFjZDg4YzgwNDhlNjljYTM2YTY4N2RjODkyMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FTyLZ1KDKuZp1ENHwBHgsotcH2qCgBcS68QRtF7XROY)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/30688843/299934840-94119e71-2780-45cc-8d69-8180ae80d2cb.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjIxNjAsIm5iZiI6MTcwNjI2MTg2MCwicGF0aCI6Ii8zMDY4ODg0My8yOTk5MzQ4NDAtOTQxMTllNzEtMjc4MC00NWNjLThkNjktODE4MGFlODBkMmNiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA5Mzc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZTI3ZmY5MGQ3MmM4YmEyNDIyYmY1NjdmYjczOTVhOTk2MmFjZDg4YzgwNDhlNjljYTM2YTY4N2RjODkyMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FTyLZ1KDKuZp1ENHwBHgsotcH2qCgBcS68QRtF7XROY)
> >         
> >        [ ](https://private-user-images.githubusercontent.com/30688843/299934840-94119e71-2780-45cc-8d69-8180ae80d2cb.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjIxNjAsIm5iZiI6MTcwNjI2MTg2MCwicGF0aCI6Ii8zMDY4ODg0My8yOTk5MzQ4NDAtOTQxMTllNzEtMjc4MC00NWNjLThkNjktODE4MGFlODBkMmNiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA5Mzc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZTI3ZmY5MGQ3MmM4YmEyNDIyYmY1NjdmYjczOTVhOTk2MmFjZDg4YzgwNDhlNjljYTM2YTY4N2RjODkyMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FTyLZ1KDKuZp1ENHwBHgsotcH2qCgBcS68QRtF7XROY)
> 
> 这个就是鼠标移到了外边的地方，在最小的时候，鼠标距离图片可能只有10px，但是随着放大，这个距离也会跟着放大，随意图片就越走越远了。

我看到这个逻辑了，但是现在我这边测试提单了，你有什么好办法让这个情况不出现吗？

**Comment by whenTheMorningDark** [comment]
![image](https://github.com/vexip-ui/vexip-ui/assets/30688843/843b766c-42ab-4fba-a8cb-7e63e064c39b)
我注释了这段就符合我的预期，

**Comment by whenTheMorningDark** [comment]
其实我觉得在useMoving,拿到拖拽后的left和top,如果是zoomOut

**Comment by qmhc** [comment]
> ![image](https://private-user-images.githubusercontent.com/30688843/299940836-843b766c-42ab-4fba-a8cb-7e63e064c39b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjI0NTIsIm5iZiI6MTcwNjI2MjE1MiwicGF0aCI6Ii8zMDY4ODg0My8yOTk5NDA4MzYtODQzYjc2NmMtNDJhYi00ZmJhLWE4Y2ItN2U2M2UwNjRjMzliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA5NDIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyOGU1NGQ0YjZlNDg4MmU3MzJhODYwNDQxMzI2NGZlNWUwZGQ1MmI5MWVmYzhhM2M5ZjE3NGE1NjNjYzAxMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ttSi_9xA611PJQayazWWj4yQMH17KLvx0DqdWassR5I) 我注释了这段就符合我的预期，

这代码是处理让缩放中心在鼠标停留的位置的。

**Comment by qmhc** [comment]
可以优化成当图片未超出视窗时，仅能局限在视窗内，然后添加一个属性，控制是否将鼠标位置作为缩放中心。

**Comment by whenTheMorningDark** [comment]
> > ![image](https://private-user-images.githubusercontent.com/30688843/299940836-843b766c-42ab-4fba-a8cb-7e63e064c39b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjI0NTIsIm5iZiI6MTcwNjI2MjE1MiwicGF0aCI6Ii8zMDY4ODg0My8yOTk5NDA4MzYtODQzYjc2NmMtNDJhYi00ZmJhLWE4Y2ItN2U2M2UwNjRjMzliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA5NDIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyOGU1NGQ0YjZlNDg4MmU3MzJhODYwNDQxMzI2NGZlNWUwZGQ1MmI5MWVmYzhhM2M5ZjE3NGE1NjNjYzAxMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ttSi_9xA611PJQayazWWj4yQMH17KLvx0DqdWassR5I) 我注释了这段就符合我的预期，
> 
> 这代码是处理让缩放中心在鼠标停留的位置的。

其实我觉得在useMoving,拿到拖拽后的left和top,如果是zoomOut 
1.先定义了scale为1
2.如果是 zoomOut 的时候 scale .value = scale / zoomDelta ，然后在contentStyle中left = currentLeft/ scale
3.如果是 zoomIn 的时候 scale .value = scale * zoomDelta ，然后在contentStyle中left = currentLeft/ scale
这样也可以保留在中间的位置

**Comment by whenTheMorningDark** [comment]
> 可以优化成当图片未超出视窗时，仅能局限在视窗内，然后添加一个属性，控制是否将鼠标位置作为缩放中心。

我觉得还是太麻烦了，主要是为了left 和top在中心位置就可以了

**Comment by whenTheMorningDark** [comment]
> > 可以优化成当图片未超出视窗时，仅能局限在视窗内，然后添加一个属性，控制是否将鼠标位置作为缩放中心。
> 
> 我觉得还是太麻烦了，主要是为了left 和top在中心位置就可以了

我到时候提交一下代码 你看下可以不

**Comment by qmhc** [comment]
Completed by 1458e41bd53603d9ac21a5377c7a3b613b2fb5e5.
