### ISSUE TITLE
Drawer event 'show' is emitted twice without any action

### ISSUE THREAD

**Issue by Nalca** [vexip-ui/vexip-ui#461]
### Describe the bug

I'm using the **drawer**, and before doing anything with it, the event '**show**' is emitted twice.
According to the [documentation](https://www.vexipui.com/en-US/component/drawer.html#drawer-events), it should be :

> When the drawer is opened, emitted after the transition effect ends

So 0, since we have yet to open the component.

### Reproduction

https://playground.vexipui.com/?vexip-ui=2.3.2&vue=3.4.18&typescript=5.2.2#eNqdVV1v2zYU/SucOlQS5lBA8+bZRpcsQDd07dDkrS5cTbq2mFAkR1J2DMf/ffeSkuxmbR8KGLB0Pw7PPTykDomzVfGbMXzbQTJNZh5aI0sPi6VibHbVea8V83sD82VirGhLu18m7HUlRfWAobLyYgtszn6KT8skNDL23oAKEEXEiHi/23IHlm0vWl2DnMaeEQaBvS2VW2OJF15S5o7+aUXX6B2+S7252YLyWT4uNTOLW90Cq7TymJkV5gcTsyLyw5dZcSYEvrrKCuOZA98ZJku1QSreBQqiNdp6dmAW1uzI1la3LEU1U2rEFZxno0pYkq1L6SBfqnWnMIzqnkZiB6IRe1pwrtxQ0zJ5BztG8zOguilG2C/MgF1r25aqAq70Lst/HZq1BI6gWQ9BiRMuSISsddW1CMUrCzjjjQR6y3CLl0nEAck9PPrrqBC29GAhObb/o+s9Lw3udZ2BpM4jaRfVQm2SSRLluWhLw++dVuixMOSyT6CGU3bALvxhtXfIci02z2or3Rohwb43pFjsiVuJ3pFS7/4MMW87mAzxqoHq4Svxe/dIMbIzOLBkuzHnS7sBH9M3t+9QgLMkerYjL34n+QFQ/I44xrKrTtVI+6wusP0jjC7U5s7dPKK+bhjqC6J06kL04zLZwqMwF50oQpDXnIT7RJXHUI8VHVx/R6XTZJf8MvQNktMF0JZCISQKPro5OgNvhglr/mfrsUqgpXCkU0HPE6v6GkToc3y4Z07JuwaNd7sTvmrGorNYXzwcow9gyLxhJlW2MGUphdKgQDiawxFieNJ8ZxXDwHzBmiytxTadsI9NhhxyHCk7Wyb/hMdxUGRYrNVd8H1EODuYaHcKZzuhajySpWOl2ud8tcLEaoWpUbmM2OW8c5D1OuW4ECFhKe+NDtZq+6YMPsFmPPCL8RCHXEaXRWwJnLL0BT6nGAxsFd4Nf6N0wsFsq0W9yDL0tZZbmKAI91D55wOIGtdJV6uwVyvn9xJWK5R5yGtJBeMZ/7cDu78FiUhI5vOLnw+iPn7OafA3d3+9fSvUQ39/sCemOilPSA1dibhW471x06LolHnY4OBtMfjk9St+yV8VtXC+CEx45VzYcsbEmmXE5eVLosQj2HweUM/2OcyKn4Ozbe9380REIkkkQmhPT9+6/VKqIl2pj575t5UKaRvu0jTEXQPgT6l+cvo7w9NK6pIwo6m+4N4XhC0PXwrautg78m2grDlaCay/Arz8IaOuybOCtbDOXzdC1uSRnPsGVBasg+/J8T+wcrEw

### Steps to reproduce

Go to the playground. There's nothing to do since the bug happen when the app is loaded.

### System Info

```shell
Vexip: 2.3.2
Vue: 3.4.18
Typescript: 5.2.2
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
This maybe a specified issue for playground. I copied the code to local IDE and run it in dev server, and the issue does not occur.

**Comment by Nalca** [comment]
Yes, it do happen in my project.
It's also happen when I download the project from the playground and test it.
