### ISSUE TITLE
Carousel 宽度显示bug

### ISSUE THREAD

**Issue by NJHSFNAK** [vexip-ui/vexip-ui#472]
### Describe the bug

Carousel使用时，vxp-carousel__list会有一个宽度。当我修改页面视图宽度时（比如拖动控制台），vxp-carousel__list的宽度就会修改，我想要页面加载完成后就展示第二种效果，要怎么修改？我用的是rem，不太确定是不是因为这个问题引起的
<img width="1727" alt="image" src="https://github.com/vexip-ui/vexip-ui/assets/38530519/1ff60c72-6404-45c3-9de1-92f239e8d406">
<img width="1726" alt="image" src="https://github.com/vexip-ui/vexip-ui/assets/38530519/d42fa7ff-4c54-4cc1-b6ff-6395400c2e09">

### Reproduction

null

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by NJHSFNAK** [comment]
目前不能自定义添加轮播图上下切换事件，希望可以加上，这样扩展性更好：）

**Comment by NJHSFNAK** [comment]
https://playground.vexipui.com/#eNp9Vttu20YQ/ZWF0kZUa5E23AKBIgmtDQNJkbRFbKAPUaDQ5FBce7nL7i51qazH9nP63g/Kf/Ts8iLabQIYNjlzZubM2dmh9wOjk+jHsgzXFQ0mg6mlohSxpflCMjZN+ZolIjZmthjcqu1i4M1sehlrVRkSbD0uVEpiEieWrwmo+mEx6MKSBtrGHoNfoxYSZEoDJhmX7HvETe5p5947/BMaKRVqXMYSNTrAp7/+/PT3P/s9k+xw6KIihLU1o37RurfO1LzW6GnUUwCvJtG8tMyQrUomYrkCBWt8bV6USlu2Z0q+VZW0lLIDy7Qq2BBiDl/2EJqyRz6XOlHSWFbrxWYOEpyOFrJLFgSj2XzvuNXI3BYCuFQlVUHShu3DlSD3B+VapKbiIjYuaeCCwkRwAH7jqc3ZN+zs9HTEInb+4rvTlyyK2BnggMJcbl0OH2LsTlCYKWmv+R81vTrnt2wxAG6AcgewnUa1QE45H8NMokpK8R5iYDz9jSs8OX+BFC4KnnYmem5X/+vG3R0x84CUGxzIbsIyQVvfZiz4So45TspMWILeSHv7XWUsz3ZjyGBhfeR7XAZtEl/lgJyd1rwYc92ODdqdsHNo0QgqlJ6wZ1mW+ffbOLlfgbxMUcS71rEOxuP1tqwN41LzIta78S3UGvkYq2NpuOVK9tFHa/2Ia1A4PASAqE7K+eBkUE/QuIjL8M4oiRvqJVk0DgzihO0Rgh+gLcSXGV89wSaqKLkg/UvpytUx9b3AfRVCbX7yNqsrOmntSU7J/f/Y7wwOf+KGQJMh7a5657OxXpGt3VfXP9MWz50Te6ISQH/B+Y6MEpXjWMMuIDNo93Ce7WvfOperG3O1xTmbtqlHRO2uJG99vxisacvLccUjbwzT0An3wSEPHg9ERZdfUOnY2Xl47uNayd36LGIukRKCdxc+0YQVgr16wvL/3PwOxXFb0dIR0PAEqsEgQ+ML2y19dN7kuPnXG26TvAP1bA243TTvqHT7w/ck4wJTPnSmoVfA77dg1Has8aolg2E2Z3kwxG4cnrD3eQAOI7QU9MqMPmAPtIq0xQq3w9wC8hl6WyxGQzAHGy5TtWGxYbHcjcLlEo7lEq5OucCxG4XYE0Gj0wiF/PWHEM2gk9ZKv4r9nCAYm2ruCylsL+8LyLNzIZ5TMHyG5yGMnq2kDfsV0nFD07Xi6TwIMNdKrOkEItxRYp82wFPUGS6X/qyW/qIul5C59SvhAN2W/r0ivbsmgUwg8/HZV3ueHj6OXOOvbt6+ecPlfbPA2QOTlRC9he++GqiVW1uaSRRVsrxfofEiaufkB/edMhafLvyqV3ZijD9zxnjGAkfm+XPHKayzzWY+be+gfbOBF6k99+Y4j0wEWIKJy/bwcOytPqqGfjB0KCesi3PP4eel8m6N/x/g93aTE9mjq2nd/enlU1Ko2OWsp+oR9wbgz9x/rtzZ1bEd35ziNMQskbYXhH1LgYs6eQLIuDb2MucidUMyCm1OMvCzg/fB4V+CPR1C
我设置的rem是写在**main.ts**中的，是在抱歉没找到**main.ts**在哪里，我就写在**onMounted**函数中了

**Comment by qmhc** [comment]
目前你可以先通过 ref 调用组件实例的 refresh 方法手动刷新
