### ISSUE TITLE
折叠面板，无法根据响应式自动切换指定的面板

### ISSUE THREAD

**Issue by leizhiyou** [vexip-ui/vexip-ui#476]
### Describe the bug

折叠面板，无法根据响应式自动切换指定的面板，示例中点击按钮a，折叠面板没有响应

### Reproduction

https://playground.vexipui.com/#eNrVVc1u20YQfpUFU4QkIJEJgl5USUhtGEiLtA1i38KAWZAjce3l7nZ3ScmQBfTSAgX6BkUufYCe01z6MkmBvkVml6QkOz8IckoAw17OfDP7zcw3601gdJF+q1TSNhBMgqmFWnFqYZ4JQqYla7vDUWOtFOR+wVlxMcsCA/ZknQVzOk07l4ch8FhyTpUB0o5rWQKfwFpRUUKJQcMxCwgtCqlL9nbcIyqAE8ssB4z4//lf/z3/99WLX/CqDohQNUfDq5d/vv7t19d///O+8zRVnx4yTa/x+SiSL//4Aki++P0zILm39Z+dzKbpgfjw0xSaKUtQao0inIollmGN589qJbUlG6JhQbZkoWVNQlRw6AILKYwlg9jIzIGiu/Hg8NJFaxST2ZxsMjEgk5byBtBzNxNbR6cj0JOxlxyIKaSCEi1Ju1bjYtA6JiGkpuvxipW2mpCv79xR62+GLC4SQ4JR0NEe11Ql50YK3DcfmfUOrG1CNhiEP4i2eJtYsOUNbCFrxTjon5TF/eliul5nAeVcrr73NqsbGA32ooLi4h32c4NLPMGD0mBAt5AFO5+legm2c5+c/ghrPO+cuNsNR/QHnI/BSN44jh3sqBEl0j7Aebbf+dKZWJ6Zk7UFYYairhG1lwq89UkWtLBmatyw1BuTMnGNe+qQW49HRAPHH+jSvrJ7yT0fN7TcPYY1ZQJTYsN3Kis0oCrxlRyR6i257VAM1YUl7QE9T0T1GMzQ+5Lhzd07zyqo4XTFbFHtQAe2Hjyo+DEojlL1NQlaw4SEzhT6DviVQX33FWv81KIXfBWFuG7hiDypIuQQY0nRwTXxU1yUoSPDZbVshD1cGUI6B8WC0BytmCjlilBDqLiMkzxHR56ja9e5yLGLk8ZA1PcpxotcJoQmvdBBa6kf4DLi4DAYd3HuL5IcOl8Enp0L8Zyi8BaeQzR6tgJW5BG2jhmYtpKV8yhCXUvewgibcA6FvVkAc+9DmOd+Vrlf1TzHNg9+yR2glEVTg7DJzw3oy1PgmAnJPLv11YaV22exK/zB2Q8PHzJxccKxl9itKyIazveZKvdU4V2VtcpM0rQR6mKJhdfpoJP77ukzFl9D/OWpJIUxfuaEsAWJHJnbtx2npMs2m/m0B4P2xUa+ScPc+3HumXBkiUxctqurfW3dqHr6UehQrrEuzp2T97fKuzX+s0G/t5sKwO5dfenuz0E+KbikLmenqmvce4CfuX/A3ey62B3fCmiZoJZA2yNYSA2RixrdACyYNva4Yrx0IokTW4GIvHbwO9i+ASZUXeU=

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
已在 [9ba993a](https://github.com/vexip-ui/vexip-ui/commit/9ba993ad4359a56fdf56fb043e9b1b32a0812b8a) 修复。
