### ISSUE TITLE
Dynamic format label in datepicker

### ISSUE THREAD

**Issue by asrori7** [vexip-ui/vexip-ui#480]
### Description

how to change format label datepicker from YYYY-MM-DD (2024-06-05) to DD-MM-YYYY (01-06-2024) ?
![image](https://github.com/vexip-ui/vexip-ui/assets/14250248/f9e18a66-114b-45fb-924a-e82c304285b1)

### Validations

- [x] Ensure this issue neither a bug report nor a feature proposal.
- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that descript the same thing to avoid creating a duplicate.

**Comment by qmhc** [comment]
Next patched version you can customize the order of date units via `format` prop.
