### ISSUE TITLE
make focus in timepicker

### ISSUE THREAD

**Issue by asrori7** [vexip-ui/vexip-ui#484]
### Description

Hello, i want make focus in unit HH when timepicker visible, so I can type using the keyboard. but now focus not work ?

this my script
https://playground.vexipui.com/#eNp9VGFv2zgM/SuCd5htILEH9FsuCXYrCuwOu21Y+20eMs9mYrWypElykiLNfx8p2bFXbAOCROGjyEfyUafImir/R+ts30G0iJYOWi1KB+tCMra84y185NUDGGZguyoi/CZbEbH9vFU1iMW+FB0g4oJZqnlZOa4ks+5RENCWx/mB165ZsKtXr/QRnV47tdt5MByKaL3Mx1wht15fd8aAdIyQBTudGOVg5/My1+iyzCdc8a+tDNeOWXCdZqKUOwpvMXQheauVcexERbAz2xrVshgLji+Qe9SA+Mjh5qiVhXr0hiPX847jlUIKcBSKvNmKTpNG9RfXSfp3ISslLQa/+CVxnFKA3u6LRyTZc8u/CSzym1ICSpmy1ZqdqA18e0HTYGFD6sy3PtuqqrMJhmXsXEj8LPPQinU0i0J587bU2b1VEifsYxQ9gO3BxoZr6O0sEtvy3TPfSrWaCzAfNA023AlMiqgUQh3+8zZnOpgN9qqB6uEX9nuLAljgQRuwYPY4+wvmSrMDF+Cb2/dwxPMFRLV1pJQ/gJ/AKtERx+D2ppM10p74ebb/+tK53N3Zm6MDaYeifiJKivDWz0U0DD/3xqzOqHFffMe9P3p0cP2HLo2VXWVX46Sw5bR+bcklhsSGX4RaGUBh417OWPNMsRM5c1QRlvQrkfY+GKHHsmHLR/CugRZuD9xVzcVpYuudB7V+Ai1Qq74mWdJGxmSKfQf81iUThbrOSIYG1HGTxDXfxzP2uUmQQ4olJZM06ZeJdodkrepw8XEzxk0IQIkFoTk5cFmrAystK+Vjmm02CGw2CF06lxC7NOssJH2fUr97jGJkvdDBGGXell4neBmXce0T4RYGLAHPjq54Tkn8As+0xZ6thAP7iK3jFpZ7xXHtE9S1EnuYYRPuoXLPC+A15ok3Gz+rjX8kNxts84ArQQ41LnWLb1/2vQPzeAsCIyGZry/+OvH6/DWlwt/e/f/uHZcPNwJ7id16YrITYozU0GuHuRrntF3keSf1ww4Lb/NBJ6/p9bQurzl+eSpZZa2feXh5iMzLl8QpC9FWKx92MmhfbHh+hrn34xyZCGSJTCja09NYWxhVTz+JySs8j8zfyH7fKg8bID3G3m4bADdCfen0M4mnpFAlxQyq+ol77+Bn7t9qml24e+HbQFlnqCUw7g1slYGEbs2eOWy5se664aImkaSZa0AmXjv4Pzr/ACdgiEQ=

### Validations

- [X] Ensure this issue neither a bug report nor a feature proposal.
- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that descript the same thing to avoid creating a duplicate.

**Comment by qmhc** [comment]
You can use `ArrowLeft` and `ArrowRight` to switch the active unit.
