### ISSUE TITLE
`expandItemByLabel` 没生效

### ISSUE THREAD

**Issue by codesyofo** [vexip-ui/vexip-ui#487]
### Describe the bug

```js
const menuRef = ref(null)
onMounted(() => {
	menuRef.value.expandItemByLabel('label')
})
```

### Reproduction

https://playground.vexipui.com/#eNqtVs1u20YQfpWFUoRUIJPNTy+qbaQ2DCSF0wZOih6iQGHIkbk2ucvuLiULtp6gKNpLeipQ9NZLTz31gWL0MTqzu6RI2U6TIAYMLef3m5+dnfOBVmn8VVVF8xoG48G2gbIqEgO7E8HY9hMQNVMw25kMSjwewWwyYGMlawMKae6ApCQ1fA5Iubt1Fz+1WRb0VSZnWwuemXzM7j34vDpD1kMNBaQGmXkisgKe2c/JYHc7JmfodjvuYMBPnSpeGabB1BUrEnGMukajxkTwspLKsHMmxRNZCwPZCMGyFZspWbIAQwq+7Ejt54kyTzmM2D43yxE7EHMoZAV6ry5OR+w7DarVfTiHM15t1TzmqRQ6mIg4Zq2lVAHiO7Lhj/zX9/D6EddGqmUXwJbLEep3LZhlBWjGGjiUaWK4FEfJ4ibFWS0wwVJc8RQO2TkVKo4nYnWNpEMYyopoeswSsfQaCtOpBIVSKwXCWMkxfs+TosZDELDViHlFxJVoUvZeKCOGOYBsp+/LWs8dvPE1gEfWO8kinhf0wRwi+qsS6pUgLu8GVo7+Uok5EwgR0a1aagkmQULzybAzXkOBuh1NxkRSUiz//vzb25/esB6Lyjrut0DDXHtJc15kmJ4WaQ9tB3Has30T6GuB98BvbdhpQ3j71y9tFF0BrEd77Ghei/HeJ8K4YecajPduxNgcX7pD4/dqB3ScfGAH9OD1O6DHch1Ao6At/P+Buv/RoDqam6B6LA/KT6r3Bvbgo4F1NDeB9VgOGM3I9wb1xQeDokdmzGZJoa+ETj/YNKuhn6SXf/5x+ePvrKp1zi5//efy7zcT4SZSZGk7OLKWImWhkWMW37k6a+/Ebhzu7DoENNRkAREXM4lK6Kc/UbvvVeizp43i4njUBOJDd1S28qO2Z9gqOoXGg5um/n1F3PiEhaIuCuS371qIk94B9XKRndMRnFUI6zG+mHvLQzIdBtZDQMbxfzt2zyc+loPRwL0+W2VSRSdaCnzvLcCJZ+CjSuWxsFDaaEQ248cbslRKXoD61r0NVsfVaDJIikIuvrY0o2rwhUadHNLTa+gnGneCMR4qBdhZc5gMWp5J1DHgZkDsg2ffwBmeW2Yps7pA6XcwjwCzXhNGJ7ZXU/1wW2nlLNrHNnSs13N9cGZA6CaoHlB6sC31xWTQbgaWGGURJc7OM9fZKFHD/juytI7sfnTf6jUpp2WsTLhAk5jwjXUDt7QRy3vbDbVPK8WxjTCktYDHiVJeBi14XtTsfGvm8xxKeLbgJs1boQ7NCzftegRVgb1qY/JTg0juxttdrdlN2l3DtXAeBhmfByP2Ig8RwxBDCjtuhi+xa5uMtHeDLgF6ay+Bu1SGJRgQksMFF5lc+CVlGE2nyJhO29UE/YSEbhjVGkKfp6GdJIxsRL7RQSmpHtl7TnsNkLfm9lpeCBYdqVhMYXALz/aykTEBC/YUU8c1bM8lz3bDEPtaFnNcORWc4ODYDIBn6CeYTm2tpnZvnk7t4+n4siCBTKY13nsT/VCDWroRhGBe3frsnGerV0MK/NHzJ4eHXJweFJhLzNYFoxmytpTTZoy+cmMqPY7jWlSnxxh4GTd98pB2bm3iDFe12EKJUk2bLxnhMxYSmNu3CVPkrO3sWLOdQttgQ5ukpu6+nGskBaJEJGTt4mIdmyuVh49jDKUosaRH5+jmVFm2AurHwNJ1DmDWLB86/XTsSVHIhGy6ruph9wK25nYiU+2cbos3hyTDmY5jy+zBTCoISWu0ITDjSpt9WiPtRI5MDiK0vYPfg9V/0K5Wqg==

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
请仔细检查调用方法时传入的参数。
