### ISSUE TITLE
[Tree]: Warning about duplicate keys

### ISSUE THREAD

**Issue by Nalca** [vexip-ui/vexip-ui#492]
### Describe the bug

When using the **Tree**, a warning about duplicate keys found during update is logged :
![image](https://github.com/vexip-ui/vexip-ui/assets/1692271/9320cd44-5046-4ef0-978f-4168592ee5dd)
Since this kind of [warning should not be ignored](https://vuejs.org/api/built-in-special-attributes.html#key), I'm posting it here.

### Reproduction

https://playground.vexipui.com/?vexip-ui=2.3.10&vue=3.4.29&typescript=5.4.5#eNqVVWtv00oQ/Ssrc4VtKdi0vdxHlFRQVIk3iFZ8qZFZ7Em87Xp32V3nobT/ndm1nQQ3IJCqxp6Zc+bMI5NNYHSRPlMqWTQQjIOJhVpxauE0E4RMLjUAGZfU0mkWuI8sOJ2kzor+SboXjK+m0ExZYsA2inAq5oixBhGZKKQwljgCMiVXjnrj/hHCyjE5GrXPnH4FPibhM8FqysPOqqgGYcfkcfcOK0VFCYizugFnu/OePcLjAeEZ0+WQ7slB5MkA+VIsQFv4qrHIIcPRQYa/BwxvaX2gmMPZnwywn/4w9z/3cs8Vu4c9Poj9d4A9p9pWS6nrIfzkIPy/AfwVcL6eMVP9Hvz/AfwDbo/kTPxe34763ejhr8FYDfe63laeic9ud9ttxd0MRgGrldT2UU1Vcm2kwO+BZ886B+7wmGwQiH8YbQ2u84zNB7GFrBXjoN8ry3DdPabNnwWUc7l85W1uaztdiKmguDlgvzYrZ8sCpcGAXkAWbH2W6jnY1n1+8Q5W+Lx11rJsOEb/wvkRjOSN09iGnTWiRNl7cV7tS186E/NLc76yIExf1A9C7VqBt15lwQJWTD1qWOqNSZm4xmGv+4lhRAPPf9GlXWUnSbsnfcvdkaopE0iJDW+nQjak0IBfDrxeI1KROzLTsiYhJgndPdpGMbw9WNIuoNOJUV0MMnS+pL+FO+dlBTVcLJktqm3Qnq0L7m/cR1Acb5yvSdAacBudqV1FfxqjuK9Y46sWBA3TU1JFYckW4YhcVRFqiLGkaC9N/DnedaRPVstGWMzWMnjW1kGxIDRHSyZKuSTUECrWcZLn6MhzdG07Fzl1cdIYiLo+xZjIMWFo0i06aC31Czy7ODgEg8vmEkkOrS8Cr85BvKYofIDPIRq9WgFL8gFbxwxMFpKVp1GEey35AkbYhGso7LAAVmKeMM/9rHJj1xzyHNvc+yV3AaUsmhq/2sm3BvT6AjgyoZgvD/7asPLuS+wKf3H59s0bJm7OOfYSu3VLRMP5jqnSMHO5KmuVGadpI9TNHAuv035Pnh4nJ8nR47RkxqZeSlIY42eO92dGIifm4UOnKWnZplNPuzdoX2zkm9TPvRvnTgneuxtU4thub3e1taPq5Eehi3KNdTj3nPy8Vd6Nd9D5vd1UAHbn6kp3H3t8UnBJHWe7VT9o7wL8zDGinV2L3eqtgJYJ7hL+eJ3BTGqIHGo0CJgxbezzivHSLUmc2ApE5HcH34O77w7wxf8=

### System Info

```shell
Vexip UI: 2.3.10
Vue: 3.4.29
TypeScript: 5.4.5

On Chrome & Edge
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
It seems to be a playground only warning?

**Comment by Nalca** [comment]
No, I have the same issue locally. Then I tried to reproduce it on the playground.
