### ISSUE TITLE
[Form] Native <button> in form will trigger the web page reload

### ISSUE THREAD

**Issue by HoneyLuka** [vexip-ui/vexip-ui#498]
### Describe the bug

Put a native `<button>` tag in the form, will trigger the web page reload when I click it, even it has no events.

But if I use vexip-ui `<Button>`, it seems fine

### Reproduction

https://playground.vexipui.com/#eNp9VO9P2zAQ/VesMBFHKskHvlUt2oqYYGNjAr4RFLLk2hgcO7Od/lDp/76zkzShG0iIOnfvnt+9u2TraZVFX6oqXNbgjb2JgbLiqYGzWBAyydnSHfD4VaqSjEuZA5/G3jz22kSbusLCfQRjs9oYKQYRQq6Mr8nN9wEoOkBNogHVh/S/36Gf1Ysh/wHsDX8faHqNmmYn0cACfNSZYpUhGkxdEZ6KBXZvtGuflZVUhmyJgjnZkbmSJfHRR98WZlJoQ+ZkarN0uwssdUOGpd7Ia6pPyrQKn7UUaP7W6ojbBF4xJttdLPAP0UYj4ZwtDrCZLCvGQd1UhuGFrqZpLfZSzuXqm4sZVcOoi2cFZC//iT/rtY3FXqVAg1pC7O1zJlULME364u4nrPG8T+JS1BzRHyRvQUteW40NbFaLHGUPcE7tlWudicW9vlgbELpr6o1Qs6nARR9ibwlrVp3ULHLBMA+tcY8WuXN4RNRw/oFLfWen4amr6yy3b0aZMoGUaPh+2JkCXA58ZUak+GfqexTD6WNLPaDViagWgwxtLuxewD55X0AJdytmsmIPGsRacLdlt1BxXDTXk0hLGBPfhnzngNtcGnQdK3xUgmBgekYK6uPW+yPyUFDUEGBLdHBN8Ihb2znSXVbKWhi8rWFwrE0ixYYwTFdM5HJFUk1SsQnCJMFEkmBq7xy16oKw1kBbnwK8yDIhNGwXHZSS6jJ1e4LFYG+zF0kOTY6CU2dLnCbqH+HZx6BTK2BFfqF1TMNkKVl+RinuteRLGKEJz5CZwwZYjvf4SeJmlWiz4ZAkaHOXl9wCcpnVJQgT/qlBbe6AIxOKeTr6tGX57imwjV/e/7i+ZuLlgqOX6NYrETXnPVNhvxh4V2FMpcdRVIvqZYGNl1G3J5/tF0gb/CjhPyclzLR2MyeEzQm1Yo6PraawYZtOHe1g0K5Z6kzq5t6Os1fCUSUqsWyvr31vzaha+dS3KGusrbPn8H2rXFqB3UffxXUBYPpU27r9GfBJwWVqOZuteqO9BbiZu8+pnV1Tu9dbQJqHuEugzAzmUgG1VaMDwJwpbc4LxnO7JEFoChDU7Q4+e7u/xJ5THw==

### Steps to reproduce

Playground can reproduce this bug.

```
<Form :model="f">
  <FormItem>
    <button>test</button>
  </FormItem>
</Form>
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
You need to add `type="button"` to the button.
