### ISSUE TITLE
[Dropdown] @outside-click event was not triggered

### ISSUE THREAD

**Issue by HoneyLuka** [vexip-ui/vexip-ui#499]
### Describe the bug

when I click outside the dropdown, the event was not triggered.

### Reproduction

https://playground.vexipui.com/#eNqNVNtu3DYQ/RVCLiItsJYe8mZ4jdSugaRwmyL2WzbYCNLsijZFqiS168V6gbwW6E/0L9p+T1/yFz2k7m4axDBsaubMzJmZQx4Co7Pk+6qKtzUFZ8G5pbISqaWLpWTsPOdbf8DxB62qXO0ks5pvNqQXyyATPHtYBuyVqq3hOZ16AxxKvm0sVw2izYEsl7W1Cjn2FQFXaV6mej8CMHZHxvbwpMHD3Zs6guwkB6NRYM/whhs7so88bxDMZFq62p8//fb5j7/++fPTpLr7GTzjHMk4yTen//t3zAdTxCzyL5cB4lvKDI5Je+fJZGFjXLPBpFnhBIdPk2leWWbI1hUTqdyAsjV+FLyslLbswDSt2ZGttSpZCHWELjBT0lg23S9bsGjGFhfs4CqmgrSNwikknC3l0RdOmsqoE8yDptRpmVbxvVES+vMplq0DfM7YAXH4BdoaVF/zzTNspsqKo+jbynKw8zHNLJZBKoTa/ehtVtc07+xZQdnDF+z35tHZnDLJkN7SMuh9NtUbso37+vZnesS5d5YqrwXQX3G+I6NE7Tg2sMta5qA9wnm2b3zrXG7uzPWjJWm6piZE3QXy1vfLYEuPvDqteeKNcR67wX1wyKPHA1HT1VemNHT2Mn7p47qRu8ehTLlESgy8V0amCUrCqzFnxX8k0qM4pIKWBkDLE6gWgwytL+7eoMF5V1BJtztus6IHjWwtuJPkO6oEhOh7clfwjIXOFPoJeJlDo23HGp9atqItohBXJJyz90UEDjO0FI3KzD5Aut1EumKlqqWdyr5xpGgI5mjHJa4gSw1L5X4Wr1ZwrFZw9ZOLHLtZXBuK2jnNUMhfIAyiFTpprfTr1OsEweSquUJKUOOLyLNzIZ5TFJ7g3N82STv2C0bHDZ1vFc8vogi6VmJLcwzhnjL7vAGeo064WvldrYzdC1qtMObOr4QD5CqrS5I2/rUmvb8lgUwg8/HkuwPPjx9nrvHXdz/d3HD5cC0wS0zriclaiCFT4Z4X1CqsrcxZktSyetig8TLpdPLKPVfG4gXDH08lzozxO2eMr1nkyLx44TjFTbbFwqcdLdo3G/khdXtv1zkwEWAJJi7b09PQW7Oqln4UOpQbrItz5/j/R+XdmpweQ283BZEdXG3r7t8on5JCpS5no6oJ9xbgdw5Es7smtudbUJrH0BKe30taK02Ri5o/A6y5Nvaq4CJ3IpnFtiAZee3gOzj+C2WWtoU=

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
Dropdown only has `click-outside` and `outside-close` events, this is a document mistake.
