### ISSUE TITLE
在nuxt3中，v2.3.11版本，VSelect不显示options下拉框

### ISSUE THREAD

**Issue by lxyongit** [vexip-ui/vexip-ui#501]
### Describe the bug

![WX20240728-214308@2x](https://github.com/user-attachments/assets/a326ab00-1ab1-4732-852f-f4116701c487)
回退到v2.3.10是正常的

### Reproduction

/

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
已知问题，在目前最新版 2.3.13 已修复
