### ISSUE TITLE
modal\drawer组件打开时，会让内部嵌入的组件渲染两次

### ISSUE THREAD

**Issue by leizhiyou** [vexip-ui/vexip-ui#502]
### Describe the bug

modal\drawer组件打开时，会让内部嵌入的组件渲染两次，如下图：触发了两次onMounted钩子，进行了两次打印
![image](https://github.com/user-attachments/assets/488af9ae-46f6-4311-afe7-bbe6fb706005)

### Reproduction

https://playground.vexipui.com/#eNp9VVFv2zYQ/iucOlQU4MjbsifDNroUAbqh2YYmb3XhCtLZYkKRGknZMRwDexv2vJc9Dvsd+zsrsH+x41GSFbcpEMTi3fG77+4+kvvImnz8XV2nmwaiSTR1UNUyczBfKMamF41zWjG3q2G2iGojqszsFhF7kUuR36Epy53YAJuxL8LXIqKNjH34/Y9///mVQMYBJSBe6SKTIWRzVukC5CTs7MEWUXA7kym7AtOuhJM+5sNfv/33959dzFYUrkTr+VebbbC16acvdVXPp2P6CSwoM35Px4MacWlzI2rHLLimZjJTa8RzlgoRVa2NY3tmYMUObGV0xWJsVNy7PH5rTymZ7yO6FyrXyjrW9wcR+CqTFhLPIOTEDNEoCkhnVVant1YrHMLeE160DmQyYfvDQuEfRjuLwCuxPonNMbWQYH6qncDEtCd0Atsqpd7+QDZnGhh19ryE/O4T9lt7721+3mDB+In0PpeZNbjgvrz+Ee7xu3fiOBuJ0Z9xvgGrZeM5hrCLRhVIexBHbL+n0oVa39jLewfKdkU9IuplSda3i2gD96I+a8SYjGmR+sa985EHiseIBvyAnurSsbLz9Jz2dS33J6TKhEJIbHividwAagiPzoiVJ+IYKEegCrCkY0DL8yghROgV1B7Eo/OmhAqut8LlZR80sJ2o7Q3UErVGNamsggmLvSmmDpDAedJVbHBpFEPDbM5KHhdiE4/Y25IjhwRL4oM0yTtUbdeRLlmlG+UwW0Ag1FbzWBCa+VaoQm9ZZlmmdkm6XKJjuURX3znu2SVpY4G3fUowkUfC0LQVOhijzauMdIKb8TDNKZGWEHzcn6mwhTjx+Bl+x2gktgq27GdsnbAw3WhRzDlHXWu5gRE24RZyd1qAKDBPvFzSrJbW7SQsl9jmzq+lDyh03lSgXPpLA2Z3DRKRkMz7Z1/uRXF4n/jCX91cvX4t1N2lxF5itx6YaiRdfwGp9BcL5iqdq+1kPG5UfbfGwqtxp5MX/qKyblwI/EdU0txamjljYsW4J/P8ueeUBrTZjGAHg6ZiOTWpm3s7ziMTiSyRiUd7eDjWFkbV0uexj/KN9fv8d/p0q8htwOsxJrstAdzR1ZbufwZ4Wkmdecygqkfc2wCaOd2ofnZhb8+3hKxIUUtg3AWstAHud41OAlbCWPeyFLLwIklSV4LipB1ctye+u8wfP4r0Gk3xrMy//uZ8ilPZkG34puCSTE+/K+gdviwjptWVTw7F43ukRerELvWaY9bE2/odvDt+Hwd+S5EH+n98cnARHf4HSTS1xQ==

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by whenTheMorningDark** [comment]
这个问题的根本原因在于 components\drawer\drawer.vue 组件的第一层插槽没有添加 v-if 判断，由于 Masker 组件中也有一个插槽，这导致组件渲染了两次。通常情况下，这不会造成影响。然而，如果涉及到嵌套的业务组件，并且这些组件中包含 HTTP 请求，那么确实会引发问题。我已经在本地解决了这个问题，以下是部分解决方案的代码思路：

**Comment by whenTheMorningDark** [comment]
这个问题的根本原因在于 components\drawer\drawer.vue 组件的第一层插槽没有添加 v-if 判断，由于 Masker 组件中也有一个插槽，这导致组件渲染了两次。通常情况下，这不会造成影响。然而，如果涉及到嵌套的业务组件，并且这些组件中包含 HTTP 请求，那么确实会引发问题。我已经在本地解决了这个问题，以下是部分解决方案的代码思路：

```js
const rendered = ref(false)
watch(
    () => props.active,
    value => {
      currentActive.value = value
      rendered.value = true
    }
 )
onMounted(() => {
  if (currentActive.value) {
    rendered.value = true // enables lazy rendering
  }
})
<div v-if="rendered" :id="bodyId" :class="nh.be('content')">
  <slot v-bind="slotParams"></slot>
</div>

```
这是我的解决思路，看下作者有无其它方案，期待回复。
