### ISSUE TITLE
Nuxt3打包后Message消息提醒的css样式丢失了

### ISSUE THREAD

**Issue by lxyongit** [vexip-ui/vexip-ui#504]
### Describe the bug

build后的
<img width="914" alt="image" src="https://github.com/user-attachments/assets/b84f4847-db45-437c-840a-617ae0dcbc56">
dev的
<img width="658" alt="image" src="https://github.com/user-attachments/assets/72135a00-3a73-45e9-8d73-4aacb3d631eb">

### Reproduction

/

### System Info

```shell
nuxt 3.12.4
vexip-ui 2.3.13
@vexip-ui/nuxt 1.3.1
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vexip UI issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
请提供一个可复现的项目并提供复现步骤。

**Comment by lxyongit** [comment]
> 请提供一个可复现的项目并提供复现步骤。

[https://github.com/lxyongit/vexip-ui-test.git](url)
这个项目只有vexip-ui相关的依赖，现在dev都不显示message了

**Comment by qmhc** [comment]
你手动引入的话需要自行引入样式。

最佳实践你应该按照 [文档](https://www.vexipui.com/zh-CN/guide/ssr.html) 所描述的方式使用各类组件。

**Comment by lxyongit** [comment]
> 你手动引入的话需要自行引入样式。
> 
> 最佳实践你应该按照 [文档](https://www.vexipui.com/zh-CN/guide/ssr.html) 所描述的方式使用各类组件。

@vexip-ui/nuxt已经有用这个了，而且其他像VSelect组件啥的都是正常的
