### ISSUE TITLE
add calendar type to date-picker and calendar 

### ISSUE THREAD

**Issue by alphaelf** [vexip-ui/vexip-ui#509]
### Description

many people today use calendar type other than Gregorian like Shamsi (solar) or Chinese calendar, it is good to have this option for `date-picker` component  and maybe for `calendar` component have a major calendar type and show one or two alternative calendar type date in each cell with lighten color.

### Suggested solution

we can use date lib like `date-fn`, `momentJs`, `dayjs` and so on that have already plugins for other calendar types

### Alternative

some alternative component that i found for jalali type:
[Vue persian datetime picker](https://talkhabi.github.io/vue-persian-datetime-picker/)
[Vue 3 Persian Datepicker](https://mohammadoftadeh.github.io/vue3-persian-datepicker/)
[Vue Persian Datepicker](https://alireza-ab.ir/datepicker)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.vexipui.com/).
- [X] Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that request the same feature to avoid creating a duplicate.

**Comment by qmhc** [comment]
It seems to be a RTL problem about DatePicker/TimerPicker/Calendar?

**Comment by alphaelf** [comment]
no it's about calendar systems, [look here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/getCalendars)
so we can get `calendar system name` and `start of week` from props and the rest is a utile method that give us **first weekday of month in  given calendar system** and total days of that month (28,29,30 or 31) then we make a `view-layer` over calendar cells for represents calendar in specifies calendar system (chinese, indian, islamic, japanese, persian, ...) and actual gregorian date remains untouched for date calculations

**Comment by qmhc** [comment]
I try to understand and reexplain: we need a calendar-system(instance) to provide context or calculation (like `Dayjs`) and it can work with DatePicker and Calendar components? (now they only can work with Date class)

**Comment by alphaelf** [comment]
`dayjs` has solution with this plugin [`@calidy/dayjs-calendarsystems`](https://github.com/calidy-com/dayjs-calendarsystems) 
i make simple component with it and its very simple:
```vue
<script lang="ts" setup>
import dayjs from 'dayjs'
import calendarSystems from '@calidy/dayjs-calendarsystems'
import PersianCalendarSystem from '@calidy/dayjs-calendarsystems/calendarSystems/PersianCalendarSystem'
import HijriCalendarSystem from '@calidy/dayjs-calendarsystems/calendarSystems/HijriCalendarSystem'
/* import 'dayjs/locale/fa' many locale translation already exists and we can import */

dayjs.extend(calendarSystems)
dayjs.registerCalendarSystem('persian', new PersianCalendarSystem())
dayjs.registerCalendarSystem('islamic', new HijriCalendarSystem())
const props = defineProps<{
  calendar?: 'gregory' | 'islamic' | 'persian' // hebrew, ethiopic and amazigh systems already implemented and other system can implemet easly
  startOfWeek?: 0 | 1 | 2 | 3 | 4 | 5 | 6
}>()
const today = computed(() => dayjs(new Date()).toCalendarSystem(props.calendar ?? 'gregory'))
const wd = ['Su', 'Mo', 'Th', 'We', 'Tr', 'Fr', 'Sa'] // weekdays
const wdi = computed( // weekdays index
  () => Array
    .from({length: 7}, (_, i) => i + props.startOfWeek)
    .map(c => c > 6 ? c - 7 : c)
)
const si = computed(() => wdi.value.indexOf(today.value.startOf('month').day())) // index of start-of-month in weekdays as start point

// and finally we can make our cells matrix of calendar
const cells = computed(() =>
  Array.from({length: 6},
    (_, i) =>
      Array.from({length: 7},
        (__, j) => {
          const diff = i * 7 - si.value + j
          return diff < 0 ? today.value.startOf('month').subtract(Math.abs(diff), 'days') : today.value.startOf('month').add(diff, 'days')
        }
      )
  )
)
</script>
```
with `wd` i have week day names and with cells i can create calendar (i use `pug` for my template and `unocss` for styling):
```vue
<template lang="pug">
.bg-white.p3.gap-y-px.font-sans
  .flex.justify-between.items-center.py-3.font-black
    .text-xl {{ today.format('MMMM') }}
    .text-3xl {{ today.format('YYYY') }}
  .gap-x-px.items-center
    .s-8.bg-zinc-2.flex.justify-center.items-center.rounded(v-for="key in wdi" :key="key") {{ wd[key] }}
  .gap-x-px.items-center(v-for="(row, k) in cells" :key="k")
    template(v-for="(day, key) in row" :key="key")
      .s-8.flex.justify-center.items-center.rounded.bg-zinc-1.text-zinc-3(v-if="day.get('M') !== today.get('M')" ) {{ day.get('D') }}
      .s-8.flex.justify-center.items-center.rounded(v-else, :class="day.date() === today.date() ?'bg-sky-5 text-white':'bg-zinc-1'") {{ day.get('D') }}
</template>

**Comment by qmhc** [comment]
Could this feature be achieved by providing a slot for custom rendering of each calendar cell (with date value parameter)?

**Comment by alphaelf** [comment]
maybe, but we must do same thing every where that we use date-picker or calendar, how about config-provider ?
can you add method property as `cellCustomRender` in config provider?

**Comment by qmhc** [comment]
Could you try 2.3.15? Refer to https://www.vexipui.com/en-US/component/config-provider.html, now you can use slots prop to specify rendering method for each slot with same name (currently only Calendar and DatePicker are effective).
